# Generated by Cognia | 2026-08-17T19:59:20.051441
# Category: Automated pet feeder that tracks feeding times and pet activity
# Score: auto-asignado 5.1/10 (SIN VERIFICAR)
# Origin: self-proposed idea

import time
import random

# Constants
FEEDING_INTERVAL = 3600  # seconds (1 hour)
FEED_AMOUNT = 10  # grams
FEEDER_CAPACITY = 1000  # grams
ACTIVITY_THRESHOLD = 20  # percentage of time pet is active

# Sample data
pet_activity_log = []
feeding_log = []

def simulate_pet_activity():
    """Simulate pet activity with a random percentage of active time."""
    active_time = random.randint(0, 100)  # Random percentage between 0 and 100
    pet_activity_log.append(active_time)
    return active_time

def check_feeder_capacity():
    """Check if the feeder has enough capacity to feed."""
    total_feeds = sum(entry[1] for entry in feeding_log)
    remaining_capacity = FEEDER_CAPACITY - total_feeds
    if remaining_capacity < FEED_AMOUNT:
        print("PASS: Feeder capacity is low. Consider refilling.")
    else:
        print("PASS: Feeder capacity is sufficient.")

def check_pet_activity():
    """Check if the pet is active enough."""
    average_activity = sum(pet_activity_log) / len(pet_activity_log) if pet_activity_log else 0
    if average_activity >= ACTIVITY_THRESHOLD:
        print("PASS: Pet activity is sufficient.")
    else:
        print("FAIL: Pet activity is below threshold.")

def feed_pet():
    """Simulate feeding the pet."""
    feeding_log.append((time.time(), FEED_AMOUNT))
    print(f"PASS: Pet fed {FEED_AMOUNT} grams at {time.strftime('%Y-%m-%d %H:%M:%S')}")

def main():
    """Main function to run the automated pet feeder."""
    print("Starting Automated Pet Feeder...")
    
    while True:
        # Simulate pet activity
        active_time = simulate_pet_activity()
        print(f"Pet activity: {active_time}%")
        
        # Check pet activity
        check_pet_activity()
        
        # Check feeder capacity
        check_feeder_capacity()
        
        # Feed pet if conditions are met
        if len(pet_activity_log) >= 3 and average_activity >= ACTIVITY_THRESHOLD:
            feed_pet()
        
        # Wait for the next feeding interval
        time.sleep(FEEDING_INTERVAL)

if __name__ == "__main__":
    main()