# Generated by Cognia | 2026-08-13T00:59:42.165680
# Category: text similarity analyzer with sample texts
# Score: auto-asignado 8.0/10 (SIN VERIFICAR)
# Origin: predefined category

# -*- coding: utf-8 -*-
# Text Similarity Analyzer — automatic, fun, and fully standard-lib

# Clear terminal
print('\033[2J\033[H', end='')

# --- ASCII art header ---
def draw_header():
    lines = [
        "   /\\_/\\",
        "  ( o.o )",
        "   /  ^  \\  <-- magnifying glass",
        "  (  |  )",
        "   \\_/\\/",
    ]
    for line in lines:
        print(line, end='\n')
    print()

# --- Colors and separators ---
def color(text, fg=''):
    # fg: '32' (green), '36' (cyan), '97' (white)
    return f"\033[{fg}m{text}\033[0m"

def print_separator(width=50):
    print(color(f"{'=' * width}", fg='36'))

# --- Sample texts (knowledge_python & animal theme) ---
SAMPLE_TEXTS = (
    "the algorithm of knowledge",
    "the fox runs across the field",
    "python is a snake that lives in code",
    "the bear hibernates in the den",
    "the cat hunts mice near the river",
)

# --- Metrics (functions) ---
def lcs_length(a, b):
    """Longest common subsequence length (DP)."""
    m, n = len(a), len(b)
    # Use a 2xN DP row to save space
    prev = [0] * (n + 1)
    for i in range(1, m + 1):
        curr = [0] * (n + 1)
        if a[i-1] == b[0]:
            curr[1] = 1
        for j in range(2, n + 1):
            if a[i-1] == b[j-1]:
                curr[j] = prev[j-1] + 1
            else:
                curr[j] = max(prev[j], curr[j-1])
        prev = curr
    return prev[n]

def lcs_substring_length(a, b):
    """Longest common contiguous substring length (DP)."""
    m, n = len(a), len(b)
    prev = [0] * (n + 1)
    max_len = 0
    for i in range(1, m + 1):
        curr = [0] * (n + 1)
        if a[i-1] == b[0]:
            curr[1] = 1
            max_len = max(max_len, 1)
        for j in range(2, n + 1):
            if a[i-1] == b[j-1]:
                curr[j] = prev[j-1] + 1
                max_len = max(max_len, curr[j])
            else:
                curr[j] = max(prev[j], curr[j-1])
        prev = curr
    return max_len

def token_jaccard(a, b):
    """Token (word) Jaccard similarity."""
    tokens_a = set(a.split())
    tokens_b = set(b.split())
    if not tokens_a or not tokens_b:
        return 0.0
    inter = tokens_a & tokens_b
    union = tokens_a | tokens_b
    return len(inter) / len(union)

def trigram_jaccard(a, b):
    """Trigram (3-char) Jaccard similarity."""
    # Generate overlapping 3-char tokens
    tokens_a = set(a[i:i+3] for i in range(len(a)-2))
    tokens_b = set(b[i:i+3] for i in range(len(b)-2))
    if not tokens_a or not tokens_b:
        return 0.0
    inter = tokens_a & tokens_b
    union = tokens_a | tokens_b
    return len(inter) / len(union)

# Move longest_common_substring out of verify_lcs_sub so it's available at module level
def longest_common_substring(a, b):
    """Longest common substring length via classic 2D DP."""
    m, n = len(a), len(b)
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if a[i-1] == b[j-1]:
                dp[i][j] = dp[i-1][j-1] + 1
            else:
                dp[i][j] = max(dp[i-1][j], dp[i][j-1])
    return dp[m][n]

metrics = {
    "lcs": lcs_length,
    "lcs_sub": lcs_substring_length,
    "jaccard": token_jaccard,
    "trigram_jaccard": trigram_jaccard,
}

# --- Pairwise computation helper ---
def pairwise(texts, metrics):
    """Return a dict of results for each unique pair (i < j)."""
    results = {}
    for i, t1 in enumerate(texts):
        for j, t2 in enumerate(texts):
            if i >= j:
                continue
            key = f"{i}-{j}"
            results[key] = {name: func(t1, t2) for name, func in metrics.items()}
    return results

# --- Verification of one metric (LCS substring) ---
def verify_lcs_sub():
    # Compute LCS substring length for pair (0,1) both ways: DP and also via a simpler method
    t0, t1 = SAMPLE_TEXTS[0], SAMPLE_TEXTS[1]
    computed = lcs_substring_length(t0, t1)
    # A naive longest common substring using DP that also records the substring itself
    expected = longest_common_substring(t0, t1)
    return computed == expected

# --- Main execution ---
draw_header()
print_separator()
print(color("Pairwise Similarity Results", fg='97'))
print_separator()

pair_results = pairwise(SAMPLE_TEXTS, metrics)

for key, vals in pair_results.items():
    print(f"Pair {key}:")
    for name, val in vals.items():
        print(f"  {name}: {val}")
    print()

print_separator()
print(color("Verification (LCS substring DP vs classic DP):", fg='97'))
print(f"   Expected (DP) length: {longest_common_substring(SAMPLE_TEXTS[0], SAMPLE_TEXTS[1])}")
print(f"   Computed (lcs_sub) length: {lcs_substring_length(SAMPLE_TEXTS[0], SAMPLE_TEXTS[1])}")
print(f"   Match: {verify_lcs_sub()}")
print_separator()