# Generated by Cognia | 2026-08-17T23:50:59.630272
# Category: di hola en 3 palabras
# Score: auto-asignado 7.3/10 (SIN VERIFICAR)
# Origin: predefined category

# Constants
LOOPS = 3
DELAY = 1  # seconds

# Sample data: List of greetings in three languages
greetings = [
    ("Spanish", "Hola"),
    ("French", "Bonjour"),
    ("German", "Hallo")
]

def print_greetings():
    for _ in range(LOOPS):
        for language, greeting in greetings:
            print(f"{language}: {greeting}")
        print('\033[2J\033[H', end='')  # Clear the terminal
        time.sleep(DELAY)

if __name__ == "__main__":
    import time
    print("Di Hola en 3 Palabras")
    print("Starting the program...")
    print_greetings()
    print("Program finished.")