# Generated by Cognia | 2026-04-05T21:18:07.212605
# Category: procedural story generator
# Score: 7.1/10

import random
import time

print('\033[2J\033[H', end='')  # clear terminal

def generate_story(theme, length):
    adjectives = ["vibrant", "turbulent", "sparkling", "chaotic"]
    nouns = ["city", "beach", "mountains", "forest"]
    verbs = ["swept", "soared", "exploded", "crashed"]

    story = ""

    if theme == "brasil":
        story += f"In the heart of {random.choice(adjectives)} Rio, "
        nouns.append("festival")
        story += f"a colorful {random.choice(nouns)} was taking place."

    elif theme == "christoph":
        story += f"Christoph's adventurous spirit was "
        verbs.append("shining")
        story += f"as he explored the mystical {random.choice(adjectives)} forest."

    for _ in range(length):
        if random.random() < 0.2:
            nouns.pop()
        elif random.random() < 0.3:
            adjectives.pop()
        else:
            verbs.append(random.choice(["jumped", "ran", "walked", "crawled"]))
        story += f"{random.choice(verbs)} through the {random.choice(adjectives)} {random.choice(nouns)}, "
        if _ == length - 1:
            story += f"feeling {random.choice(['exhilarated', 'scared', 'elated'])}."
    return story

def main():
    print("Story Spinner")
    time.sleep(1)
    theme = input("Choose a theme (brasil/christoph), or type 'custom' for more options: ")
    if theme == "custom":
        print("Available themes:")
        print("1. brazil")
        print("2. christoph")
        choice = input("Enter the number of your chosen theme, or type 'other' to define a custom theme: ")
        if choice == '1':
            theme = 'brasil'
        elif choice == '2':
            theme = 'christoph'
        else:
            custom_adjectives = input("Define 3 adjectives (space-separated): ").split()
            custom_nouns = input("Define 3 nouns (space-separated): ").split()
            custom_verbs = input("Define 3 verbs (space-separated): ").split()
            theme = "custom"
    length = int(input("Enter the story length: "))
    print(generate_story(theme, length))

if __name__ == "__main__":
    main()