# Generated by Cognia | 2026-04-05T20:57:48.030130
# Category: fractal pattern renderer in terminal
# Score: 7.3/10

import random
from time import sleep
print('\033[2J\033[H', end='')
def clear_terminal():
    pass

def main_menu():
    while True:
        print("Fractal Pattern Renderer")
        print("1. Mandelbrot Fractal")
        print("2. Julia Fractal")
        print("3. Quit")
        choice = input("Enter your choice: ")
        if choice == "1":
            mandelbrot()
        elif choice == "2":
            julia()
        elif choice == "3":
            clear_terminal()
            break
        else:
            print("Invalid choice. Please try again.")

def mandelbrot():
    width = 100
    height = 50
    scale = 0.4

    for i in range(height):
        line = ""
        for j in range(width):
            x = (-3 * scale) + (j / width) * 6 * scale
            y = (-2 * scale) + (i / height) * 4 * scale
            c = complex(x, y)
            z = complex(0, 0)
            for k in range(256):
                if abs(z) > 2:
                    line += "* "
                    break
                else:
                    z = z*z + c
        print(line)

def julia():
    width = 100
    height = 50
    scale = 0.4

    for i in range(height):
        line = ""
        for j in range(width):
            x = (-2 * scale) + (j / width) * 3 * scale
            y = (-1 * scale) + (i / height) * 2 * scale
            c = complex(x, y)
            z = complex(0, 0)
            a = complex(-0.8, 0.156)
            for k in range(256):
                if abs(z) > 2:
                    line += "* "
                    break
                else:
                    z = z*z + c
        print(line)

if __name__ == "__main__":
    while True:
        main_menu()
        sleep(1)