# Generated by Cognia | 2026-08-31T16:21:09.902308
# Category: number theory explorer that prints interesting patterns
# Score: auto-asignado 9.5/10 (SIN VERIFICAR)
# Origin: predefined category

# -*- coding: utf-8 -*-
"""
Zoo of Number Theory — an animal-themed number-theory explorer.
Every exhibit prints a classic pattern and, where math allows,
verifies a property with a real PASS/FAIL verdict.

Python tricks shown (conocimiento_python):
slice assignment, comprehensions, dicts, bit ops, math.isqrt.
Standard library only. Runs fully automatically.
"""

from math import gcd, isqrt

# ==================== TUNABLE CONSTANTS ====================
LIMIT          = 200    # prime / totient upper bound
GRID_W         = 40     # characters per grid row
COLLATZ_SEEDS  = [7, 15, 27, 61, 233]
MOD_PRIMES     = [7, 11, 13]
SIERSK_ROWS    = 10     # 2**SIERSK_ROWS rows of the butterfly
FIB_N          = 12     # how many Fibonacci numbers to show
DR_MAX         = 99     # digital-root grid size
PYTH_MAX_C     = 100    # max hypotenuse for triples
AMICABLE_BOUND = 1000   # search bound for amicable pairs
GOLDEN_TOL     = 0.01   # tolerance for golden-ratio check
TOP_HISTOGRAM  = 10     # top entries in phi histogram
DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

VERDICTS = []  # (name, ok) pairs collected during the tour


def record(name, ok, note=""):
    ok = bool(ok)
    VERDICTS.append((name, ok))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}: {note}")


# ==================== MATH HELPERS ====================

def is_prime(n):
    """Trial division — an independent check for the sieve."""
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    d = 3
    while d * d <= n:
        if n % d == 0:
            return False
        d += 2
    return True


def sieve(n):
    """Eratosthenes with fancy slice assignment."""
    mark = [True] * (n + 1)
    mark[0] = mark[1] = False
    for i in range(2, isqrt(n) + 1):
        if mark[i]:
            chunk = mark[i * i::i]
            mark[i * i::i] = [False] * len(chunk)
    return [x for x in range(2, n + 1) if mark[x]]


def phi(n):
    """Euler's totient by factorization."""
    r, d = n, 2
    while d * d <= n:
        if n % d == 0:
            while n % d == 0:
                n //= d
            r = r // d * (d - 1)
        d += 1
    if n > 1:
        r = r // n * (n - 1)
    return r


def dr(n):
    """Digital root (1..9)."""
    while n > 9:
        n = sum(int(c) for c in str(n))
    return n


def sum_proper_divisors(n):
    """Sum of proper divisors, via square-root pairing."""
    if n == 1:
        return 0
    s, d = 1, 2
    while d * d <= n:
        if n % d == 0:
            s += d
            if d != n // d:
                s += n // d
        d += 1
    return s


# ==================== THE NINE EXHIBITS ====================

def exhibit_sieve():
    print(f"\n-- Exhibit 1 | SERPENT SIEVE (snake) | primes <= {LIMIT} as dots")
    print("   Python trick: slice assignment mark[i*i::i]")
    primes = sieve(LIMIT)
    known = set(primes)
    cells = ['●' if n in known else '·' for n in range(1, LIMIT + 1)]
    for r in range(0, len(cells), GRID_W):
        print("   " + " ".join(cells[r:r + GRID_W]))
    check = sum(1 for n in range(2, LIMIT + 1) if is_prime(n))
    record("serpent-sieve", check == len(primes),
           f"counted {len(primes)} primes <= {LIMIT}; trial division agrees ({check})")


def exhibit_collatz():
    print("\n-- Exhibit 2 | FALCON COLLATZ (falcon) | 3x+1 always lands on 1")
    print("   Python trick: while-loop with conditional expression")
    for seed in COLLATZ_SEEDS:
        x, steps, peak = seed, 0, seed
        while x != 1:
            x = 3 * x + 1 if x % 2 else x // 2
            steps += 1
            if x > peak:
                peak = x
        record("falcon-collatz", x == 1,
               f"seed {seed} reaches 1 in {steps} steps, peak value {peak}")


def exhibit_modulo():
    print("\n-- Exhibit 3 | BEETLE MODULAR TABLES (beetle) | multiplication mod p")
    print("   Python trick: list comprehension + custom digit string")
    for p in MOD_PRIMES:
        print(f"   p = {p}")
        print("      " + " ".join(DIGITS[k] for k in range(1, p)))
        ok = True
        for r in range(1, p):
            row = [(r * k) % p for k in range(1, p)]
            print(f" {DIGITS[r]}   " + " ".join(DIGITS[v] for v in row))
            if sorted(row) != list(range(1, p)):
                ok = False
        record("beetle-modulo", ok,
               f"p={p}: every row is a permutation of 1..{p - 1}")


def exhibit_sierpinski():
    n = 1 << SIERSK_ROWS
    print(f"\n-- Exhibit 4 | BUTTERFLY SIERSKINSKI (butterfly) | n ^ (n<<1), {n} rows")
    print("   Python trick: bitwise XOR + bit shifting")
    for i in range(n):
        v = i ^ (i << 1)
        print("   " + "".join("▓" if (v >> b) & 1 else " "
                               for b in range(SIERSK_ROWS)))


def exhibit_fibonacci():
    fibs = [0, 1]
    while len(fibs) < FIB_N:
        fibs.append(fibs[-1] + fibs[-2])
    print(f"\n-- Exhibit 5 | HARE FIBONACCI (hare) | ratios drift toward golden phi")
    print("   Python trick: iterative accumulator, sqrt via **0.5")
    golden = (1 + 5 ** 0.5) / 2
    for i in range(1, FIB_N - 1):
        print(f"   F{i + 2}/F{i + 1} = {fibs[i + 1] / fibs[i]:.6f}")
    last = fibs[-1] / fibs[-2]
    record("hare-fibonacci", abs(last - golden) < GOLDEN_TOL,
           f"last ratio {last:.6f} vs phi = {golden:.6f} (|diff| = {abs(last - golden):.6f})")
    cassini = all(fibs[i] ** 2 - fibs[i - 1] * fibs[i + 1] == (-1) ** (i - 1)
                  for i in range(1, FIB_N - 1))
    record("cassini-identity", cassini,
           f"F(n)^2 - F(n-1)*F(n+1) = (-1)^(n-1) checked for n = 1..{FIB_N - 2}")


def exhibit_totient():
    print(f"\n-- Exhibit 6 | OWL TOTIENTS (owl) | phi(n) up to {LIMIT} + divisor identity")
    print("   Python trick: dict comprehension + histogram bars")
    phis = {n: phi(n) for n in range(1, LIMIT + 1)}
    counts = {}
    for v in phis.values():
        counts[v] = counts.get(v, 0) + 1
    top = max(counts.values())
    for v in sorted(counts, reverse=True)[:TOP_HISTOGRAM]:
        bar = "#" * int(counts[v] * 30 / top)
        print(f"   phi={v:3d}  {bar} ({counts[v]} values)")
    identity = all(sum(phis[d] for d in range(1, n + 1) if n % d == 0) == n
                   for n in range(1, LIMIT + 1))
    record("owl-totient", identity,
           f"sum of phi(d) over divisors d of n equals n, checked for n <= {LIMIT}")


def exhibit_digital_root():
    print(f"\n-- Exhibit 7 | FOX DIGITAL ROOTS (fox) | grid of 1..{DR_MAX}")
    print("   Python trick: generator expression inside sum()")
    cells = [str(dr(n)) for n in range(1, DR_MAX + 1)]
    for r in range(0, len(cells), GRID_W):
        print("   " + " ".join(cells[r:r + GRID_W]))
    ok = all(dr(a * b) == dr(dr(a) * dr(b))
             for a in range(2, 60) for b in range(2, 60))
    record("fox-digital-root", ok,
           "dr(a*b) == dr(dr(a)*dr(b)) checked for a,b in 2..59")


def exhibit_pythagoras():
    print(f"\n-- Exhibit 8 | DOLPHIN PYTHAGOREAN (dolphin) | a^2+b^2=c^2, c <= {PYTH_MAX_C}")
    print("   Python trick: math.isqrt for exact square tests")
    triples = []
    for c in range(5, PYTH_MAX_C + 1):
        for a in range(3, c):
            b2 = c * c - a * a
            b = isqrt(b2)
            if b > 0 and b * b == b2:
                triples.append((a, b, c))
    for a, b, c in triples:
        kind = "primitive" if gcd(a, b) == 1 else "scaled"
        print(f"   {a:3d}^2 + {b:3d}^2 = {c:3d}^2   ({kind})")
    ok = all(a * a + b * b == c * c for a, b, c in triples)
    record("dolphin-pythagoras", ok and triples,
           f"{len(triples)} triples found, all square-sums verified")


def exhibit_amicable():
    print(f"\n-- Exhibit 9 | WALRUS AMICABLE (walrus) | sigma*(a)=b and sigma*(b)=a, <= {AMICABLE_BOUND}")
    print("   Python trick: dict comprehension + dict.get()")
    sd = {n: sum_proper_divisors(n) for n in range(1, AMICABLE_BOUND + 1)}
    pairs = [(a, b) for a, b in sd.items()
             if 1 < a < b <= AMICABLE_BOUND and sd.get(b) == a]
    if pairs:
        for a, b in pairs:
            print(f"   {a} <-> {b}   (sigma*({a})={sd[a]}, sigma*({b})={sd[b]})")
            record("walrus-amicable", sd[a] == b and sd[b] == a,
                   f"pair ({a}, {b}) round-trips correctly")
    else:
        record("walrus-amicable", False, "no amicable pairs found (unexpected!)")


# ==================== SUMMARY ====================

def summary():
    passed = sum(1 for _, ok in VERDICTS if ok)
    total = len(VERDICTS)
    print("\n" + "=" * 64)
    print(f" ZOO CLOSED | {passed}/{total} verifications PASS | "
          f"{total - passed} FAIL | {total} checks total")
    print("=" * 64)


def main():
    print('\033[2J\033[H', end='')  # clear terminal (no os.system)
    print("=" * 64)
    print(" ZOO OF NUMBER THEORY  |  conocimiento_python edition")
    print(" Nine animal exhibits, each printing a number-theory")
    print(" pattern. Every check gets a real PASS/FAIL verdict.")
    print("=" * 64)

    exhibit_sieve()
    exhibit_collatz()
    exhibit_modulo()
    exhibit_sierpinski()
    exhibit_fibonacci()
    exhibit_totient()
    exhibit_digital_root()
    exhibit_pythagoras()
    exhibit_amicable()
    summary()


if __name__ == "__main__":
    main()