# Generated by Cognia | 2026-07-20T01:32:48.527014
# Category: cola de prioridad con heapq que soporte cambiar la prioridad de un elemento ya insertado, con una clase de unittest con al menos 3 metodos test_ y unittest.main(exit=False)
# Score: 7.3/10
# Origin: predefined category

import heapq
import unittest

class PriorityQueue:
    def __init__(self):
        self.heap = []
        self.entry_finder = {}  # mapping of tasks to entries
        self.REMOVED = '<removed-task>'  # placeholder for a removed task
        self.counter = 0  # unique sequence count

    def add_task(self, task, priority=0):
        'Add a new task or update the priority of an existing task'
        if task in self.entry_finder:
            self.remove_task(task)
        count = self.counter
        entry = [priority, count, task]
        self.entry_finder[task] = entry
        heapq.heappush(self.heap, entry)
        self.counter += 1

    def remove_task(self, task):
        'Mark an existing task as REMOVED.  Raise KeyError if not found.'
        entry = self.entry_finder.pop(task)
        entry[-1] = self.REMOVED

    def pop_task(self):
        'Remove and return the lowest priority task. Raise KeyError if empty.'
        while self.heap:
            priority, count, task = heapq.heappop(self.heap)
            if task is not self.REMOVED:
                del self.entry_finder[task]
                return task
        raise KeyError('pop from an empty priority queue')

    def change_priority(self, task, new_priority):
        'Change the priority of an existing task'
        if task in self.entry_finder:
            self.remove_task(task)
            self.add_task(task, new_priority)

class PriorityQueueTest(unittest.TestCase):
    def test_add_task(self):
        pq = PriorityQueue()
        pq.add_task('task1', 1)
        self.assertEqual(pq.pop_task(), 'task1')

    def test_remove_task(self):
        pq = PriorityQueue()
        pq.add_task('task1', 1)
        pq.add_task('task2', 2)
        pq.remove_task('task1')
        self.assertEqual(pq.pop_task(), 'task2')

    def test_change_priority(self):
        pq = PriorityQueue()
        pq.add_task('task1', 1)
        pq.add_task('task2', 2)
        pq.change_priority('task1', 3)
        self.assertEqual(pq.pop_task(), 'task2')
        self.assertEqual(pq.pop_task(), 'task1')

if __name__ == '__main__':
    # Demo of PriorityQueue
    print('Priority Queue Demo:')
    pq = PriorityQueue()
    pq.add_task('task1', priority=2)
    pq.add_task('task2', priority=1)
    pq.add_task('task3', priority=3)
    print(f'Added tasks: task1 (priority 2), task2 (priority 1), task3 (priority 3)')
    print(f'Popped task: {pq.pop_task()}')  # Should pop task2
    pq.change_priority('task1', new_priority=0)
    print(f'Changed priority of task1 to 0')
    print(f'Popped task: {pq.pop_task()}')  # Should pop task1
    print(f'Popped task: {pq.pop_task()}')  # Should pop task3

    # Run unittests
    unittest.main(exit=False)