# Generated by Cognia | 2026-08-29T18:46:36.009500
# Category: text similarity analyzer with sample texts
# Score: auto-asignado 9.5/10 (SIN VERIFICAR)
# Origin: predefined category

# -*- coding: utf-8 -*-
"""Text Similarity Analyzer - 4 metrics over built-in sample texts.

The sample corpus mixes Python-knowledge texts (conocimiento_python)
with animal texts. Every metric self-verifies with PASS/FAIL checks
before the program prints a final verdict. Runs 100% automatically.
"""

import difflib
import math
import random
import re
from collections import Counter

# -------------------------------------------------------------- ANSI bits --
RESET, BOLD, DIM = '\033[0m', '\033[1m', '\033[2m'
RED, GREEN, YELLOW = '\033[91m', '\033[92m', '\033[93m'
BLUE, CYAN, MAGENTA = '\033[94m', '\033[96m', '\033[95m'
WHITE = '\033[97m'


def c(text, *codes):
    """Wrap text in ANSI codes."""
    return ''.join(codes) + str(text) + RESET


def bar(value, width=16):
    n = int(round(value * width))
    return c('█' * n, GREEN) + c('░' * (width - n), DIM)


def heat_color(v):
    if v >= 0.9:
        return GREEN
    if v >= 0.4:
        return YELLOW
    if v >= 0.15:
        return BLUE
    return DIM


BANNER = r'''
      _____
    /  o  o \
    |   ^   |
     \ ~~~~ /
    / ~~~~ \
   /~~~~~~~~\
    \______/
'''

# ----------------------------------------------------------- sample corpus --
SAMPLES = [
    ('P1', 'python language',
     'Python is a programming language with simple syntax used for writing clean code.'),
    ('P2', 'python library',
     'Python is also used for data analysis, so writing simple code keeps projects clean.'),
    ('P3', 'panda animal',
     'A panda is a gentle animal that eats bamboo in the forests of china.'),
    ('P4', 'python snake',
     'The python is a snake that lives quietly and sheds its skin often.'),
    ('P5', 'ocean fish',
     'Fish glide through coral reefs where sunlight filters into the deep ocean.'),
]
EXPECTED_TOP = ('P1', 'P2')
EXPECTED_KEYWORD = 'python'

# -------------------------------------------------------- similarity metrics --
def tokenize(text):
    return re.findall(r"[a-z]+(?:'[a-z]+)?", text.lower())


def jaccard(a, b):
    A, B = set(tokenize(a)), set(tokenize(b))
    return len(A & B) / len(A | B) if (A | B) else 0.0


def cosine(a, b):
    va, vb = Counter(tokenize(a)), Counter(tokenize(b))
    dot = sum(va[k] * vb[k] for k in va.keys() & vb.keys())
    na = math.sqrt(sum(x * x for x in va.values()))
    nb = math.sqrt(sum(x * x for x in vb.values()))
    return dot / (na * nb) if na and nb else 0.0


def bigrams(text):
    t = re.sub(r"[^a-z ]", "", text.lower())
    t = re.sub(r"\s+", " ", t).strip()
    return {t[i:i + 2] for i in range(len(t) - 1)}


def bigram_jaccard(a, b):
    A, B = bigrams(a), bigrams(b)
    return len(A & B) / len(A | B) if (A | B) else 0.0


def seq_ratio(a, b):
    return difflib.SequenceMatcher(None, a.lower(), b.lower()).ratio()


METRICS = [
    ('word_jaccard', jaccard),
    ('tf_cosine', cosine),
    ('char_bigram_jaccard', bigram_jaccard),
    ('seq_ratio', seq_ratio),
]

# ------------------------------------------------------------- verification --
def run_checks(fn):
    """Run 5 self-checks on metric fn; return (passed, checks, pairs, matrix)."""
    ids = [s[0] for s in SAMPLES]
    texts = [s[2] for s in SAMPLES]
    n = len(texts)
    checks = []

    self_vals = [fn(texts[i], texts[i]) for i in range(n)]
    self_ok = all(abs(v - 1.0) < 1e-9 for v in self_vals)
    checks.append(('SELF', self_ok,
                   f'{sum(1 for v in self_vals if abs(v - 1.0) < 1e-9)}/{n} self-scores == 1.0'))

    matrix, range_bad = {}, 0
    for i in range(n):
        for j in range(n):
            v = fn(texts[i], texts[j])
            matrix[(ids[i], ids[j])] = v
            if not (0.0 <= v <= 1.0):
                range_bad += 1
    checks.append(('RANGE', range_bad == 0, f'{n * n} cells in [0,1] (out={range_bad})'))

    sym_pairs, sym_bad = 0, 0
    for i in range(n):
        for j in range(i + 1, n):
            v_ab, v_ba = fn(texts[i], texts[j]), fn(texts[j], texts[i])
            sym_pairs += 1
            if abs(v_ab - v_ba) > 1e-12:
                sym_bad += 1
    checks.append(('SYMMETRY', sym_bad == 0, f'{sym_pairs} mirror pairs (violations={sym_bad})'))

    pairs = [(matrix[(ids[i], ids[j])], ids[i], ids[j])
             for i in range(n) for j in range(i + 1, n)]
    pairs.sort(key=lambda p: p[0], reverse=True)
    top = (pairs[0][1], pairs[0][2])
    checks.append(('TOPPAIR', top == EXPECTED_TOP,
                   f'top={top} expected={EXPECTED_TOP} score={pairs[0][0]:.3f}'))

    idx = {pid: i for i, pid in enumerate(ids)}
    toks = [set(tokenize(t)) for t in texts]
    shared = toks[idx[top[0]]] & toks[idx[top[1]]]
    checks.append(('CONTENT', EXPECTED_KEYWORD in shared,
                   f'shared keyword "{EXPECTED_KEYWORD}" found (shared={len(shared)} tokens)'))

    passed = sum(1 for _, ok, _ in checks if ok)
    return passed, checks, pairs, matrix


# ------------------------------------------------------------------- main --
def main():
    print('\033[2J\033[H', end='')
    print(c(BANNER, BOLD, GREEN))
    print('  ' + c('─' * 70, DIM))
    print('  ' + c('TEXT SIMILARITY ANALYZER', BOLD, CYAN)
          + c('   sample texts: python knowledge + animals', DIM))
    print('  ' + c('─' * 70, DIM))

    n = len(SAMPLES)
    npairs = n * (n - 1) // 2
    print(c(f'\n[1] SAMPLE CORPUS — {n} texts, {npairs} pairs/metric, '
            f'{len(METRICS)} metrics, {n * n} cells checked', BOLD, YELLOW))
    token_sets = {}
    for pid, label, text in SAMPLES:
        toks = tokenize(text)
        token_sets[pid] = set(toks)
        print(f'   {c(pid, BOLD, MAGENTA)}  {c(f"{label:<18}", CYAN)}  {text}')
        print(f'      {c(str(len(toks)) + " tokens, " + str(len(token_sets[pid])) + " unique", DIM)}')

    total_pass = total = 0
    heat = None
    for midx, (name, fn) in enumerate(METRICS, 1):
        passed, checks, pairs, matrix = run_checks(fn)
        total_pass += passed
        total += len(checks)
        print(c(f'\n[2.{midx}] METRIC — {name}', BOLD, YELLOW))
        for rank, (score, k1, k2) in enumerate(pairs[:3], 1):
            print(f'   #{rank}  {c(k1 + " × " + k2, BOLD, MAGENTA)}  '
                  f'{bar(score)}  {score:.3f}')
        for cname, ok, detail in checks:
            verdict = c('PASS', BOLD, GREEN) if ok else c('FAIL', BOLD, RED)
            print(f'      [{verdict}] {cname:<9} {c(detail, DIM)}')
        if name == 'tf_cosine':
            heat = matrix

    ids = [s[0] for s in SAMPLES]
    print(c('\n[3] HEATMAP — tf_cosine matrix', BOLD, YELLOW))
    print('        ' + '  '.join(c(x, BOLD) for x in ids))
    for i in ids:
        row = '  '.join(c(f'{heat[(i, j)]:4.2f}', heat_color(heat[(i, j)])) for j in ids)
        print(f'   {c(f"{i:<6}", BOLD)}{row}')

    random.seed(2024)
    a, b = random.sample(ids, 2)
    ta, tb = token_sets[a], token_sets[b]
    print(c(f'\n[4] SPOTLIGHT — random pair {a} × {b} (seed=2024)', BOLD, YELLOW))
    print(f'   shared : {c(" ".join(sorted(ta & tb)) or "(none)", GREEN)}')
    print(f'   {a} only : {c(" ".join(sorted(ta - tb)), DIM)}')
    print(f'   {b} only : {c(" ".join(sorted(tb - ta)), DIM)}')

    print('\n  ' + c('─' * 70, DIM))
    print(c('[5] FINAL VERDICT', BOLD, WHITE))
    print(f'   checks passed: {total_pass}/{total}')
    if total_pass == total:
        print(c('   (OK) ALL METRICS VERIFIED — SIMILARITY ENGINE: PASS', BOLD, GREEN))
    else:
        print(c('   (XX) SOME CHECKS FAILED — SIMILARITY ENGINE: FAIL', BOLD, RED))


if __name__ == '__main__':
    main()