# Generated by Cognia | 2026-07-25T11:31:59.284817
# Category: juego Minecraft
# Score: 7.8/10
# Origin: predefined category

import random

# Constantes y datos iniciales
BLOQUE_TERRA = 1
BLOQUE_AIRE = 0
BLOQUE_PIEDRA = 2
ANCHO = 40
ALTO = 20
POS_INICIAL = (1, 1)
BLOQUES_INICIALES = [(POS_INICIAL, BLOQUE_TERRA)]
JUGADOR = (1, 1)
BLOQUES_JUGADOR = [(JUGADOR, BLOQUE_TERRA)]
POS_JUGADOR = JUGADOR

# Funciones auxiliares
def crear_mundo(ancho, alto):
    return [[BLOQUE_AIRE for _ in range(ancho)] for _ in range(alto)]

def colocar_bloque(mundo, pos, bloque):
    x, y = pos
    if 0 <= x < ANCHO and 0 <= y < ALTO:
        mundo[y][x] = bloque

def mover_jugador(mundo, pos_nueva):
    global POS_JUGADOR
    x, y = pos_nueva
    if 0 <= x < ANCHO and 0 <= y < ALTO:
        colision = False
        for bloque in BLOQUES_JUGADOR:
            if bloque[0] == pos_nueva:
                colision = True
                break
        if not colision:
            BLOQUES_JUGADOR.append((pos_nueva, BLOQUE_TERRA))
            BLOQUES_INICIALES.append((pos_nueva, BLOQUE_TERRA))
            POS_JUGADOR = pos_nueva
            return True
    return False

def dibujar_mundo(mundo):
    for y in range(ALTO):
        for x in range(ANCHO):
            if (x, y) == POS_JUGADOR:
                print('P', end=' ')
            else:
                print(' ' if mundo[y][x] == BLOQUE_AIRE else 'X', end=' ')
        print()

def actualizar_juego():
    nuevo_mundo = crear_mundo(ANCHO, ALTO)
    for bloque in BLOQUES_INICIALES + BLOQUES_JUGADOR:
        colocar_bloque(nuevo_mundo, bloque[0], bloque[1])
    return nuevo_mundo

# Iniciar el juego
mundo = actualizar_juego()

# Juego automático
for _ in range(100):
    nueva_pos = (POS_JUGADOR[0] + random.choice([-1, 0, 1]), POS_JUGADOR[1] + random.choice([-1, 0, 1]))
    if mover_jugador(mundo, nueva_pos):
        mundo = actualizar_juego()
    print('\033[2J\033[H', end='')  # Limpiar la terminal
    dibujar_mundo(mundo)
    print(f'Posicion del jugador: {POS_JUGADOR}')
print('Fin del juego')