# Generated by Cognia | 2026-04-06T21:39:41.593818
# Category: Automated poetry generator based on user-inputted lyrics and a random poem selection algorithm
# Score: 6.5/10
# Origin: self-proposed idea

import sys

def clear_terminal():
    print('\033[2J\033[H', end='')

def main():
    clear_terminal()
    while True:
        text = input("Enter your poem (maximum 100 characters): ")
        if len(text) > 100:
            print("Your poem is too long. Please try again.")
        else:
            poem = "\n".join([f"{char}{word}" for char, word in zip([" ".join(random.choice(range(1,11))) for _ in range(len(text))], text.lower())])
            clear_terminal()
            print(poem)

if __name__ == "__main__":
    main()