"""
tests/test_bbrain.py
Tests for cognia/bbrain.py — autonomous bbrain.md generator.

No network access: OLLAMA_URL points at an unroutable local port and the
GGUF/shard env vars point at controlled empty tmp dirs.
"""

from __future__ import annotations

from pathlib import Path

import pytest


@pytest.fixture()
def offline_env(tmp_path, monkeypatch):
    """Isolate the backend probes: no GGUF, no shards, no reachable Ollama."""
    shard_dir = tmp_path / "shards" / "model"
    shard_dir.mkdir(parents=True)
    monkeypatch.delenv("LLAMA_GGUF_PATH", raising=False)
    monkeypatch.setenv("SHARD_WEIGHTS_DIR", str(shard_dir))
    # Connection refused on localhost is instant — no real network involved.
    monkeypatch.setenv("OLLAMA_URL", "http://127.0.0.1:1")
    return tmp_path


# ---------------------------------------------------------------------------
# generate_bbrain()
# ---------------------------------------------------------------------------

class TestGenerateBbrain:
    def test_returns_string_with_key_sections(self, offline_env):
        """generate_bbrain returns a markdown string containing every section."""
        from cognia.bbrain import generate_bbrain
        md = generate_bbrain(offline_env)
        assert isinstance(md, str)
        for section in ("## Entorno", "## Backend LLM", "## Mapa del repo",
                        "## Reglas del proyecto"):
            assert section in md

    def test_includes_autogenerated_notice(self, offline_env):
        """The header must warn that the file is autogenerated."""
        from cognia.bbrain import generate_bbrain
        md = generate_bbrain(offline_env)
        assert "AUTOGENERADO por cognia/bbrain.py" in md
        assert "cognia bbrain" in md

    def test_includes_hard_rules(self, offline_env):
        """The embedded project rules make bbrain.md self-sufficient."""
        from cognia.bbrain import generate_bbrain
        md = generate_bbrain(offline_env)
        assert "venv312" in md
        assert "storage/db_pool.py" in md
        assert "shattering/model_constants.py" in md

    def test_backend_probe_survives_without_gguf_or_ollama(self, offline_env):
        """Backend introspection must not raise when nothing is available."""
        from cognia.bbrain import _backend_lines
        lines = _backend_lines()
        joined = "\n".join(lines)
        assert "no encontrado" in joined          # GGUF absent
        assert "Ollama: no disponible" in joined  # ping refused

    def test_repo_map_counts_controlled_tree(self, offline_env):
        """Repo map reflects the actual tree passed as repo_root."""
        (offline_env / "topmod.py").touch()
        tests_dir = offline_env / "tests"
        tests_dir.mkdir()
        (tests_dir / "test_x.py").touch()

        from cognia.bbrain import generate_bbrain
        md = generate_bbrain(offline_env)
        assert "Modulos .py top-level: 1" in md
        assert "Archivos de test (tests/test_*.py): 1" in md


# ---------------------------------------------------------------------------
# write_bbrain()
# ---------------------------------------------------------------------------

class TestWriteBbrain:
    def test_creates_file_in_tmp_path(self, offline_env):
        """write_bbrain creates bbrain.md at the given root and returns its path."""
        from cognia.bbrain import write_bbrain
        path = write_bbrain(offline_env)
        assert path == offline_env / "bbrain.md"
        assert path.is_file()

    def test_written_content_is_utf8_and_autogenerated(self, offline_env):
        """The written file is valid UTF-8 and carries the autogenerated notice."""
        from cognia.bbrain import write_bbrain
        path = write_bbrain(offline_env)
        content = path.read_text(encoding="utf-8")
        assert "AUTOGENERADO por cognia/bbrain.py" in content
        assert "## Entorno" in content

    def test_overwrites_existing_file(self, offline_env):
        """A stale bbrain.md is fully replaced on regeneration."""
        stale = offline_env / "bbrain.md"
        stale.write_text("contenido viejo", encoding="utf-8")
        from cognia.bbrain import write_bbrain
        path = write_bbrain(offline_env)
        content = path.read_text(encoding="utf-8")
        assert "contenido viejo" not in content
        assert "AUTOGENERADO" in content


class TestCoverageRadar:
    """Radar anti-danos-colaterales: modulos publicos sin mencion en tests/."""

    def test_detecta_modulo_huerfano(self, tmp_path):
        (tmp_path / "a.py").write_text("def alpha_fn():\n    pass\n", encoding="utf-8")
        (tmp_path / "b.py").write_text(
            "def beta_orphan():\n    pass\nclass GammaOrphan:\n    pass\n",
            encoding="utf-8")
        (tmp_path / "tests").mkdir()
        (tmp_path / "tests" / "test_a.py").write_text(
            "from a import alpha_fn\n", encoding="utf-8")
        from cognia.bbrain import _coverage_map_lines
        txt = "\n".join(_coverage_map_lines(tmp_path))
        assert "b.py (2 simbolos publicos)" in txt      # huerfano detectado
        assert "* a.py" not in txt                       # el testeado no aparece

    def test_repo_sin_tests_no_explota(self, tmp_path):
        (tmp_path / "solo.py").write_text("def x_pub():\n    pass\n", encoding="utf-8")
        from cognia.bbrain import _coverage_map_lines
        txt = "\n".join(_coverage_map_lines(tmp_path))
        assert "SIN ninguna mencion" in txt

    def test_seccion_presente_en_bbrain(self, offline_env):
        from cognia.bbrain import generate_bbrain
        content = generate_bbrain(offline_env)
        assert "## Radar de cobertura" in content
