# Generated by Cognia | 2026-08-01T15:49:50.126049
# Category: juego extremadamente adictivo llamado
# Score: auto-asignado 8.4/10 (SIN VERIFICAR)
# Origin: predefined category

import random
import time

# Constants
GRID_SIZE = 10
PLAYER_START = (0, 0)
OBSTACLE_COUNT = 5
POINT_COUNT = 5
GAME_DURATION = 10  # seconds

# Sample data
obstacles = set()
points = set()

# Initialize game state
player_position = PLAYER_START
score = 0
game_over = False

# Generate random obstacles and points
while len(obstacles) < OBSTACLE_COUNT:
    obstacle = (random.randint(0, GRID_SIZE - 1), random.randint(0, GRID_SIZE - 1))
    if obstacle != PLAYER_START:
        obstacles.add(obstacle)

while len(points) < POINT_COUNT:
    point = (random.randint(0, GRID_SIZE - 1), random.randint(0, GRID_SIZE - 1))
    if point not in obstacles and point != PLAYER_START:
        points.add(point)

# Function to print the game grid
def print_grid():
    print('\033[2J\033[H', end='')  # Clear terminal
    for y in range(GRID_SIZE):
        for x in range(GRID_SIZE):
            if (x, y) == player_position:
                print('P', end=' ')
            elif (x, y) in obstacles:
                print('X', end=' ')
            elif (x, y) in points:
                print('.', end=' ')
            else:
                print(' ', end=' ')
        print()
    print(f'Score: {score}')

# Function to move the player
def move_player(dx, dy):
    global player_position, score, game_over
    new_position = (player_position[0] + dx, player_position[1] + dy)
    if 0 <= new_position[0] < GRID_SIZE and 0 <= new_position[1] < GRID_SIZE:
        if new_position in obstacles:
            print("Game Over! You hit an obstacle.")
            game_over = True
        elif new_position in points:
            score += 1
            points.remove(new_position)
            print("Point collected!")
        player_position = new_position

# Main game loop
start_time = time.time()
while not game_over and (time.time() - start_time) < GAME_DURATION:
    print_grid()
    time.sleep(1)
    # Randomly move the player
    dx, dy = random.choice([(-1, 0), (1, 0), (0, -1), (0, 1)])
    move_player(dx, dy)

# Final score
print_grid()
print(f"Final Score: {score}")