# Generated by Cognia | 2026-08-17T22:30:46.160851
# Category: Automated pet feeder that schedules meals based on animal behavior patterns
# Score: auto-asignado 5.1/10 (SIN VERIFICAR)
# Origin: self-proposed idea

# Title: Automated Pet Feeder with Behavior-Based Scheduling
# Description: This program simulates an automated pet feeder that schedules meals based on the pet's behavior patterns using sample data and tunable constants.

import random
import time
from collections import deque
import threading

# Constants
MEAL_INTERVAL_MIN = 60  # Minimum interval between meals in minutes
MEAL_INTERVAL_MAX = 120  # Maximum interval between meals in minutes
FEEDER_CAPACITY = 2000  # Feeder capacity in grams
PET_WEIGHT = 5  # Pet weight in kg
PORTION_SIZE = 50  # Portion size in grams per meal
SAMPLING_INTERVAL = 5  # Time interval for monitoring behavior in minutes
BEHAVIOR_CHANGE_THRESHOLD = 0.2  # Threshold for detecting significant behavior change

# Sample behavior data (0.0 to 1.0, where 1.0 is most active)
behavior_data = [random.uniform(0.0, 1.0) for _ in range(100)]

# Queue to store recent behavior data
behavior_queue = deque(maxlen=10)

def schedule_meals(behavior_data):
    """Schedule meals based on behavior patterns."""
    meals = []
    last_meal_time = 0
    for i, behavior in enumerate(behavior_data):
        if i == 0:
            # Schedule the first meal
            meals.append(i)
            last_meal_time = i
        else:
            # Calculate time since last meal
            time_since_last_meal = i - last_meal_time
            # Determine meal interval based on behavior
            meal_interval = MEAL_INTERVAL_MIN + (behavior - 0.5) * (MEAL_INTERVAL_MAX - MEAL_INTERVAL_MIN)
            if time_since_last_meal > meal_interval:
                # Schedule a new meal
                meals.append(i)
                last_meal_time = i
    return meals

def monitor_behavior():
    """Monitor pet behavior over time."""
    global FEEDER_CAPACITY
    while True:
        # Simulate behavior data
        behavior = random.uniform(0.0, 1.0)
        behavior_queue.append(behavior)
        # Check for significant behavior change
        if len(behavior_queue) == behavior_queue.maxlen:
            avg_behavior = sum(behavior_queue) / len(behavior_queue)
            if any(abs(b - avg_behavior) > BEHAVIOR_CHANGE_THRESHOLD for b in behavior_queue):
                print("Significant behavior change detected!")
        # Wait for the next sampling interval
        time.sleep(SAMPLING_INTERVAL * 60)

def feed_pet():
    """Feed the pet based on scheduled meals."""
    global FEEDER_CAPACITY
    scheduled_meals = schedule_meals(behavior_data)
    print(f"Scheduled meals: {scheduled_meals}")
    for meal_time in scheduled_meals:
        # Calculate portion size based on pet weight
        portion = PET_WEIGHT * PORTION_SIZE
        # Check if the feeder has enough food
        if FEEDER_CAPACITY >= portion:
            print(f"Feeding at time {meal_time}: {portion} grams")
            FEEDER_CAPACITY -= portion
        else:
            print(f"Feeder is empty! Refill required.")
            break
        # Wait for the next meal time
        if meal_time < len(behavior_data) - 1:
            time.sleep((behavior_data[meal_time + 1] - behavior_data[meal_time]) * 60)

def main():
    """Main function to run the automated pet feeder."""
    print("Starting Automated Pet Feeder...")
    # Monitor behavior in a separate thread
    behavior_thread = threading.Thread(target=monitor_behavior)
    behavior_thread.start()
    # Feed the pet based on scheduled meals
    feed_pet()
    # Wait for the behavior thread to finish
    behavior_thread.join()
    print("Pet feeding completed.")

if __name__ == "__main__":
    main()