# Generated by Cognia | 2026-08-12T23:38:07.829189
# Category: number theory explorer that prints interesting patterns
# Score: auto-asignado 7.5/10 (SIN VERIFICAR)
# Origin: predefined category

# Number Theory Explorer
MAX_N = 60
sep = "  "

# smallest prime factor
spf = [0]*(MAX_N+1)
def sieve_spf():
    for i in range(2, MAX_N+1):
        if spf[i] == 0:
            for j in range(i, MAX_N+1, i):
                if spf[j] == 0:
                    spf[j] = i
                # else keep existing smaller factor

sieve_spf()

# divisor count
div_cnt = [1]*(MAX_N+1)
for i in range(2, MAX_N+1):
    for j in range(i, MAX_N+1, i):
        div_cnt[j] += 1

# proper divisor sum
proper_sum = [0]*(MAX_N + 108)
for i in range(2, MAX_N+1):
    for j in range(2*i, MAX_N+1, i):
        proper_sum[j] += i

# amicable detection
def amicable(n):
    s = proper_sum[n]
    return s != n and proper_sum[s] == n

# classification
def classify(n):
    if n == 1: return "unit"
    if spf[n] == n: return "prime"
    if proper_sum[n] == n: return "perfect"
    if amicable(n): return "amicable"
    return "composite"

# pattern flags
def pattern(n):
    p = ""
    if spf[n] > spf[n-1]: p += "jump"
    if div_cnt[n] >= div_cnt[n-1]: p += "hc"
    if amicable(n): p += "ami"
    return p

def row(n):
    return f"{n}{sep}{classify(n):15}{sep}{spf[n]:2}{sep}{div_cnt[n]:2}{sep}{proper_sum[n]:2}{sep}{pattern(n)}"

# print header
print("# Number Theory Explorer")
print("# Bounds: 1 .. MAX_N")
print("# Pattern: smallest prime factor, divisor count, proper divisor sum")
print()
print("---")

# print pattern lines
print("# Pattern: smallest prime factor steps")
for n in range(2, MAX_N+1):
    if spf[n] > spf[n-1]:
        print(f"{n:2}  (spf jumps to {spf[n]})")
print()

print("# Pattern: highly composite numbers")
for n in range(2, MAX_N+1):
    if div_cnt[n] >= div_cnt[n-1]:
        print(f"{n:2}  (divisors: {div_cnt[n]})")
print()

# main table
for n in range(1, MAX_N+1):
    print(row(n))

# verification
primes = sum(1 for n in range(1, MAX_N+1) if spf[n] == n)
print()
print("# Verification: prime count matches spf[n]==n for n>1")
print("PASS" if primes == sum(1 for n in range(1, MAX_N+1) if spf[n] == n and n > 1) else "FAIL")