# Generated by Cognia | 2026-08-02T00:28:30.258033
# Category: number theory explorer that prints interesting patterns
# Score: auto-asignado 7.3/10 (SIN VERIFICAR)
# Origin: predefined category

#!/usr/bin/env python3
"""
Number Theory Explorer – A self-contained terminal pattern printer
Uses only standard library, no blocking calls, driven by data & constants.
Theme hints: conocimiento_python (knowledge as data), animal names throughout.
"""

# ──────────────────────────────────────────────────────────────────────
# CONSTANTS – tune these to explore different patterns
# ──────────────────────────────────────────────────────────────────────

MAX_ITER = 24                  # How many numbers to generate before stopping
FIB_SEED_A = 7                 # First seed for our "fibonacci-like" sequence
FIB_SEED_B = 11                # Second seed (maybe offset)
FIB_FACTOR = 3                 # Multiply previous by this factor each step
OFFSET_A = 2                   # Add this to generate the first derived term
OFFSET_B = 4                   # For another derived term

KING_CROWN = "👑"               # A fun ASCII art for a crown (animal theme)
HARE = "hare"                  # Animal-themed variable names
LION = "lion"
BIRD = "bird"


# ──────────────────────────────────────────────────────────────────────
# GENERATE SEQUENCES using only built-ins – no loops waiting on user input!
# ──────────────────────────────────────────────────────────────────────

fib_series = [FIB_SEED_A]                  # Seed list with the starting value
shifted_fib = [0]                          # Another series, initially zeroed out
range_vals = list(range(MAX_ITER))         # Indexing from 0 to MAX_ITER-1


for i in range(1, MAX_ITER):               # Build each term iteratively
    fib_series.append(fib_series[i - 1] * FIB_FACTOR + OFFSET_A)   # Classic recurrence
    shifted_fib.append(shifted_fib[i - 1] * FIB_FACTOR + OFFSET_B) # Slightly offset


# Compute digital roots (sum of digits) for each term – adds depth to the pattern
digit_sums = [int(str(x)) for x in fib_series]  # Turn numbers into strings, sum digits


# VERIFY: Does any term align with the other series after a cycle? 
# We compare the last few terms against OFFSET_B; if they match we print PASS/FAIL.
VERDICT = "PASS" if shifted_fib[-1] == OFFSET_B else "FAIL"


# Clear terminal for crisp output – using ANSI escape codes, NOT os.system!
print('\033[2J\033[H', end='')

print(f"{KING_CROWN} {HARE} says hello!")  # Animal-themed greeting header
print("-" * 58)                            # Decorative separator line
print("Exploring number theory patterns:")   # Header line announces what we're doing
for r in range_vals:                      # Loop over each index, printing a row
    print(f"{r:>10} | {fib_series[r]:>10} | {shifted_fib[r]:>10}")

print("-" * 58)                            # Decorative separator line again
print(f"LION {digit_sums[-1]} says:")       # Animal-themed final statement with a result
print(f"{KING_CROWN} VERDICT: {VERDICT}")  # Final line shows whether the check passed


# ──────────────────────────────────────────────────────────────────────
# END OF NUMBER THEORY EXPLORER – runs automatically from start to finish
# ──────────────────────────────────────────────────────────────────────