"""
cognia/reports/progress_reporter.py
=====================================
Deterministic Markdown progress report generator.
Combines goals, conversation stats, curiosity insights, and session summaries.
No LLM calls — all data is pulled directly from SQLite via db_pool.
"""

from __future__ import annotations

import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

_ROOT = Path(__file__).parent.parent.parent
_CHAT_DB = str(_ROOT / "cognia_desktop_chat.db")


class ProgressReporter:
    """
    Generates weekly progress reports in Markdown.
    Combines: goals, conversation stats, curiosity insights, session summaries.
    """

    def __init__(self, db_path: str = _CHAT_DB):
        self._db = db_path

    def generate_report(self, user_id: str = "local", period_days: int = 7) -> str:
        """
        Return Markdown string of the progress report for the last `period_days`.
        Sections: header, goals, conversation stats, curiosity insights, summaries, footer.
        """
        if period_days < 0:
            period_days = 0

        now = datetime.utcnow()
        since = now - timedelta(days=period_days)

        lines: list[str] = []

        # 1. Header
        lines.append(f"# Cognia Progress Report")
        lines.append(f"")
        lines.append(f"**User:** {user_id}  ")
        lines.append(f"**Period:** last {period_days} day{'s' if period_days != 1 else ''}  ")
        lines.append(f"**Generated:** {now.strftime('%Y-%m-%d %H:%M UTC')}  ")
        lines.append(f"")
        lines.append("---")
        lines.append("")

        # 2. Goals
        goals_section = self._get_goals_section(user_id, since)
        if goals_section:
            lines.append(goals_section)

        # 3. Conversation stats
        conv_section = self._get_conversation_stats(since)
        if conv_section:
            lines.append(conv_section)

        # 4. Curiosity insights
        curiosity_section = self._get_curiosity_section(since)
        if curiosity_section:
            lines.append(curiosity_section)

        # 5. Session summaries
        summaries_section = self._get_summaries_section(user_id)
        if summaries_section:
            lines.append(summaries_section)

        # 6. Footer
        lines.append("---")
        lines.append("")
        lines.append(f"*Report generated by Cognia at {now.strftime('%Y-%m-%d %H:%M:%S UTC')}*")

        return "\n".join(lines)

    def _get_goals_section(self, user_id: str, since: datetime) -> str:
        """Build Markdown section for goals — active and completed this period."""
        try:
            from cognia.goals.goal_tracker import GoalTracker
            tracker = GoalTracker(db_path=self._db)
            active_goals = tracker.get_goals(user_id, status="active")
            completed_goals = tracker.get_goals(user_id, status="completed")
        except Exception:
            return ""

        since_ts = int(since.timestamp())
        completed_this_period = [
            g for g in completed_goals
            if g.get("completed_at") and g["completed_at"] >= since_ts
        ]

        lines: list[str] = []
        lines.append("## Goals")
        lines.append("")

        if active_goals:
            lines.append(f"**Active ({len(active_goals)})**")
            lines.append("")
            for g in active_goals:
                bar = _progress_bar(g["progress_pct"])
                lines.append(f"- {g['title']} — {g['progress_pct']}% {bar}")
            lines.append("")
        else:
            lines.append("*No active goals.*")
            lines.append("")

        if completed_this_period:
            lines.append(f"**Completed this period ({len(completed_this_period)})**")
            lines.append("")
            for g in completed_this_period:
                lines.append(f"- ~~{g['title']}~~ (100%)")
            lines.append("")

        return "\n".join(lines)

    def _get_conversation_stats(self, since: datetime) -> str:
        """Build Markdown section for conversation statistics from chat_history."""
        since_ts = int(since.timestamp())
        try:
            from storage.db_pool import get_pool
            with get_pool(self._db).get() as conn:
                row = conn.execute(
                    "SELECT COUNT(*), COUNT(DISTINCT session_id) "
                    "FROM chat_history WHERE ts >= ?",
                    (since_ts,),
                ).fetchone()
        except Exception:
            return ""

        if row is None:
            return ""

        total_msgs, total_sessions = row[0] or 0, row[1] or 0

        lines: list[str] = []
        lines.append("## Conversation Statistics")
        lines.append("")
        lines.append(f"| Metric | Value |")
        lines.append(f"|---|---|")
        lines.append(f"| Messages | {total_msgs} |")
        lines.append(f"| Sessions | {total_sessions} |")
        lines.append("")

        return "\n".join(lines)

    def _get_curiosity_section(self, since: datetime) -> str:
        """Build Markdown section for recent curiosity insights."""
        try:
            from cognia.reasoning.curiosity_engine import CuriosityEngine
            engine = CuriosityEngine()
            insights = engine.get_insights(limit=5)
        except Exception:
            return ""

        if not insights:
            return ""

        since_ts = int(since.timestamp())
        # Filter to the period if answered_at is available
        period_insights = [
            i for i in insights
            if i.get("answered_at") is None or i["answered_at"] >= since_ts
        ]
        if not period_insights:
            period_insights = insights  # fallback: show all recent if none in window

        lines: list[str] = []
        lines.append("## Curiosity Insights")
        lines.append("")
        lines.append("Recent questions explored:")
        lines.append("")
        for insight in period_insights:
            question = insight.get("question", "").strip()
            answer = insight.get("answer", "").strip()
            if not question:
                continue
            # Truncate answer to a brief excerpt
            excerpt = (answer[:120] + "...") if len(answer) > 120 else answer
            lines.append(f"- **{question}**")
            if excerpt:
                lines.append(f"  {excerpt}")
        lines.append("")

        return "\n".join(lines)

    def _get_summaries_section(self, user_id: str = "local") -> str:
        """Build Markdown section for recent session summaries."""
        try:
            from storage.db_pool import get_pool
            with get_pool(self._db).get() as conn:
                rows = conn.execute(
                    "SELECT summary FROM session_summaries ORDER BY created_at DESC LIMIT 3"
                ).fetchall()
        except Exception:
            # Table may not exist — silently skip
            return ""

        if not rows:
            return ""

        lines: list[str] = []
        lines.append("## Recent Session Summaries")
        lines.append("")
        for i, row in enumerate(rows, 1):
            summary = (row[0] or "").strip()
            if summary:
                lines.append(f"**Session {i}**")
                lines.append("")
                lines.append(f"> {summary}")
                lines.append("")

        return "\n".join(lines)

    def generate_json_stats(self, user_id: str = "local", period_days: int = 7) -> dict:
        """
        Return a JSON-serialisable dict of key metrics for dashboard use.
        Keys: period_days, goals_active, goals_completed, messages_total,
              sessions_total, insights_count.
        """
        if period_days < 0:
            period_days = 0

        now = datetime.utcnow()
        since = now - timedelta(days=period_days)
        since_ts = int(since.timestamp())

        # Goals
        goals_active = 0
        goals_completed = 0
        try:
            from cognia.goals.goal_tracker import GoalTracker
            tracker = GoalTracker(db_path=self._db)
            goals_active = len(tracker.get_goals(user_id, status="active"))
            completed = tracker.get_goals(user_id, status="completed")
            goals_completed = sum(
                1 for g in completed
                if g.get("completed_at") and g["completed_at"] >= since_ts
            )
        except Exception:
            pass

        # Conversation stats
        messages_total = 0
        sessions_total = 0
        try:
            from storage.db_pool import get_pool
            with get_pool(self._db).get() as conn:
                row = conn.execute(
                    "SELECT COUNT(*), COUNT(DISTINCT session_id) "
                    "FROM chat_history WHERE ts >= ?",
                    (since_ts,),
                ).fetchone()
            if row:
                messages_total = row[0] or 0
                sessions_total = row[1] or 0
        except Exception:
            pass

        # Curiosity insights count
        insights_count = 0
        try:
            from cognia.reasoning.curiosity_engine import CuriosityEngine
            engine = CuriosityEngine()
            insights = engine.get_insights(limit=100)
            insights_count = sum(
                1 for i in insights
                if i.get("answered_at") is None or i["answered_at"] >= since_ts
            )
        except Exception:
            pass

        return {
            "period_days": period_days,
            "goals_active": goals_active,
            "goals_completed": goals_completed,
            "messages_total": messages_total,
            "sessions_total": sessions_total,
            "insights_count": insights_count,
        }


def _progress_bar(pct: int, width: int = 10) -> str:
    """Return a simple ASCII progress bar like [====      ] 40%."""
    pct = max(0, min(100, pct))
    filled = round(pct / 100 * width)
    return f"[{'=' * filled}{' ' * (width - filled)}]"
