# Generated by Cognia | 2026-08-29T21:35:38.004705
# Category: number theory explorer that prints interesting patterns
# Score: auto-asignado 9.4/10 (SIN VERIFICAR)
# Origin: predefined category

#!/usr/bin/env python3
"""NUMBER THEORY EXPLORER - a tour of beautiful patterns in the integers.
Each exhibit prints a visible pattern and verifies a theorem with a real
computed comparison (PASS/FAIL verdicts, no bare claims).  Data-driven:
edit the tunables at the top to reshape the tour.  Animal guide: every
pattern is named after a creature.
"""
import math
import random

# ------------------------- TUNABLE CONSTANTS -------------------------
COLLATZ_LIMIT  = 4_000        # Collatz: test n = 1..4000
COLLATZ_BUCKET = 20           # histogram bucket width (steps)
PASCAL_ROWS    = 23           # rows of Pascal's triangle mod 2
MOD_P          = 13           # prime modulus for the kaleidoscope table
MOD_GLYPHS     = " .':;+*#%&@~?"  # 13 glyphs, index = residue 0..12
FIB_ROW_LEN    = 10           # digits per line of the rabbit wheel
ODD_SUM_N      = 6            # rows of the odd-sum identity
EUCLID_M       = 6            # Euclid parameter m ranges over 3..EUCLID_M
FERMAT_PRIMES  = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37)
PRIME_GRID_N   = 100          # prime map 1..100
PRIME_GRID_W   = 10           # columns in the prime map
RANDOM_SEED    = 42           # fixed seed -> reproducible "random" number
RANDOM_MAX     = 10_000

CHECKS = []  # (tag, ok) - the knowledge ledger

# ----------------------------- helpers ------------------------------

def banner(title, animal):
    print()
    print("=" * 72)
    print(f"  {title}")
    print(f"  animal guide: {animal}")
    print("=" * 72)


def knowledge(statement):
    print(f"  conocimiento: {statement}")


def verify(tag, label, ok, detail=""):
    ok = bool(ok)
    CHECKS.append((tag, ok))
    mark = "PASS" if ok else "FAIL"
    line = f"  [{mark}] {label}"
    if not ok and detail:
        line += f"   -> {detail}"
    print(line)
    return ok

# ----------------------------- exhibits -----------------------------

def exhibit_pascal():
    banner("EXHIBIT 1 - Pascal's triangle mod 2 -> the Sierpinski fractal",
           "the squirrel counting branches of its fractal tree")
    rows, row = [], [1]
    for _ in range(PASCAL_ROWS):
        rows.append(row)
        row = [(row[i - 1] + row[i]) % 2 for i in range(len(row))]
    width = len(rows[-1])
    for k, r in enumerate(rows):
        print(f"  {k:2d} │{''.join('#' if v else ' ' for v in r).center(width)}│")
    print("  (row index on the left; # = odd binomial coefficient)")
    odd = [sum(r) for r in rows]
    exp = [2 ** bin(k).count("1") for k in range(PASCAL_ROWS)]
    verify("Pascal", f"odd entries in row k = 2^popcount(k), {PASCAL_ROWS} rows",
           odd == exp, f"got {odd} vs {exp}")
    knowledge("binomial coefficients mod 2 hide a self-similar fractal")


def exhibit_mod_table():
    banner(f"EXHIBIT 2 - multiplication table mod {MOD_P} -> kaleidoscope",
           "the peacock, whose feathers repeat in perfect order")
    table = [[(i * j) % MOD_P for j in range(MOD_P)] for i in range(MOD_P)]
    print("      " + "".join("%2d" % j for j in range(MOD_P)))
    print("      " + "-" * (2 * MOD_P))
    for i in range(MOD_P):
        print(f"  {i:2d}  " + "".join("%2s" % MOD_GLYPHS[v] for v in table[i]))
    print("      " + "-" * (2 * MOD_P))
    print(f"  legend (residue -> glyph): [{MOD_GLYPHS}]  (leftmost char = 0)")
    perm = list(range(1, MOD_P))
    latin = (all(sorted(table[r][1:]) == perm for r in range(1, MOD_P))
             and all(sorted(table[r][c] for r in range(1, MOD_P)) == perm
                     for c in range(1, MOD_P)))
    verify("Peacock", "Latin square: every non-zero row/col permutes 1..p-1", latin)
    sym = all(table[r][c] == table[c][r] for r in range(MOD_P)
              for c in range(MOD_P))
    verify("Peacock", "table is symmetric - multiplication commutes mod p", sym)
    knowledge("mod p, the non-zero residues form a cyclic group; rows rotate")


def collatz_trace(n, cap=1_000_000):
    v, steps, peak = n, 0, n
    while v != 1:
        if steps >= cap:
            return None, peak            # runaway guard
        v = v // 2 if v % 2 == 0 else 3 * v + 1
        steps += 1
        peak = max(peak, v)
    return steps, peak


def exhibit_collatz():
    banner("EXHIBIT 3 - Collatz 'caterpillar' - stopping-time landscape",
           "the caterpillar (Collatz is literally the caterpillar problem)")
    data, ok_all = {}, True
    for n in range(1, COLLATZ_LIMIT + 1):
        s, p = collatz_trace(n)
        if s is None:
            ok_all = False
        else:
            data[n] = (s, p)
    verify("Collatz", f"every n <= {COLLATZ_LIMIT} reached 1 (traces terminated)",
           ok_all and len(data) == COLLATZ_LIMIT)
    evens = [n for n in data if n % 2 == 0]
    verify("Collatz", f"T(2n) = T(n) + 1 for all {len(evens)} even n",
           all(data[n][0] == data[n // 2][0] + 1 for n in evens))
    powers = [2 ** k for k in range(1, COLLATZ_LIMIT.bit_length())
             if 2 ** k <= COLLATZ_LIMIT]
    verify("Collatz", f"powers of 2 take exactly k steps ({len(powers)} checked)",
           all(data[p][0] == p.bit_length() - 1 for p in powers))
    top5 = sorted(data.items(), key=lambda kv: kv[1][0], reverse=True)[:5]
    print("  top 5 longest flights:")
    for n, (s, p) in top5:
        print(f"    n={n:<6} steps={s:<4} peak={p}")
    hist = {}
    for s, _ in data.values():
        hist[s // COLLATZ_BUCKET] = hist.get(s // COLLATZ_BUCKET, 0) + 1
    best = max(hist.values())
    print(f"  stopping-time histogram (bucket = {COLLATZ_BUCKET} steps):")
    for b in sorted(hist):
        bar = "#" * int(hist[b] / best * 50)
        lo = b * COLLATZ_BUCKET
        print(f"    {lo:3d}-{lo + COLLATZ_BUCKET - 1:3d} | {bar}")
    climbers = sum(1 for _, (_, p) in data.items() if p > COLLATZ_LIMIT)
    print(f"  {climbers} caterpillars climbed above n = {COLLATZ_LIMIT} before landing")
    knowledge(f"every caterpillar lands on 1 - verified for n = 1..{COLLATZ_LIMIT}")


def exhibit_fib():
    banner("EXHIBIT 4 - Fibonacci last digits - the wheel of the rabbit",
           "the rabbit (Fibonacci counted his rabbits' babies)")
    a, b = 0, 1
    seq = []
    while True:
        a, b = b, a + b                  # step k: (a, b) = (F_k, F_{k+1})
        seq.append(a % 10)              # collect F_k mod 10
        if a % 10 == 0 and b % 10 == 1:  # the pair (0,1) returns
            break
    period = len(seq)
    print(f"  pair (0,1) returns after {period} steps -> last-digit period = {period}")
    print("  " + " ".join("%2d" % j for j in range(FIB_ROW_LEN)))
    for r in range(0, min(period, FIB_ROW_LEN * 6), FIB_ROW_LEN):
        print("  " + " ".join("%2d" % v for v in seq[r:r + FIB_ROW_LEN]))

    def fib_period(mod):
        aa, bb, k = 0, 1, 0
        while (aa % mod, bb % mod) != (0, 1) or k == 0:
            aa, bb = bb, (aa + bb) % mod
            k += 1
        return k

    p2, p5 = fib_period(2), fib_period(5)
    lcm = p2 * p5 // math.gcd(p2, p5)
    verify("Rabbit", f"period mod 10 = lcm(period mod 2, mod 5) = lcm({p2}, {p5})",
           period == lcm, f"measured {period}")
    extra = []
    for _ in range(25):
        a, b = b, a + b
        extra.append(a % 10)
    verify("Rabbit", "second wheel matches the first (25 sampled digits)",
           extra == seq[:25], "digits drifted")
    verify("Rabbit", f"F({period}) ends in 0 - the wheel closes",
           seq[-1] == 0, f"F({period}) mod 10 = {seq[-1]}")
    knowledge("every rabbit's last digit repeats after a full wheel")


def exhibit_odds():
    banner("EXHIBIT 5 - sum of the first n odds = n^2 - growing squares",
           "the turtle, stacking the plates of its shell")
    total, ok = 0, True
    for n in range(1, ODD_SUM_N + 1):
        total += 2 * n - 1
        ok = ok and total == n * n
        ladder = " + ".join(str(2 * k - 1) for k in range(1, n + 1))
        print(f"  {ladder:<30} = {total:<3} = {n}^2")
    verify("Turtle", f"1+3+5+...+(2n-1) = n^2 for n = 1..{ODD_SUM_N}", ok)
    verify("Turtle", f"next odd 2n+1 = (n+1)^2 - n^2, n = 1..{ODD_SUM_N}",
           all((k + 1) ** 2 - k * k == 2 * k + 1
               for k in range(1, ODD_SUM_N + 1)))
    n = ODD_SUM_N
    print(f"  the {n}-square, built plate by plate:")
    for _ in range(n):
        print("    " + "#" * n)
    knowledge("each new shell plate adds exactly 2n+1 dots - the next odd number")


def exhibit_triples():
    banner("EXHIBIT 6 - Euclid's mill - Pythagorean triples",
           "the owl of Athena, Euclid's emblem")
    rows = []
    for m in range(3, EUCLID_M + 1):
        for nn in range(1, m):
            if math.gcd(m, nn) != 1 or (m - nn) % 2 == 0:
                continue
            a, b, c = m * m - nn * nn, 2 * m * nn, m * m + nn * nn
            rows.append((m, nn, a, b, c,
                         a * a + b * b == c * c,
                         math.gcd(math.gcd(a, b), c) == 1,
                         a % 2 == 1 and b % 2 == 0 and c % 2 == 1))
    print("  m  n │     a      b      c │  a^2+b^2=c^2  primitive  parity")
    print("   " + "-" * 58)
    for m, nn, a, b, c, chk, prim, par in rows:
        print(f"  {m}  {nn} │ {a:5d} {b:5d} {c:5d} │     "
              f"{'Y' if chk else 'N'}      {'Y' if prim else 'N'}     "
              f"{'Y' if par else 'N'}")
    cnt = len(rows)
    verify("Owl", f"a^2+b^2=c^2 holds for all {cnt} generated triples",
           all(r[5] for r in rows), "identity failed")
    verify("Owl", f"all {cnt} triples are primitive (gcd(a,b,c) = 1)",
           all(r[6] for r in rows), "gcd > 1 found")
    verify("Owl", "parity: a odd, b even, c odd in every row",
           all(r[7] for r in rows), "parity broken")
    knowledge("m>n, coprime, opposite parity -> a primitive triple (Euclid)")


def is_prime(x):
    if x < 2:
        return False
    d = 2
    while d * d <= x:
        if x % d == 0:
            return False
        d += 1
    return True


def exhibit_fermat():
    banner("EXHIBIT 7 - Fermat's little theorem - and its liar",
           "the fox, sly enough to wear a prime's coat")
    ok_all = True
    for p in FERMAT_PRIMES:
        bases = [b for b in (2, 3, 5) if b < p] or [1]
        cells = []
        for b in bases:
            good = pow(b, p - 1, p) == 1
            ok_all = ok_all and good
            cells.append(f"b={b} -> " + ("1" if good else "FAIL"))
        print(f"  p={p:3d} │ " + "   ".join(cells))
    verify("Fox", "b^(p-1) = 1 (mod p) for every prime/base pair above", ok_all)
    liar = pow(2, 560, 561)
    verify("Fox", "561 = 3*11*19 is composite yet 2^560 = 1 (mod 561)",
           liar == 1, f"2^560 mod 561 = {liar}")
    print()
    print(f"  prime map 1..{PRIME_GRID_N} (primes as digits, composites as dots):")
    for k in range(0, PRIME_GRID_N, PRIME_GRID_W):
        cells = "".join(f"{x:3d}" if is_prime(x) else "· ·"
                        for x in range(k + 1, k + PRIME_GRID_W + 1))
        print(f"  {k + 1:3d}-{k + PRIME_GRID_W:3d} │ {cells}")
    primes = [x for x in range(2, PRIME_GRID_N + 1) if is_prime(x)]
    sieve = [True] * (PRIME_GRID_N + 1)
    sieve[0] = sieve[1] = False
    for x in range(2, int(PRIME_GRID_N ** 0.5) + 1):
        if sieve[x]:
            for y in range(x * x, PRIME_GRID_N + 1, x):
                sieve[y] = False
    n_sieve = sum(sieve)
    verify("Fox", f"trial division and sieve agree: pi({PRIME_GRID_N}) = {len(primes)}",
           n_sieve == len(primes), f"sieve counted {n_sieve}")
    knowledge("Carmichael numbers are primes' false cousins - they fool the test")


def exhibit_random():
    banner("EXHIBIT 8 - anatomy of a seeded-random number",
           "the chameleon, which adapts to any number")
    n = random.Random(RANDOM_SEED).randrange(100, RANDOM_MAX)
    print(f"  today's number: {n}")
    f, d, x = {}, 2, n
    while d * d <= x:
        while x % d == 0:
            f[d] = f.get(d, 0) + 1
            x //= d
        d += 1
    if x > 1:
        f[x] = f.get(x, 0) + 1
    fac = " * ".join(f"{p}^{e}" if e > 1 else str(p)
                     for p, e in sorted(f.items()))
    print(f"  factorization: {n} = {fac}")
    prod = 1
    for p, e in f.items():
        prod *= p ** e
    verify("Chameleon", "factorization multiplies back to n", prod == n)
    tau = phi = 1
    for p, e in f.items():
        tau *= e + 1
        phi *= p ** (e - 1) * (p - 1)
    coprimes = [a for a in range(1, n + 1) if math.gcd(a, n) == 1]
    verify("Chameleon", f"coprime count in 1..n matches phi(n) = {phi}",
           len(coprimes) == phi, f"counted {len(coprimes)}")
    print(f"  divisors: tau(n) = {tau}     totient: phi(n) = {phi}")
    print(f"  first few coprimes to {n}: "
          f"{' '.join(map(str, coprimes[:12]))}")
    knowledge("phi(n) counts the residues that invert cleanly modulo n")


def main():
    print("\033[2J\033[H", end="")
    print("┌" + "─" * 72 + "┐")
    print("│" + " NUMBER THEORY EXPLORER - patterns you can see, checks you can see ".center(72) + "│")
    print("└" + "─" * 72 + "┘")
    exhibit_pascal()
    exhibit_mod_table()
    exhibit_collatz()
    exhibit_fib()
    exhibit_odds()
    exhibit_triples()
    exhibit_fermat()
    exhibit_random()
    print()
    print("=" * 72)
    print("  GRAND TOTAL - the knowledge ledger (conocimiento_python)")
    print("=" * 72)
    ledger = {}
    for tag, ok in CHECKS:
        if tag not in ledger:
            ledger[tag] = [0, 0]
        ledger[tag][1] += 1
        ledger[tag][0] += 1 if ok else 0
    print(f"  {'exhibit':<12} {'pass':>4} {'fail':>4}")
    for tag, (p, t) in ledger.items():
        print(f"  {tag:<12} {p:>4} {t - p:>4}")
    passed = sum(1 for _, ok in CHECKS if ok)
    total = len(CHECKS)
    verdict = "PASS" if passed == total else "FAIL"
    print(f"  total: {passed}/{total} checks   [{verdict}] the tour "
          f"{'holds' if verdict == 'PASS' else 'wobbled'}")
    print("  The integers behaved beautifully.  Conocimiento! (knowledge gained)")


if __name__ == "__main__":
    main()