# Generated by Cognia | 2026-07-20T00:33:48.279081
# Category: compresor de texto que colapsa lineas consecutivas repetidas en una sola con contador y recorta el medio si hay demasiadas lineas, con una clase TestCompresor de unittest con al menos 3 metodos test_ que se ejecuten con unittest.main(exit=False)
# Score: 7.0/10
# Origin: predefined category

import unittest

class TextCompressor:
    def compress_text(self, text, max_lines=10):
        lines = text.splitlines()
        compressed = []
        i = 0
        while i < len(lines):
            count = 1
            while i + 1 < len(lines) and lines[i] == lines[i + 1]:
                i += 1
                count += 1
            compressed.append(f"{lines[i]} x{count}")
            i += 1
        
        if len(compressed) > max_lines:
            half = max_lines // 2
            return "\n".join(compressed[:half] + ["..."] + compressed[-half:])
        return "\n".join(compressed)

class TestCompresor(unittest.TestCase):
    def test_single_line(self):
        tc = TextCompressor()
        result = tc.compress_text("Line1\nLine1\nLine1")
        self.assertEqual(result, "Line1 x3")

    def test_multiple_lines(self):
        tc = TextCompressor()
        result = tc.compress_text("Line1\nLine1\nLine2\nLine2\nLine2\nLine3")
        self.assertEqual(result, "Line1 x2\nLine2 x3\nLine3 x1")

    def test_truncate_middle(self):
        tc = TextCompressor()
        long_text = "\n".join(["Line" + str(i) for i in range(20)])
        result = tc.compress_text(long_text, max_lines=5)
        self.assertIn("...", result)

if __name__ == "__main__":
    print('\033[2J\033[H', end='')  # Clear terminal
    print("Running Text Compressor Test Suite...")
    unittest.main(exit=False)