# Generated by Cognia | 2026-07-20T00:11:46.909752
# Category: gestor de tareas con SQLite en memoria, pila de deshacer y tests unitarios que se ejecutan solos
# Score: 6.7/10
# Origin: predefined category

import unittest
import sqlite3
from contextlib import contextmanager

class TaskManager:
    def __init__(self):
        self.conn = sqlite3.connect(':memory:')
        self.create_table()
        self.undo_stack = []

    def create_table(self):
        self.conn.execute('''
            CREATE TABLE tasks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                description TEXT NOT NULL,
                completed BOOLEAN DEFAULT 0
            )
        ''')

    def add_task(self, description):
        cursor = self.conn.cursor()
        cursor.execute('INSERT INTO tasks (description) VALUES (?)', (description,))
        self.undo_stack.append(('add', description, cursor.lastrowid))
        self.conn.commit()

    def complete_task(self, task_id):
        cursor = self.conn.cursor()
        cursor.execute('UPDATE tasks SET completed = 1 WHERE id = ?', (task_id,))
        self.undo_stack.append(('complete', task_id, 1))
        self.conn.commit()

    def undo(self):
        if not self.undo_stack:
            return
        action, arg1, arg2 = self.undo_stack.pop()
        cursor = self.conn.cursor()
        if action == 'add':
            cursor.execute('DELETE FROM tasks WHERE id = ?', (arg2,))
        elif action == 'complete':
            cursor.execute('UPDATE tasks SET completed = 0 WHERE id = ?', (arg1,))
        self.conn.commit()

    def list_tasks(self):
        cursor = self.conn.cursor()
        cursor.execute('SELECT id, description, completed FROM tasks')
        return cursor.fetchall()

class TestTaskManager(unittest.TestCase):
    def setUp(self):
        self.tm = TaskManager()

    def test_add_task(self):
        self.tm.add_task('Buy milk')
        tasks = self.tm.list_tasks()
        self.assertEqual(len(tasks), 1)
        self.assertEqual(tasks[0][1], 'Buy milk')

    def test_complete_task(self):
        self.tm.add_task('Buy milk')
        self.tm.complete_task(tasks[0][0])
        tasks = self.tm.list_tasks()
        self.assertEqual(tasks[0][2], 1)

    def test_undo_add(self):
        self.tm.add_task('Buy milk')
        self.tm.undo()
        tasks = self.tm.list_tasks()
        self.assertEqual(len(tasks), 0)

    def test_undo_complete(self):
        self.tm.add_task('Buy milk')
        self.tm.complete_task(1)
        self.tm.undo()
        tasks = self.tm.list_tasks()
        self.assertEqual(tasks[0][2], 0)

if __name__ == '__main__':
    # Clear terminal
    print('\033[2J\033[H', end='')

    # Run tests
    unittest.main(argv=[''], exit=False)

    # Demo
    print("Running demo...")
    tm = TaskManager()
    tm.add_task('Read a book')
    tm.add_task('Write a report')
    tm.complete_task(1)
    tasks = tm.list_tasks()
    for task in tasks:
        print(f'ID: {task[0]}, Description: {task[1]}, Completed: {"Yes" if task[2] else "No"}')
    print("Undo last action...")
    tm.undo()
    tasks = tm.list_tasks()
    for task in tasks:
        print(f'ID: {task[0]}, Description: {task[1]}, Completed: {"Yes" if task[2] else "No"}')