# Generated by Cognia | 2026-09-07T08:00:23.968849
# Category: number theory explorer that prints interesting patterns
# Score: auto-asignado 8.6/10 (SIN VERIFICAR)
# Origin: predefined category

"""El Zoo Numérico — a number-theory explorer that prints interesting patterns.
Standard library only, fully automatic (no input), terminal output."""
import random
import time
import cmath
from math import isqrt, pi

# ═══════════════ Tunable constants ═══════════════
LIMIT       = 10_000     # sieve bound for primes
GOLD_LIMIT  = 4_000      # Goldbach: verify every even number up to here
COLL_LIMIT  = 1_000      # Collatz: starting values 2..COLL_LIMIT
SPR_SIZE    = 41         # Ulam spiral side length (odd)
MULT_SIZE   = 18         # digital-root multiplication table size
DIGIT_TRIES = 24         # casting-out-nines random samples
EULER_TRIES = 18         # Euler identity random samples
SEED        = 42         # RNG seed (reproducible output)
W           = 76         # report width
CLEAR       = '\033[2J\033[H'

KNOWN_PI = {100: 25, 1_000: 174, 10_000: 1229, 100_000: 9_592}
TRIVIA = [
    '6, 28, 496, 8128 → first perfect numbers    (🐧 penguins)',
    '220 ↔ 284        → first amicable pair      (🐜 ants)',
    '341              → smallest base-2 pseudoprime (🦊 fox)',
    '1729             → Ramanujan taxicab number   (🐢 turtle)',
]

rng = random.Random(SEED)
CHECKS = []  # global PASS/FAIL log


# ───────────── small report helpers ─────────────
def banner(title):
    print()
    print('═' * W)
    print('  ' + title)
    print('═' * W)


def verdict(name, ok, extra='', record=True):
    """Print a [PASS]/[FAIL] line for a verified claim."""
    if record:
        CHECKS.append(bool(ok))
    tag = 'PASS' if ok else 'FAIL'
    line = f'  [{tag}] {name}'
    if extra:
        line += f'  ({extra})'
    print(line)
    return bool(ok)


# ───────────── number-theory tools ─────────────
def make_sieve(n):
    f = bytearray(b'\x01') * (n + 1)
    f[:2] = b'\x00\x00'
    for i in range(2, isqrt(n) + 1):
        if f[i]:
            f[i * i::i] = bytearray(len(f[i * i::i]))
    return [i for i in range(n + 1) if f[i]]


def trial_prime(p):
    """Independent primality test by trial division."""
    return p >= 2 and all(p % d for d in range(2, isqrt(p) + 1))


def droot(n):
    """Digital root of a positive integer."""
    return (n - 1) % 9 + 1


def sum_of_divs(n):
    """Sum of proper divisors via square-root pairing."""
    s, i = 1, 2
    while i * i <= n:
        if n % i == 0:
            s += i
            if n // i != i:
                s += n // i
        i += 1
    return s


def brute_divisors(n):
    """All proper divisors, brute force (for cross-checks)."""
    return [d for d in range(1, n) if n % d == 0]


def phi(n):
    result, m, d = n, n, 2
    while d * d <= m:
        if m % d == 0:
            while m % d == 0:
                m //= d
            result = result // d * (d - 1)
        d += 1
    if m > 1:
        result = result // m * (m - 1)
    return result


# ───────────── the zoo exhibits ─────────────
def beaver_dam(primes, pset):
    banner('🦫 BEAVER PRIME DAM · La Represa del Castor')
    print(f'  Sieve of Eratosthenes up to {LIMIT}: {len(primes)} primes.')
    print('  First 25 primes :', ' '.join(map(str, primes[:25])))
    print('  Last 6 primes   :', ' '.join(map(str, primes[-6:])))
    sample = primes[:50]
    ok = all(trial_prime(p) for p in sample)
    verdict(f'trial-division cross-check of {len(sample)} primes', ok)
    if LIMIT in KNOWN_PI:
        expected = KNOWN_PI[LIMIT]
        verdict(f'prime count matches known pi({LIMIT}) = {expected}',
                len(primes) == expected, f'counted {len(primes)}')


def goldbach_geese(primes, pset):
    banner('🦢 GOLDBACH GEESE · Los Cisnes de Goldbach')
    total = ok = 0
    examples = []
    for n in range(4, GOLD_LIMIT + 1, 2):
        total += 1
        for p in primes:
            if p > n:
                break
            if n - p in pset:
                ok += 1
                if len(examples) < 4:
                    examples.append((n, p, n - p))
                break
    for n, a, b in examples:
        print(f'    e.g. {n} = {a} + {b}')
    verdict(f'Goldbach verified for {total} even numbers up to {GOLD_LIMIT}',
            ok == total, f'{ok}/{total}')


def ulam_owl(primes, pset):
    banner('🦉 ULAM OWL · El Búho de Ulam')
    size = SPR_SIZE
    half = size // 2
    total = size * size
    # FIX: the spiral numbers k run 1..total, so the position list needs
    # total+1 slots (index 0 is unused).  The old list had only `total`
    # slots, so the final assignment pos[total] raised IndexError.
    pos = [None] * (total + 1)
    x = y = half
    k = 1
    dirs = [(1, 0), (0, 1), (-1, 0), (0, -1)]
    di = 0
    step = 1
    while k <= total:
        for _ in range(step):
            if k > total:
                break  # outer ring is partial for odd side lengths
            x += dirs[di][0]
            y += dirs[di][1]
            pos[k] = (x, y)
            k += 1
        di = (di + 1) % 4
        if di % 2 == 0:
            step += 1
    cells = [p for p in pos if p is not None]
    verdict(f'spiral walk visits all {total} cells exactly once',
            len(cells) == total and len(set(cells)) == total)
    verdict('spot-check: 5 sits upper-left of centre',
            pos[5] == (half - 1, half + 1))
    prime_cells = set()
    for p in primes:
        if p <= total:
            prime_cells.add(pos[p])
    print(f'  Prime arms (primes = #, composites = ·), {size}×{size}:')
    for y in range(size):
        print('    ' + ''.join('#' if (x, y) in prime_cells else '·'
                                for x in range(size)))
    verdict(f'all {len(prime_cells)} primes ≤ {total} plotted on the spiral',
            len(prime_cells) == sum(1 for p in primes if p <= total))


def fractal_fox(primes, pset):
    banner('🦊 DIGITAL-ROOT FRACTAL · La Fractal del Zorro')
    n = MULT_SIZE
    print(f'  droot(a·b) for a,b = 1..{n} (pattern repeats every 9):')
    print('      ' + ''.join(f'{b % 9 or 9:3}' for b in range(1, n + 1)))
    for a in range(1, n + 1):
        print(f'  {a % 9 or 9:3}  ' +
              ''.join(f'{droot(a * b):3}' for b in range(1, n + 1)))
    ok = all(droot(a * b) == droot(droot(a) * droot(b))
             for a in range(1, 500) for b in range(1, 500))
    verdict('casting property: dr(a·b) = dr(dr(a)·dr(b)) for a,b < 500', ok)


def nines_newt(primes, pset):
    banner('🐸 CASTING-OUT-NINES NEWT · La Rana de los Nueves')
    ok = True
    for _ in range(DIGIT_TRIES):
        n = rng.randint(1, 10**9)
        s = sum(int(d) for d in str(n))
        if n % 9 != s % 9:
            ok = False
    verdict(f'{DIGIT_TRIES} random numbers: n ≡ digit-sum (mod 9)', ok)


def euler_eagle(primes, pset):
    banner('🦅 EULER EAGLE · El Águila de Euler')
    z = cmath.exp(1j * pi)
    verdict("e^(iπ) + 1 = 0 (within 1e-12)", abs(z + 1) < 1e-12,
            f'error {abs(z + 1):.2e}')
    ok = True
    for _ in range(EULER_TRIES):
        theta = rng.uniform(0, 2 * pi)
        w = cmath.exp(1j * theta)
        if abs(abs(w) - 1) > 1e-9:
            ok = False
    verdict(f'{EULER_TRIES} random angles: |e^(iθ)| = 1', ok)


def collatz_canary(primes, pset):
    banner('🐤 COLLATZ CANARY · El Canario de Collatz')
    ok = True
    longest = (2, 0)
    for n in range(2, COLL_LIMIT + 1):
        m, steps = n, 0
        while m != 1:
            m = m // 2 if m % 2 == 0 else 3 * m + 1
            steps += 1
        if m != 1 or steps < 0:
            ok = False
        if steps > longest[1]:
            longest = (n, steps)
    verdict(f'Collatz reaches 1 for every n in 2..{COLL_LIMIT}', ok)
    print(f'    longest chain: {longest[0]} takes {longest[1]} steps')


def fermat_falcon(primes, pset):
    banner('🦅 FERMAT FALCON · El Halcón de Fermat')
    ok = True
    for p in primes[:200]:
        for a in range(2, 6):
            if pow(a, p - 1, p) != 1:
                ok = False
    verdict("Fermat's little theorem for first 200 primes, a = 2..5", ok)


def trivia_turtle(primes, pset):
    banner('🐢 ZOO TRIVIA · Curiosidades del Zoo')
    for t in TRIVIA:
        print('  ' + t)
    ok = all(sum_of_divs(n) == n for n in (6, 28, 496, 8128))
    verdict('6, 28, 496, 8128 are perfect (sum of proper divisors = n)', ok)
    ok2 = sum_of_divs(220) == 284 and sum_of_divs(284) == 220
    verdict('220 and 284 are amicable', ok2)


def main():
    print(CLEAR, end='')
    t0 = time.perf_counter()
    primes = make_sieve(LIMIT)
    pset = set(primes)
    beaver_dam(primes, pset)
    goldbach_geese(primes, pset)
    ulam_owl(primes, pset)
    fractal_fox(primes, pset)
    nines_newt(primes, pset)
    euler_eagle(primes, pset)
    collatz_canary(primes, pset)
    fermat_falcon(primes, pset)
    trivia_turtle(primes, pset)
    dt = time.perf_counter() - t0
    passed = sum(CHECKS)
    print()
    print('═' * W)
    print(f'  ZOO REPORT: {passed}/{len(CHECKS)} checks passed in {dt:.3f}s')
    print('═' * W)


if __name__ == '__main__':
    main()