# Generated by Cognia | 2026-04-05T20:16:34.388728
# Category: text-based strategy game
# Score: 8.9/10

import random
import time

class Resource:
    def __init__(self, name, initial_amount):
        self.name = name
        self.amount = initial_amount

class Building:
    def __init__(self, name, resource_required, reward_resource=None, reward_points=0):
        self.name = name
        self.resource_required = resource_required
        self.reward_resource = reward_resource
        self.reward_points = reward_points

class Player:
    def __init__(self):
        self.resources = [Resource("Gold", 100), Resource("Wood", 50)]
        self.buildings = []
        self.points = 0

    def build(self, building):
        if all(resource.amount >= building.resource_required[resource_name] for resource_name, resource in building.resource_required.items()):
            for resource_name, resource_amount in building.resource_required.items():
                self.resources[resource_names.index(resource_name)].amount -= resource_amount
            self.points += building.reward_points
            self.buildings.append(building)
        else:
            print("Not enough resources to build this.")

def display_player_status(player):
    print(f"Resources:")
    for i, resource in enumerate(player.resources):
        print(f"{i+1}. {resource.name}: {resource.amount}")
    print(f"\nBuildings:")
    for i, building in enumerate(player.buildings):
        print(f"{i+1}. {building.name} (Points: {building.reward_points})")
    print(f"\nTotal Points: {player.points}")

def random_event(player):
    event = random.randint(1, 5)
    if event == 1:
        player.resources[0].amount += 20
        print("A merchant arrives with gold!")
    elif event == 2:
        player.resources[1].amount -= 10
        print("A log gets stolen from the woods!")
    elif event == 3:
        new_building = Building(random.choice(["Bridge", "Tower"]), {"Gold": 50, "Wood": 20})
        player.buildings.append(new_building)
        print(f"A new {new_building.name} appears!")
    elif event == 4:
        player.points += 10
        print("A friendly villager gifts you points!")
    elif event == 5:
        random_building = random.choice(player.buildings)
        removed_resources = random_building.resource_required.copy()
        for resource_name, resource_amount in removed_resources.items():
            player.resources[resource_names.index(resource_name)].amount += resource_amount
        print(f"A {random_building.name} disappears, taking its resources with it!")

def main():
    global resource_names
    resource_names = [name.name for name in Player().resources]
    player = Player()
    while True:
        display_player_status(player)
        print("\nOptions:")
        print("1. Build a building")
        print("2. Collect resources")
        print("3. Rest")
        option = input("> ")
        if option == "1":
            building_type = input("What type of building do you want to build (Bridge, Tower): ")
            building_name = Building(building_type.capitalize(), {"Gold": 50, "Wood": 20}, reward_resource=("Gold", 30), reward_points=10)
            player.build(building_name)
        elif option == "2":
            for i in range(len(player.resources)):
                if input(f"Do you want to collect {player.resources[i].name} ({player.resources[i].amount}?): ") == "":
                    player.resources[i].amount += 10
        elif option == "3":
            time.sleep(1)
            print('\033[2J\033[H', end='')
        else:
            print("Invalid option. Try again.")

if __name__ == "__main__":
    main()