# Generated by Cognia | 2026-07-20T02:58:38.719079
# Category: estimador de tokens para saber si un texto cabe en una ventana de contexto: funcion estimar_tokens(texto) que aproxima el numero de tokens sin dependencias, y funcion cabe(texto, limite) que dice si entra; con unittest de al menos 3 metodos test_ y unittest.main(exit=False)
# Score: 7.6/10
# Origin: predefined category

import unittest
import random

def estimar_tokens(texto):
    """Estima el número de tokens en un texto."""
    return len(texto.split())

def cabe(texto, limite):
    """Indica si el texto cabe dentro del límite de tokens."""
    return estimar_tokens(texto) <= limite

class TestTokenEstimator(unittest.TestCase):
    def test_corto(self):
        texto = "Hola mundo"
        self.assertTrue(cabe(texto, 10))

    def test_largo(self):
        texto = " ".join(["palabra"] * 20)
        self.assertFalse(cabe(texto, 15))

    def test_exacto(self):
        texto = " ".join(["token"] * 7)
        self.assertTrue(cabe(texto, 7))

def main():
    print("\033[2J\033[H", end='')  # Clear terminal
    print("Token Estimator")
    print("--------------")
    
    # Generate some sample text
    palabras = ["amigo", "familia", "python", "programación", "terminal", "ASCII", "ANSI", "colores", "pruebas", "unitarias"]
    texto_aleatorio = " ".join(random.choices(palabras, k=random.randint(5, 15)))
    
    # Define a token limit
    limite_tokens = 10
    
    # Check if the text fits within the token limit
    if cabe(texto_aleatorio, limite_tokens):
        print(f"El texto '{texto_aleatorio}' cabe dentro del límite de {limite_tokens} tokens.")
    else:
        print(f"El texto '{texto_aleatorio}' no cabe dentro del límite de {limite_tokens} tokens.")
    
    # Run tests
    unittest.main(exit=False)

if __name__ == "__main__":
    main()