# Generated by Cognia | 2026-04-05T20:25:01.016472
# Category: text-based strategy game
# Score: 5.6/10

import random

print('\033[2J\033[H')

def clear_screen():
    print('\033[2J\033[H', end='')

clear_screen()

directions = ['N', 'S', 'E', 'W']
treasure_x, treasure_y = 3, 4
player_x, player_y = 0, 0

while True:
    clear_screen()
    forest = [['.' for _ in range(10)] for _ in range(10)]
    
    if random.random() < 0.1:
        forest[player_y][player_x] = 'F'
        
    if treasure_x == player_x and treasure_y == player_y:
        print('Congratulations, you found the treasure!')
        break

    forest[player_y][player_x] = 'F'
    forest[player_y + random.choice([-1, 0, 1])][player_x + random.choice([-1, 0, 1])] = ' '

    if player_x > 0 and directions[(random.randint(0, 3)) % 4] == 'E':
        player_x += 1
    elif player_x < 8 and directions[(random.randint(0, 3)) % 4] == 'W':
        player_x -= 1
    if player_y > 0 and directions[(random.randint(0, 3)) % 4] == 'S':
        player_y -= 1
    elif player_y < 8 and directions[(random.randint(0, 3)) % 4] == 'N':
        player_y += 1

    for row in forest:
        print(' '.join(row))

print('\033[2J\033[H')