# Generated by Cognia | 2026-08-17T18:50:50.556612
# Category: Random animal fact generator that displays a new fact every second
# Score: auto-asignado 5.6/10 (SIN VERIFICAR)
# Origin: self-proposed idea

import random
import time

# Constants
ANIMAL_FACTS = [
    "Did you know that elephants are the only mammals that can't jump?",
    "Kangaroos have three vaginas.",
    "Sloths have claws like humans.",
    "Octopuses have three hearts.",
    "Giraffes have the same number of neck vertebrae as humans.",
    "Flamingos can only eat with their heads upside down.",
    "A shrimp's heart is in its head.",
    "The blue whale's tongue can weigh as much as an elephant.",
    "Starfish don't have brains or blood.",
    "Bees have five eyes.",
    "Chameleons have eyes that can move independently.",
    "Penguins can jump as high as they can swim.",
    "Dolphins sleep with one eye open.",
    "Snails can sleep for three years.",
    "Frogs can live without lungs for up to 12 months.",
    "Cats have claws that are curved, which helps them climb trees.",
    "Dogs have three eyelids.",
    "Sharks do not have eyelashes.",
    "The world's oldest known animal is a 507-year-old clam.",
    "Ants can lift 50 times their own body weight.",
    "Snakes can't stick their tongues out.",
    "Bats are the only mammals that can truly fly.",
    "Honey never spoils.",
    "Penguins have a layer of fat called blubber that keeps them warm.",
    "Fish have eyelids.",
    "Whales have hair.",
    "Rabbits can't vomit.",
    "Flamingos are pink because of the food they eat.",
    "The average person has 60,000 hairs on their head.",
    "Frogs can't jump backward.",
    "Camels have three eyelids.",
    "Pandas have a thumb-like bone that evolved to help them grasp bamboo.",
    "Bees have two stomachs.",
    "Octopuses have blue blood.",
    "Cows have four stomachs.",
    "The world's smallest bird is the bee hummingbird.",
    "Snails can sleep for three years.",
    "Frogs can live without lungs for up to 12 months.",
    "Chameleons have eyes that can move independently.",
    "Penguins can jump as high as they can swim.",
    "Dolphins sleep with one eye open.",
    "Snails can sleep for three years.",
    "Frogs can live without lungs for up to 12 months.",
    "Kangaroos have three vaginas.",
    "Sloths have claws like humans.",
    "Octopuses have three hearts.",
    "Giraffes have the same number of neck vertebrae as humans.",
    "Flamingos can only eat with their heads upside down.",
    "Shrimp have three hearts.",
    "The blue whale's tongue can weigh as much as an elephant.",
    "Starfish don't have brains or blood.",
    "Bees have five eyes.",
    "Chameleons have eyes that can move independently.",
    "Penguins can jump as high as they can swim.",
    "Dolphins sleep with one eye open.",
    "Snails can sleep for three years.",
    "Frogs can live without lungs for up to 12 months.",
    "Cats have claws that are curved, which helps them climb trees.",
    "Dogs have three eyelids.",
    "Sharks do not have eyelashes.",
    "The world's oldest known animal is a 507-year-old clam.",
    "Ants can lift 50 times their own body weight.",
    "Snakes can't stick their tongues out.",
    "Bats are the only mammals that can truly fly.",
    "Honey never spoils.",
    "Penguins have a layer of fat called blubber that keeps them warm.",
    "Fish have eyelids.",
    "Whales have hair.",
    "Rabbits can't vomit.",
    "Flamingos are pink because of the food they eat.",
    "The average person has 60,000 hairs on their head.",
    "Frogs can't jump backward.",
    "Camels have three eyelids.",
    "Pandas have a thumb-like bone that evolved to help them grasp bamboo.",
    "Bees have two stomachs.",
    "Octopuses have blue blood.",
    "Cows have four stomachs.",
    "The world's smallest bird is the bee hummingbird.",
    "Snails can sleep for three years.",
    "Frogs can live without lungs for up to 12 months.",
    "Chameleons have eyes that can move independently.",
    "Penguins can jump as high as they can swim.",
    "Dolphins sleep with one eye open.",
    "Snails can sleep for three years.",
    "Frogs can live without lungs for up to 12 months.",
]

def clear_terminal():
    print('\033[2J\033[H', end='')

def display_random_fact():
    clear_terminal()
    fact = random.choice(ANIMAL_FACTS)
    print(fact)

def main():
    while True:
        display_random_fact()
        time.sleep(1)

if __name__ == "__main__":
    main()