# Generated by Cognia | 2026-07-20T00:42:55.931479
# Category: mapa de proyecto Python con ast: funcion mapear(directorio) que recorre los .py y devuelve para cada fichero la lista de clases y funciones con su linea, y funcion resumen(mapa) que lo formatea compacto; probar sobre un directorio temporal creado en el propio test con tempfile, con unittest y unittest.main(exit=False)
# Score: 7.0/10
# Origin: predefined category

import ast
import tempfile
import unittest
from pathlib import Path

def mapear(directorio):
    mapa = {}
    for path in Path(directorio).rglob('*.py'):
        with path.open() as f:
            contenido = f.read()
        tree = ast.parse(contenido)
        clases = [node for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]
        funciones = [node for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)]
        mapa[str(path.relative_to(directorio))] = {'clases': [(clase.name, clase.lineno) for clase in clases],
                                                  'funciones': [(funcion.name, funcion.lineno) for funcion in funciones]}
    return mapa

def resumen(mapa):
    for archivo, detalles in mapa.items():
        print(f"Archivo: {archivo}")
        print("Clases:")
        for clase, linea in detalles['clases']:
            print(f"  - {clase} (Línea {linea})")
        print("Funciones:")
        for funcion, linea in detalles['funciones']:
            print(f"  - {funcion} (Línea {linea})")
        print()

class TestMapeo(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.dir_path = self.temp_dir.name
        with open(Path(self.dir_path) / 'test1.py', 'w') as f:
            f.write("class Clase1: pass\ndef funcion1(): pass")
        with open(Path(self.dir_path) / 'test2.py', 'w') as f:
            f.write("class Clase2: pass\n\n")
            f.write("def funcion2(): pass\n")

    def tearDown(self):
        self.temp_dir.cleanup()

    def test_mapear(self):
        mapa = mapear(self.dir_path)
        self.assertIn('test1.py', mapa)
        self.assertIn('test2.py', mapa)
        self.assertEqual(len(mapa['test1.py']['clases']), 1)
        self.assertEqual(len(mapa['test1.py']['funciones']), 1)
        self.assertEqual(len(mapa['test2.py']['clases']), 1)
        self.assertEqual(len(mapa['test2.py']['funciones']), 1)

    def test_resumen(self):
        mapa = mapear(self.dir_path)
        resumen(mapa)

if __name__ == '__main__':
    unittest.main(exit=False)