"""
shattering/distillation/losses.py
===================================
Loss functions for SRDN distillation.

sequence_level_loss:
  Cross-entropy between student logit distribution and teacher token sequence.
  Ollama returns text only — teacher tokens are the tokenized teacher output.
  Student logits must cover the same vocabulary; missing positions are zero-padded.

consistency_loss:
  Measures disagreement between LOGOS, TECHNE, and RHETOR sub-model outputs
  on the same prompt. Uses mean squared error between output token distributions.
  Low consistency_loss means all three sub-models agree on boundary inputs.
  High consistency_loss indicates domain drift and guides specialization.
"""

from __future__ import annotations

import logging
from typing import Dict, List

import numpy as np

logger = logging.getLogger(__name__)

_SEQ_WEIGHT   = 0.7
_CONS_WEIGHT  = 0.3
_VOCAB_SIZE   = 32000
_EPS          = 1e-9


def sequence_level_loss(
    student_logits: np.ndarray,
    teacher_tokens: List[int],
) -> float:
    """
    Cross-entropy loss: student distribution vs teacher token sequence.

    Args:
        student_logits: (seq_len, vocab_size) float32 — raw logits from student model
        teacher_tokens: list of int token ids generated by teacher (same length as seq_len)

    Returns:
        Scalar float32 cross-entropy loss, averaged over positions.
    """
    if len(teacher_tokens) == 0 or student_logits.shape[0] == 0:
        return 0.0

    seq_len = min(student_logits.shape[0], len(teacher_tokens))
    logits  = student_logits[:seq_len].astype(np.float32)
    tokens  = teacher_tokens[:seq_len]

    # Pad to vocab_size if needed
    if logits.shape[1] < _VOCAB_SIZE:
        pad = np.zeros((seq_len, _VOCAB_SIZE - logits.shape[1]), dtype=np.float32)
        logits = np.concatenate([logits, pad], axis=1)
    elif logits.shape[1] > _VOCAB_SIZE:
        logits = logits[:, :_VOCAB_SIZE]

    # Softmax
    logits_stable = logits - logits.max(axis=-1, keepdims=True)
    exp_l = np.exp(logits_stable.clip(-30, 30))
    probs = exp_l / exp_l.sum(axis=-1, keepdims=True).clip(_EPS)

    # Gather teacher token probabilities and compute negative log-likelihood
    token_arr = np.array(tokens, dtype=np.int64).clip(0, _VOCAB_SIZE - 1)
    gathered  = probs[np.arange(seq_len), token_arr]
    loss      = -np.log(gathered.clip(_EPS)).mean()

    return float(loss)


def consistency_loss(
    outputs_dict: Dict[str, np.ndarray],
    prompt: str = "",
) -> float:
    """
    Measure disagreement between sub-model outputs on the same prompt.

    Args:
        outputs_dict: maps sub_model name -> (seq_len, vocab_size) logit array.
                      Any subset of {"logos", "techne", "rhetor"} is accepted.
        prompt:       original prompt (unused in computation; available for logging)

    Returns:
        Scalar float32 — mean pairwise MSE between softmax distributions.
        0.0 if fewer than two sub-models are provided.
    """
    names = sorted(outputs_dict.keys())
    if len(names) < 2:
        return 0.0

    # Compute softmax distributions for each sub-model
    dists: Dict[str, np.ndarray] = {}
    for name, logits in outputs_dict.items():
        logits_f = np.asarray(logits, dtype=np.float32)
        stable   = logits_f - logits_f.max(axis=-1, keepdims=True)
        exp_l    = np.exp(stable.clip(-30, 30))
        dists[name] = exp_l / exp_l.sum(axis=-1, keepdims=True).clip(_EPS)

    # Mean pairwise MSE across all sub-model pairs
    pair_mses = []
    for i, n1 in enumerate(names):
        for n2 in names[i + 1:]:
            d1   = dists[n1]
            d2   = dists[n2]
            # Align seq lengths
            min_seq = min(d1.shape[0], d2.shape[0])
            mse  = float(np.mean((d1[:min_seq] - d2[:min_seq]) ** 2))
            pair_mses.append(mse)

    loss = float(np.mean(pair_mses)) if pair_mses else 0.0
    logger.debug(
        "[Distillation] consistency_loss=%.4f prompt='%s...'",
        loss, prompt[:40],
    )
    return loss


def combined_loss(
    student_logits: np.ndarray,
    teacher_tokens: List[int],
    outputs_dict: Dict[str, np.ndarray],
    prompt: str = "",
    training_weight: float = 1.0,
) -> float:
    """
    Full SRDN training loss:
      (0.7 * seq_loss + 0.3 * cons_loss) * training_weight

    Args:
        student_logits:  (seq_len, vocab_size) logits from the student sub-model
        teacher_tokens:  token ids from Ollama teacher output
        outputs_dict:    logits from all three sub-models for consistency loss
        prompt:          original prompt (passed to consistency_loss for logging)
        training_weight: feedback-weight scaling factor (1.0–2.0 from gold episodes)
    """
    seq  = sequence_level_loss(student_logits, teacher_tokens)
    cons = consistency_loss(outputs_dict, prompt)
    return (_SEQ_WEIGHT * seq + _CONS_WEIGHT * cons) * float(training_weight)
