# Generated by Cognia | 2026-08-17T15:23:26.068262
# Category: text similarity analyzer with sample texts
# Score: auto-asignado 8.1/10 (SIN VERIFICAR)
# Origin: predefined category

"""Text Similarity Analyzer - generates sample texts and compares them."""

# Build a word pool and some sentences from it
WORDS = (
    "swift", "ancient", "tiny", "vast", "bold", "quiet", "fierce", "gentle",
    "moon", "star", "river", "mountain", "cloud", "ocean", "forest", "garden",
    "whisper", "shout", "dream", "wander", "glow", "sparkle", "drift", "sail"
)
SENTENCES = [
    "A swift river winds through the quiet forest at dawn.",
    "The ancient moon watches over tiny stars drifting on the vast ocean.",
    "Bold whispers travel through the vast forest at midnight.",
    "Gentle clouds sail over the garden where a tiny mountain sleeps.",
    "A fierce dragon glows in the dark, watching the quiet forest drift.",
    "The tiny river sparkles as it wanders toward the bold moon.",
    "Vast clouds whisper to the garden where ancient mountains sleep.",
    "A quiet star drifts above the garden, near the tiny, gentle moon.",
]

def similarity(text1, text2):
    """Jaccard similarity between two sentences (0.0 to 1.0)."""
    # Normalize: lowercase, strip punctuation, split on spaces
    normalize = lambda s: s.lower().translate(str.maketrans('', '', '.,!?;:'))
    words1 = set(normalize(text1).split())
    words2 = set(normalize(text2).split())
    if not words1 and not words2:
        return 1.0
    union = words1 | words2
    inter = words1 & words2
    return len(inter) / len(union)

def generate_sentence():
    """Pretend to create a fresh sentence by mixing words."""
    length = 3 + (len(WORDS) % 5)  # 3 to 7 words
    return " ".join(random.sample(WORDS, length))

# Import random for some variety (standard library, not blocking)
import random

def main():
    # Clear the terminal once
    print('\033[2J\033[H', end='')

    # ASCII header
    print('\033[1;35m╔════════════════════════════════════════════════════════════╗')
    print('\033[1;35m║                    TEXT SIMILARITY ANALYZER                 ║')
    print('\033[1;35m╚════════════════════════════════════════════════════════════╝\033[0m')

    # Show the sample sentences
    print('\033[1;33m───────── GENERATED SAMPLE TEXTS ──────────\033[0m')
    for i, s in enumerate(SENTENCES):
        print(f'\033[1;35m{chr(149)+str(i+1)}\033[0m  {s}')

    # Compute pairwise similarities
    print('\033[1;33m───────── SIMILARITY RESULTS ──────────\033[0m')
    for i, t1 in enumerate(SENTENCES):
        for t2 in SENTENCES[i+1:]:
            score = similarity(t1, t2)
            color = '\033[1;32m' if score > 0.4 else '\033[1;34m'
            print(f'\033[1;35m{chr(149)+str(i+1)}\033[0m ─ {chr(149)+str(i+2)}\033[0m │\033[1;33m{t1[:20]}…\033[0m vs |\033[1;33m{t2[:20]}…\033[0m\033[0m')
            print(f'\033[{color}Jaccard = {score:.3f}\033[0m')

    # Verify that self-similarity is essentially 1.0
    print('\033[1;33m───────── VERIFICATION ──────────\033[0m')
    self_sim = similarity(SENTENCES[0], SENTENCES[0])
    verdict = 'PASS' if self_sim >= 0.99 else 'FAIL'
    print(f'\033[1;35mVerdict: {verdict}\033[0m (self-similarity = {self_sim:.4f})')

    # Generate a few more "on the fly" sentences
    print('\033[1;33m───────── MORE GENERATED TEXTS ──────────\033[0m')
    for j in range(3):
        fresh = generate_sentence()
        fresh_sim = similarity(fresh, SENTENCES[j])
        print(f'\033[1;35m{chr(149)+str(j+1)}\033[0m  {fresh}')
        print(f'\033[1;34m→ Similarity to original: {fresh_sim:.3f}\033[0m')

if __name__ == '__main__':
    main()