# Generated by Cognia | 2026-08-17T23:51:11.168175
# Category: di hola en 3 palabras
# Score: auto-asignado 6.0/10 (SIN VERIFICAR)
# Origin: predefined category

class HolaPrinter:
    def __init__(self):
        self.languages = {
            'Spanish': 'Hola',
            'English': 'Hello',
            'French': 'Bonjour'
        }

    def print_greetings(self):
        for language, greeting in self.languages.items():
            print(f"{language}: {greeting}")

if __name__ == "__main__":
    # Clear terminal
    print('\033[2J\033[H', end='')

    # Create HolaPrinter instance
    hola_printer = HolaPrinter()

    # Print greetings
    hola_printer.print_greetings()

    # Verification
    expected_output = [
        "Spanish: Hola",
        "English: Hello",
        "French: Bonjour"
    ]

    # Collect actual output
    from io import StringIO
    import sys

    # Redirect stdout to capture print statements
    captured_output = StringIO()
    sys.stdout = captured_output

    # Run the print_greetings method
    hola_printer.print_greetings()

    # Reset stdout
    sys.stdout = sys.__stdout__

    # Get the captured output
    actual_output = captured_output.getvalue().strip().split('\n')

    # Verify the output
    if actual_output == expected_output:
        print("PASS: Output matches expected.")
    else:
        print("FAIL: Output does not match expected.")
        print("Expected:")
        for line in expected_output:
            print(line)
        print("Got:")
        for line in actual_output:
            print(line)