# Generated by Cognia | 2026-04-05T19:57:40.410793
# Category: reaction-diffusion pattern simulator
# Score: 7.3/10

import random
import time
import sys

# Clear the terminal
def clear_terminal():
    print('\033[2J\033[H', end='')

# Reaction diffusion simulator parameters
grid_size = 20
population_density = 0.5
birth_rate = 0.1
death_rate = 0.05
diffusion_rate = 0.01

# Grid to represent the reaction-diffusion system
def create_grid(size):
    grid = [[random.random() for _ in range(size)] for _ in range(size)]
    return grid

# Update the simulation step using the logistic map and reaction-diffusion equations
def update_simulation(grid, population_density, birth_rate, death_rate, diffusion_rate):
    new_grid = [[0.0 for _ in range(len(grid[0]))] for _ in range(len(grid))]
    for i in range(len(grid)):
        for j in range(len(grid[i])):
            neighbors = [grid[k][j] if k < len(grid) else 0 for k in range(i-1, i+2)]
            average_neighbors = sum(neighbors) / len(neighbors)
            new_grid[i][j] = grid[i][j] + birth_rate * (1 - grid[i][j]) * (average_neighbors - population_density)
            new_grid[i][j] += diffusion_rate * (grid[i][j] - population_density)
    return [min(max(new_value, 0.0), 1.0) for row in new_grid for new_value in row]

# Main simulation loop
def simulate(num_steps):
    clear_terminal()
    grid = create_grid(grid_size)
    for step in range(1, num_steps + 1):
        print(f'Step {step} - Population Density: {population_density}')
        grid = update_simulation(grid.copy(), population_density, birth_rate, death_rate, diffusion_rate)
        time.sleep(0.5)

# Color themes
def walt_disney_color():
    return '\033[38;2;255;128;0m'  # Bright orange

def juan_luis_color():
    return '\033[38;2;0;0;204m'  # Dark blue

# Main program loop
while True:
    print('\nChoose a color theme:')
    print('1. Walt Disney (Bright Orange)')
    print('2. Juan Luis (Dark Blue)')
    choice = input()
    if choice == '1':
        def update_simulation(grid, population_density, birth_rate, death_rate, diffusion_rate):
            new_grid = [[0.0 for _ in range(len(grid[0]))] for _ in range(len(grid))]
            for i in range(len(grid)):
                for j in range(len(grid[i])):
                    neighbors = [grid[k][j] if k < len(grid) else 0 for k in range(i-1, i+2)]
                    average_neighbors = sum(neighbors) / len(neighbors)
                    new_grid[i][j] = grid[i][j] + birth_rate * (1 - grid[i][j]) * (average_neighbors - population_density)
                    new_grid[i][j] += diffusion_rate * (grid[i][j] - population_density)
            return [min(max(new_value, 0.0), 1.0) for row in new_grid for new_value in row]
        clear_terminal()
        grid_size = 20
        population_density = 0.5
        birth_rate = 0.1
        death_rate = 0.05
        diffusion_rate = 0.01
    elif choice == '2':
        def update_simulation(grid, population_density, birth_rate, death_rate, diffusion_rate):
            new_grid = [[0.0 for _ in range(len(grid[0]))] for _ in range(len(grid))]
            for i in range(len(grid)):
                for j in range(len(grid[i])):
                    neighbors = [grid[k][j] if k < len(grid) else 0 for k in range(i-1, i+2)]
                    average_neighbors = sum(neighbors) / len(neighbors)
                    new_grid[i][j] = grid[i][j] + birth_rate * (1 - grid[i][j]) * (average_neighbors - population_density)
                    new_grid[i][j] += diffusion_rate * (grid[i][j] - population_density)
            return [min(max(new_value, 0.0), 1.0) for row in new_grid for new_value in row]
        clear_terminal()
        grid_size = 20
        population_density = 0.5
        birth_rate = 0.1
        death_rate = 0.05
        diffusion_rate = 0.01

    choice = input("Enter 'q' to quit: ")
    if choice == 'q':
        break

    num_steps = int(input('Choose the number of simulation steps (1-100): '))
    simulate(num_steps)