# Generated by Cognia | 2026-08-17T21:31:43.796132
# Category: Automatic pet care simulator monitoring virtual pet health needs
# Score: auto-asignado 5.6/10 (SIN VERIFICAR)
# Origin: self-proposed idea

# Automatic Pet Care Simulator
import random
import time

# Constants
PETS_COUNT = 3
HEALTH_CHECK_INTERVAL = 5  # seconds
HUNGER_THRESHOLD = 30
THIRST_THRESHOLD = 30
HAPPINESS_THRESHOLD = 30
HEALTH_DECREASE_RATE = 1  # per health check interval
FEED_AMOUNT = 10
DRINK_AMOUNT = 10
PLAY_AMOUNT = 10
MAX_HUNGER = 100
MAX_THIRST = 100
MAX_HAPPINESS = 100

# Pet Class
class Pet:
    def __init__(self, name):
        self.name = name
        self.hunger = random.randint(0, MAX_HUNGER)
        self.thirst = random.randint(0, MAX_THIRST)
        self.happiness = random.randint(0, MAX_HAPPINESS)
        self.health = 100

    def feed(self):
        self.hunger = max(0, self.hunger - FEED_AMOUNT)
        print(f"Fed {self.name}: Hunger now {self.hunger}")

    def drink(self):
        self.thirst = max(0, self.thirst - DRINK_AMOUNT)
        print(f"Drank for {self.name}: Thirst now {self.thirst}")

    def play(self):
        self.happiness = min(MAX_HAPPINESS, self.happiness + PLAY_AMOUNT)
        print(f"Played with {self.name}: Happiness now {self.happiness}")

    def update_health(self):
        if self.hunger > HUNGER_THRESHOLD:
            self.health -= HEALTH_DECREASE_RATE
        if self.thirst > THIRST_THRESHOLD:
            self.health -= HEALTH_DECREASE_RATE
        if self.happiness < HAPPINESS_THRESHOLD:
            self.health -= HEALTH_DECREASE_RATE
        self.health = max(0, self.health)
        print(f"Updated health for {self.name}: Health now {self.health}")

    def needs_attention(self):
        return self.health < 50 or self.hunger > 50 or self.thirst > 50 or self.happiness < 50

# Initialize pets
pets = [Pet(f"Pet{i+1}") for i in range(PETS_COUNT)]

# Simulation loop
for _ in range(20):  # Run for 20 intervals
    print('\033[2J\033[H', end='')  # Clear terminal
    for pet in pets:
        pet.update_health()
        if pet.needs_attention():
            if pet.hunger > HUNGER_THRESHOLD:
                pet.feed()
            if pet.thirst > THIRST_THRESHOLD:
                pet.drink()
            if pet.happiness < HAPPINESS_THRESHOLD:
                pet.play()
    time.sleep(HEALTH_CHECK_INTERVAL)

# Final health check
print('\033[2J\033[H', end='')  # Clear terminal
print("Final health check results:")
for pet in pets:
    print(f"{pet.name}: Health {pet.health}, Hunger {pet.hunger}, Thirst {pet.thirst}, Happiness {pet.happiness}")
    if pet.health < 50:
        print(f"PASS: {pet.name} needs medical attention.")
    else:
        print(f"FAIL: {pet.name} is healthy.")

# Verification
print("\nVerification results:")
for pet in pets:
    if pet.hunger <= HUNGER_THRESHOLD and pet.thirst <= THIRST_THRESHOLD and pet.happiness >= HAPPINESS_THRESHOLD:
        print(f"PASS: {pet.name} meets all health criteria.")
    else:
        print(f"FAIL: {pet.name} does not meet all health criteria.")