# Generated by Cognia | 2026-04-05T21:27:38.285380
# Category: cellular automata simulator
# Score: 5.1/10

import random
import time

print('\033[2J\033[H', end='')

def initialize_grid(size, density):
    grid = [[random.choice([0,1]) for _ in range(size)] for _ in range(size)]
    return grid

def count_neighbors(grid, x, y):
    neighbors = 0
    for dx in [-1, 0, 1]:
        for dy in [-1, 0, 1]:
            if dx == 0 and dy == 0:
                continue
            nx, ny = (x+dx)%size, (y+dy)%size
            neighbors += grid[ny][nx]
    return neighbors

def next_generation(grid):
    size = len(grid)
    new_grid = [[0 for _ in range(size)] for _ in range(size)]
    for x in range(size):
        for y in range(size):
            live_neighbors = count_neighbors(grid, x, y)
            if grid[y][x] == 1:
                if live_neighbors < 2 or live_neighbors > 3:
                    new_grid[y][x] = 0
            else:
                if live_neighbors == 3:
                    new_grid[y][x] = 1
    return new_grid

def simulate(grid, size, density, generations):
    for _ in range(generations):
        print('\033[2J\033[H', end='')
        print('\n'.join([' '.join(['*' if cell else ' ' for cell in row]) for row in grid]))
        time.sleep(0.5)
        grid = next_generation(grid)

def main():
    size = 50
    density = 0.4
    generations = 100
    print('Conway\'s Game of Life:')
    simulate(initialize_grid(size, density), size, density, generations)

if __name__ == '__main__':
    main()