# Generated by Cognia | 2026-04-06T21:11:44.693445
# Category: word frequency analyzer
# Score: 7.0/10

import sys

def main():
    print("Word Frequency Analyzer (Modelo Permitido)")
    print("---------------------------")

    while True:
        print("\n1. Text File")
        print("2. stdin")
        choice = input("Choose an option: ")

        if choice == "1":
            text = input("Enter a file path or copy and paste the contents into the console: ")
            try:
                with open(text, 'r') as f:
                    lines = [line.strip() for line in f.readlines()]
                    word_freq = {}
                    for line in lines:
                        words = line.split()
                        if len(words) > 0:
                            for word in words:
                                word = word.lower()
                                if word not in word_freq:
                                    word_freq[word] = 1
                                else:
                                    word_freq[word] += 1
                    print("\nWord Frequency:")
                    for word, count in sorted(word_freq.items()):
                        print(f"{word}: {count}")
            except FileNotFoundError:
                print("File not found. Please try again.")

        elif choice == "2":
            text = input("Enter a string to analyze: ")
            words = text.split()
            word_freq = {}
            for word in words:
                if len(word) > 1:
                    word = word.lower()
                    if word not in word_freq:
                        word_freq[word] = 1
                    else:
                        word_freq[word] += 1

            print("\nWord Frequency:")
            for word, count in sorted(word_freq.items()):
                print(f"{word}: {count}")

        elif choice == "3":
            print("Exiting...")
            break

        else:
            print("Invalid option. Please choose again.")

if __name__ == "__main__":
    main()