# Generated by Cognia | 2026-09-08T03:32:16.305632
# Category: number theory explorer that prints interesting patterns
# Score: auto-asignado 8.9/10 (SIN VERIFICAR)
# Origin: predefined category

# Number Theory Explorer - Serpents & Spirals Edition
# Standard library only. Runs 100% automatically, no input.

import math

# =================== Tunable constants ===================
SIZE_LIMIT        = 200      # sieve + density chart range
CHART_BUCKETS     = 10       # histogram buckets for prime density
GRID_MOD          = 12       # size of the multiplication grid
PYTH_MAX_U        = 24       # Euclid u-bound for primitive triples
PERFECT_LIMIT     = 5000     # search perfect numbers under this
FERMAT_CASES      = [(2, 5), (3, 7), (5, 13), (7, 19), (11, 23), (2, 29)]
COLLATZ_SEEDS     = [7, 15, 27, 233, 626, 97]
KAPREKAR_SEEDS    = [1234, 2024, 8753, 4321]
CYCLIC_NUMBER     = 142857
MAX_COLLATZ_STEPS = 10000

# The python for each section (conocimiento_python theme)
SNAKES = ["Bueno", "Cobra", "Mamba", "Boa",
          "Piton", "Viper", "Anaconda", "Naja", "Taipan"]

results = []  # collects booleans for the final tally

def report(name, ok):
    results.append(bool(ok))
    print(f"   [{'PASS' if ok else 'FAIL'}] {name}")

def header(num, snake, title, sub):
    bar = "=" * 66
    print()
    print(bar)
    print(f"  Conocimiento {num}  /  snake: {snake}")
    print(f"  {title}")
    print(f"  {sub}")
    print(bar)

# =================== Primitives ===================

def sieve(n):
    flags = [True] * (n + 1)
    flags[0] = flags[1] = False
    for i in range(2, int(n ** 0.5) + 1):
        if flags[i]:
            for j in range(i * i, n + 1, i):
                flags[j] = False
    return [i for i in range(n + 1) if flags[i]]

def trial_primes(n):
    return [i for i in range(2, n)
            if all(i % d for d in range(2, int(i ** 0.5) + 1))]

def sum_of_proper_divisors(n):
    if n < 2:
        return 0
    s = 1
    i = 2
    while i * i <= n:
        if n % i == 0:
            s += i
            if i != n // i:
                s += n // i
        i += 1
    return s

# =================== Sections ===================

def sec_sieve():
    header(1, SNAKES[0], "Sieve of Eratosthenes",
           f"primes under {SIZE_LIMIT}, cross-checked against trial division")
    primes = sieve(SIZE_LIMIT)
    check = trial_primes(SIZE_LIMIT)
    print(f"   primes = {', '.join(map(str, primes))}")
    report(f"sieve({SIZE_LIMIT}) == trial division ({len(primes)} primes)",
           primes == check)

def sec_chart():
    header(2, SNAKES[1], "Prime Density Chart",
           "histogram of primes per bucket across the range")
    primes = sieve(SIZE_LIMIT)
    per = SIZE_LIMIT // CHART_BUCKETS
    counts = [sum(1 for p in primes if i * per < p <= (i + 1) * per)
              for i in range(CHART_BUCKETS)]
    top = max(counts) or 1
    for i, c in enumerate(counts):
        bar = "#" * (c * 50 // top)
        print(f"   {i*per:4d}-{(i+1)*per-1:4d} |{bar:<50}| {c}")
    report("bucket counts sum to total prime count",
           sum(counts) == len(primes))

def sec_grid():
    header(3, SNAKES[2], f"Multiplication Grid mod {GRID_MOD}",
           "rows where gcd(i,n)=1 are full permutations (Euler phi)")
    n = GRID_MOD
    perm_rows = 0
    for i in range(1, n):
        row = [(i * j) % n for j in range(1, n)]
        is_perm = sorted(row) == list(range(1, n))
        perm_rows += is_perm
        mark = "*" if is_perm else " "
        print(f"   {i:2d} {mark} | " + " ".join(f"{v:2d}" for v in row))
    phi = sum(1 for k in range(1, n) if math.gcd(k, n) == 1)
    report(f"coprime rows ({perm_rows}) == phi({n}) = {phi}",
           perm_rows == phi)

def sec_pyth():
    header(4, SNAKES[3], "Pythagorean Triples (Euclid)",
           f"a=u^2-v^2, b=2uv, c=u^2+v^2 for coprime odd-parity pairs, u<={PYTH_MAX_U}")
    triples = set()
    for u in range(3, PYTH_MAX_U + 1):
        for v in range(2, u):
            if (u - v) % 2 == 1 and math.gcd(u, v) == 1:
                triples.add((u*u - v*v, 2*u*v, u*u + v*v))
    triples = sorted(triples, key=lambda t: t[2])
    for a, b, c in triples[:12]:
        print(f"   {a:4d}^2 + {b:4d}^2 = {c:4d}^2   (check: {a*a+b*b} == {c*c})")
    print(f"   ... and {len(triples) - 12} more triples generated")
    report(f"all {len(triples)} triples satisfy a^2+b^2=c^2",
           all(a*a + b*b == c*c for a, b, c in triples) and len(triples) > 0)

def sec_perfect():
    header(5, SNAKES[4], "Perfect Numbers",
           f"numbers equal to the sum of their proper divisors, under {PERFECT_LIMIT}")
    found = [n for n in range(2, PERFECT_LIMIT + 1)
             if sum_of_proper_divisors(n) == n]
    for n in found:
        print(f"   {n}: sum of proper divisors = {sum_of_proper_divisors(n)}")
    report(f"perfect numbers under {PERFECT_LIMIT} are exactly {found}",
           found == [6, 28])

def sec_fermat():
    header(6, SNAKES[5], "Fermat's Little Theorem",
           "for prime p: a^(p-1) mod p == 1")
    prime_set = set(sieve(SIZE_LIMIT))
    all_ok = True
    for a, p in FERMAT_CASES:
        r = pow(a, p - 1, p)
        ok = p in prime_set and r == 1
        all_ok &= ok
        print(f"   a={a:2d}, p={p:2d}: a^(p-1) mod p = {r:2d}   "
              f"{'PASS' if ok else 'FAIL'}")
    report("all Fermat cases hold (p prime, residue 1)", all_ok)
    r = pow(2, 8, 9)
    print(f"   counter-example: 2^8 mod 9 = {r} (not 1, because 9 is composite)")

def sec_collatz():
    header(7, SNAKES[6], "Collatz Convergence (3n+1)",
           "even: n//2, odd: 3n+1 - every seed should land on 1")
    all_ok = True
    for seed in COLLATZ_SEEDS:
        n, steps = seed, 0
        while n != 1 and steps < MAX_COLLATZ_STEPS:
            n = n // 2 if n % 2 == 0 else 3 * n + 1
            steps += 1
        ok = (n == 1)
        all_ok &= ok
        print(f"   seed={seed:4d}: reached 1 in {steps:4d} steps   "
              f"{'PASS' if ok else 'FAIL'}")
    report("all Collatz seeds converge to 1", all_ok)

def sec_kaprekar():
    header(8, SNAKES[7], "Kaprekar's Constant (6174)",
           "sort digits desc/asc, subtract - 4-digit seeds fall into 6174")
    def step(n):
        d = sorted(f"{n:04d}", reverse=True)
        return int("".join(d)) - int("".join(reversed(d)))
    all_ok = True
    for seed in KAPREKAR_SEEDS:
        n, trail = seed, []
        for _ in range(50):
            if n == 6174:
                break
            n = step(n)
            trail.append(n)
        ok = (n == 6174)
        all_ok &= ok
        print(f"   seed={seed}: " + " -> ".join(map(str, trail))
              + f"   {'PASS' if ok else 'FAIL'}")
    report("all seeds reach 6174", all_ok)

def sec_cyclic():
    header(9, SNAKES[8], "Cyclic Number 142857 (the 1/7 pattern)",
           "multiples 1..6 are digit rotations of the same six digits")
    base_digits = sorted(str(CYCLIC_NUMBER))
    all_ok = True
    for k in range(1, 7):
        prod = CYCLIC_NUMBER * k
        digits = sorted(str(prod))
        ok = digits == base_digits
        all_ok &= ok
        print(f"   {k} x {CYCLIC_NUMBER} = {prod:8d}   digits: "
              f"{''.join(digits)}   {'PASS' if ok else 'FAIL'}")
    report("all six multiples share the same digit multiset", all_ok)

# =================== Main ===================

def main():
    bar = "=" * 66
    print()
    print(bar)
    print("  NUMBER THEORY EXPLORER   (Serpents & Spirals Edition)")
    print("  9 classic patterns, each printed and verified live")
    print(bar)

    for section in (sec_sieve, sec_chart, sec_grid, sec_pyth, sec_perfect,
                    sec_fermat, sec_collatz, sec_kaprekar, sec_cyclic):
        section()

    passed = sum(results)
    total = len(results)
    print()
    print(bar)
    print(f"  FINAL TALLY: {passed}/{total} checks passed")
    verdict = ("ALL PATTERNS CONFIRMED - the python is happy"
               if passed == total else "SOME CHECKS FAILED - the python is sad")
    print(f"  VERDICT     : {verdict}")
    print(bar)

if __name__ == "__main__":
    main()