# Generated by Cognia | 2026-09-02T13:27:27.925660
# Category: number theory explorer that prints interesting patterns
# Score: auto-asignado 8.3/10 (SIN VERIFICAR)
# Origin: predefined category

#!/usr/bin/env python3
"""
Luna the Lobster's Number Theory Expedition
A data-driven explorer that prints fascinating number patterns.
"""

# ----------------------------------------------------------------------
# 1. TUNABLE CONSTANTS (data-driven, never user‑input)
# ----------------------------------------------------------------------
RANGE_END = 100          # Upper bound for most explorations
COLUMN_COUNT = 8         # Width of the prime ladder columns
BLOCK_WIDTH = 80         # Nice terminal width for wrapping

# Theme constants – animal, color, and a few "fun" numbers
THEME_ANIMAL = "Luna the Lobster"
THEME_COLOR = "magenta"
VERIFICATION_PRIMES = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71]
VERIFICATION_PERFECT = [6,28,496,8128]

# ----------------------------------------------------------------------
# 2. UTILITY FUNCTIONS (pure, no blocking calls)
# ----------------------------------------------------------------------
def clear_screen():
    """Clear terminal cleanly using escape sequences."""
    print('\033[2J\033[H', end='')

def centered(text, width):
    """Center text inside a fixed width, padding spaces on left/right."""
    lines = text.splitlines()
    return ' '.join(
        ' ' * ((width - len(line)) // 2) + line
        for line in lines
    )

def fmt_block(title, subtitle, body, width=BLOCK_WIDTH):
    """Print a nicely wrapped block."""
    print(centered(title, width))
    if subtitle:
        print(centered(subtitle, width))
    print(centered(body, width))
    print()

# ----------------------------------------------------------------------
# 3. NUMBER THEORY BUILDINGS
# ----------------------------------------------------------------------
def is_prime(n):
    """Classic primality test, O(√n)."""
    if n < 2:
        return False
    if n in (2,3):
        return True
    if n % 2 == 0:
        return False
    limit = int(n**0.5)
    for d in range(3, limit+1, 2):
        if n % d == 0:
            return False
    return True

def proper_divisors_sum(n):
    """Sum of proper divisors of n (i.e. all divisors except n)."""
    if n < 2:
        return 0
    total = 1  # 1 always divides any n > 1
    limit = int(n**0.5)
    for d in range(2, limit+1):
        if n % d == 0:
            total += d
            other = n // d
            if other != d and other != n:
                total += other
    return total

def is_perfect(n):
    """True if n equals sum of proper divisors."""
    return proper_divisors_sum(n) == n

def is_abundant(n):
    """True if n is strictly less than sum of proper divisors."""
    return proper_divisors_sum(n) > n

def primes_up_to(limit):
    """List of all primes ≤ limit."""
    primes = [2]
    for n in range(3, limit+1, 2):
        if is_prime(n):
            primes.append(n)
    return primes

def palindromic_primes_in_range(low, high):
    """Return primes between low and high that are also palindromes."""
    return [n for n in range(low, high+1) if is_prime(n) and str(n) == str(n)[::-1]]

def fibonacci_primes(limit):
    """First few Fibonacci numbers that are prime."""
    fib = [0, 1]
    while fib[-1] < limit:
        fib.append(fib[-1] + fib[-2])
    return [n for n in fib if is_prime(n) and n > 1]

def prime_gap_stats(low, high):
    """Smallest and largest gap between successive primes in the range."""
    primes = primes_up_to(high)
    primes = [p for p in primes if low <= p <= high]
    if len(primes) < 2:
        return None, None
    gaps = [primes[i+1] - primes[i] for i in range(len(primes)-1)]
    return min(gaps), max(gaps)

# ----------------------------------------------------------------------
# 4. EXPLORATION MODULES (each returns a nicely formatted body)
# ----------------------------------------------------------------------
def explore_primes(count):
    """Explore prime density up to a given count."""
    title = "Prime Density"
    subtitle = f"Numbers 1 … {count}"
    body = f"Examining numbers 1 … {count}:\n"
    body += f"  Primes found: {count}\n"
    body += f"  Density: {count / count}:\n"
    return (title, subtitle, body)

def explore_perfect_numbers(limit):
    """Find perfect numbers up to a limit."""
    title = "Perfect Numbers"
    subtitle = f"Up to {limit}"
    body = "Perfect numbers (sum of proper divisors equals the number itself):\n"
    for n in range(2, limit+1):
        if is_perfect(n):
            body += f"  {n}\n"
    return (title, subtitle, body)

def explore_abundant_numbers(limit):
    """Find abundant numbers up to a limit."""
    title = "Abundant Numbers"
    subtitle = f"Up to {limit}"
    body = "Abundant numbers (sum of proper divisors exceeds the number):\n"
    for n in range(2, limit+1):
        if is_abundant(n):
            body += f"  {n}\n"
    return (title, subtitle, body)

def explore_palindromic_primes(low, high):
    """Explore palindromic primes in a range."""
    title = "Palindromic Primes"
    subtitle = f"Between {low} and {high}"
    body = "Primes that read the same forwards and backwards:\n"
    for n in palindromic_primes_in_range(low, high):
        body += f"  {n}\n"
    return (title, subtitle, body)

def explore_fibonacci_primes(limit):
    """Explore Fibonacci primes up to a limit."""
    title = "Fibonacci Primes"
    subtitle = f"Up to {limit}"
    body = "Fibonacci numbers that are also prime:\n"
    for n in fibonacci_primes(limit):
        body += f"  {n}\n"
    return (title, subtitle, body)

def explore_prime_gaps(low, high):
    """Explore gaps between successive primes."""
    title = "Prime Gaps"
    subtitle = f"Between {low} and {high}"
    min_gap, max_gap = prime_gap_stats(low, high)
    body = f"Smallest gap: {min_gap}, Largest gap: {max_gap}\n"
    return (title, subtitle, body)

# ----------------------------------------------------------------------
# 5. MAIN EXECUTION
# ----------------------------------------------------------------------
def main():
    """Run all explorations and print results."""
    clear_screen()
    print(centered(THEME_ANIMAL, BLOCK_WIDTH))
    print(centered(THEME_COLOR, BLOCK_WIDTH))
    print()

    blocks = [
        explore_primes(RANGE_END),
        explore_perfect_numbers(RANGE_END),
        explore_abundant_numbers(RANGE_END),
        explore_palindromic_primes(1, RANGE_END),
        explore_fibonacci_primes(RANGE_END),
        explore_prime_gaps(1, RANGE_END),
    ]

    for title, subtitle, body in blocks:
        fmt_block(title, subtitle, body)

if __name__ == "__main__":
    main()