# Generated by Cognia | 2026-08-11T13:02:03.843136
# Category: text similarity analyzer with sample texts
# Score: auto-asignado 7.8/10 (SIN VERIFICAR)
# Origin: predefined category

from functools import lru_cache
from math import sqrt

# --- Color palette ---
RED = "\033[31m"
GREEN = "\033[32m"
BLUE = "\033[34m"
YELLOW = "\033[33m"
WHITE = "\033[37m"
RESET = "\033[0m"
BOLD = "\033[1m"

# --- Sample texts ---
SAMPLE_TEXTS = [
    "The quick brown fox",
    "A clever cat",
    "Python is fun",
    "The fox runs fast",
]

# --- Edit distance (dynamic programming) ---
def edit_distance(s1: str, s2: str) -> int:
    m, n = len(s1), len(s2)
    # dp[i][j] = distance between s1[:i] and s2[:j]
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    for i in range(m + 1):
        dp[i][0] = i
    for j in range(n + 1):
        dp[0][j] = j
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if s1[i - 1] == s2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = 1 + min(dp[i - 1][j],
                                   dp[i][j - 1],
                                   dp[i - 1][j - 1])
    return dp[m][n]

# --- Similarity score (normalized 0–1) ---
def similarity(a: str, b: str) -> float:
    d = edit_distance(a, b)
    length = max(len(a), len(b))
    return 1 - d / length if length > 0 else 1.0

# --- Z‑score of similarities ---
def z_score(similarities: list[float]) -> float:
    n = len(similarities)
    mean = sum(similarities) / n
    std = sqrt(sum((x - mean) ** 2 for x in similarities) / n)
    return (mean - 1) / std if std > 0 else 0.0

# --- Print a nicely formatted report ---
def print_report(sims: list[float]) -> None:
    # Header
    print(f"{BOLD}{YELLOW}=== Text Similarity Report ==={RESET}")
    print(f"{BOLD}{BLUE}{'Index':<6}{BLUE}{'Text':<20}{BLUE}{'Sim':<10}{BLUE}{'Rating':<12}{BLUE}{'Self‑Match'}{RESET}")
    # Row numbers (0‑based)
    for i, (text, sc) in enumerate(zip(SAMPLE_TEXTS, sims)):
        # Determine rating
        if sc >= 1.0: r = "EXACT"
        elif sc >= 0.95: r = "NEAR"
        elif sc >= 0.80: r = "SIMILAR"
        elif sc >= 0.60: r = "MATCHY"
        elif sc >= 0.40: r = "OK"
        elif sc >= 0.20: r = "LOOSE"
        else: r = "DIFF"
        self_match = similarity(text, text)
        print(f"{BOLD}{BLUE}{i:<6}{BLUE}{text:<20}{BLUE}{sc:<10.3f}{BLUE}{r:<12}{BLUE}{self_match}{RESET}")
    # Footer
    print(f"{BOLD}{GREEN}---{RESET}")

# --- Verification: does self‑similarity equal 1.0? ---
def verify() -> bool:
    for t in SAMPLE_TEXTS:
        if similarity(t, t) != 1.0:
            return False
    return True

# --- Main program (no input) ---
def main() -> None:
    # Clear terminal
    print('\033[2J\033[H', end='')
    # ASCII art title
    title = """
   .--.   .--.   .--.
  /   \\ /   \\ /   \\
  |   | |   | |   |
  \\   / \\   / \\   /
   '--'   '--'   '--'
"""
    print(title)
    # Compute all pairwise similarities (including self)
    sims = []
    for text in SAMPLE_TEXTS:
        sc = similarity(text, text)
        sims.append(sc)
    # Compute Z‑score of the self‑similarities
    z = z_score(sims)
    # Run verification
    v = verify()
    # Print report
    print_report(sims)
    # Summary line
    print(f"{BOLD}{BLUE}Z‑score of self‑similarities: {z:.3f}{RESET}")
    # Final footer
    print("\n")
    # End of main
if __name__ == "__main__":
    main()