# Generated by Cognia | 2026-08-17T22:02:30.804385
# Category: Virtual pet health monitor that simulates daily activities and health stats
# Score: auto-asignado 8.3/10 (SIN VERIFICAR)
# Origin: self-proposed idea

import random
import time

# Constants
PET_NAME = "Buddy"
MAX_HUNGER = 100
MAX_THIRST = 100
MAX_HAPPINESS = 100
MAX_HEALTH = 100
HUNGER_DECREASE = 10
THIRST_DECREASE = 10
HAPPINESS_INCREASE = 5
HEALTH_INCREASE = 5
ACTIVITIES = ["play", "sleep", "eat", "drink"]
DAYS = 7

# Initial stats
hunger = MAX_HUNGER
thirst = MAX_THIRST
happiness = MAX_HAPPINESS
health = MAX_HEALTH

def clear_terminal():
    print('\033[2J\033[H', end='')

def print_stats():
    print(f"{PET_NAME}'s Current Stats:")
    print(f"Hunger: {hunger}/{MAX_HUNGER}")
    print(f"Thirst: {thirst}/{MAX_THIRST}")
    print(f"Happiness: {happiness}/{MAX_HAPPINESS}")
    print(f"Health: {health}/{MAX_HEALTH}")
    print("-" * 30)

def simulate_day():
    global hunger, thirst, happiness, health
    print(f"Day {day + 1}:")
    for activity in ACTIVITIES:
        if activity == "play":
            print(f"{PET_NAME} is playing.")
            happiness += HAPPINESS_INCREASE
            health += HEALTH_INCREASE
        elif activity == "sleep":
            print(f"{PET_NAME} is sleeping.")
            happiness += HAPPINESS_INCREASE
            hunger -= HUNGER_DECREASE
            thirst -= THIRST_DECREASE
        elif activity == "eat":
            print(f"{PET_NAME} is eating.")
            hunger -= HUNGER_DECREASE
        elif activity == "drink":
            print(f"{PET_NAME} is drinking.")
            thirst -= THIRST_DECREASE

    # Ensure stats don't exceed maximum
    hunger = min(hunger, MAX_HUNGER)
    thirst = min(thirst, MAX_THIRST)
    happiness = min(happiness, MAX_HAPPINESS)
    health = min(health, MAX_HEALTH)

    print_stats()

# Main loop
for day in range(DAYS):
    clear_terminal()
    print(f"Welcome to {PET_NAME}'s Pet Health Monitor!")
    print_stats()
    simulate_day()
    time.sleep(2)  # Pause for a moment to simulate time passing

print(f"{PET_NAME}'s health journey over {DAYS} days is complete.")