# Generated by Cognia | 2026-04-05T21:47:44.182521
# Category: text-based strategy game
# Score: 8.4/10

import time
import random

print('\033[2J\033[H', end='')

def clear_screen():
    print('\033[2J\033[H', end='')

def get_user_input(prompt):
    return input(prompt).split(',')

def generate_resources(start_amount, growth_rate):
    resources = {'Food': start_amount, 'Water': start_amount}
    for _ in range(random.randint(1, 3)):
        resource, amount = random.choice(list(resources.items()))
        resources[resource] += int(amount * growth_rate)
    return resources

def update_serotonin(resources):
    serotonin = sum(value / 10 for value in resources.values())
    return round(serotonin)

def print_resources(resources):
    print(f"Food: {resources['Food']}, Water: {resources['Water']}")

def main():
    clear_screen()
    print("Welcome to Decent Dilemma!")
    start_amount_food = 100
    growth_rate_food = 0.2

    start_amount_water = 50
    growth_rate_water = 0.1

    resources = generate_resources(start_amount_food, growth_rate_food)
    serotonin = update_serotonin(resources)

    while True:
        clear_screen()
        print(f"Serotonin: {serotonin}")
        print("Options:")
        print("1. Harvest food")
        print("2. Collect water")
        print("3. Check resources")

        option = input("Choose an action: ")
        if option == "1":
            resources['Food'] += 10
            serotonin = update_serotonin(resources)
        elif option == "2":
            resources['Water'] += 5
            serotonin = update_serotonin(resources)
        elif option == "3":
            print_resources(resources)
            time.sleep(0.5)
        else:
            print("Invalid action!")

        if serotonin > 50:
            print("You have achieved a perfect serotonin level!")
            break

main()