# Generated by Cognia | 2026-08-02T00:46:04.783837
# Category: 1. Identify the core constraints:
# Score: auto-asignado 6.3/10 (SIN VERIFICAR)
# Origin: self-proposed idea

#!/usr/bin/env python3
"""
Cosmic Census — a starfield simulation that inspects its own code
while running, proving it can juggle animation with meta-analysis.
Built entirely from Python's standard library — no external dependencies!
"""

# =============================================================================
# SECTION 1: IMPORTS (all must be from builtins)
# =============================================================================
import random as rnd
from math import ceil
from sys import stdout, version_info
from time import perf_counter, sleep

# =============================================================================
# SECTION 2: CONSTANTS & CONFIGURATION
# =============================================================================
MAX_STARS = 100
SCREEN_WIDTH = 80
FRAME_DELAY = 0.035          # ~30 fps — quick but readable
ANIMATION_FRAMES = 40        # How many frames to cycle through

# A tiny palette of ASCII characters for star variety
STAR_SHAPES = ['•', 'o', '.', '*', '+']

# Self-reference: the module name we're inspecting
MODULE_NAME = __name__
CODE_FILE = __file__.split('/')[-1] if __file__ else MODULE_NAME

# =============================================================================
# SECTION 3: HELPER FUNCTIONS (pure, no blocking)
# =============================================================================
def draw_header(title: str) -> None:
    """Print a nice centered header."""
    border = '═' * SCREEN_WIDTH
    print(border, end='')
    print()
    stars = rnd.choice(STAR_SHAPES)
    banner = f" {stars} {'COSMIC CENSUS'.center(SCREEN_WIDTH - 2)} {stars}"
    print(banner.center(SCREEN_WIDTH))
    subtitle = f" ({title})"
    print(subtitle.rjust(SCREEN_WIDTH), end='')
    print()
    print(border, end='')
    print()

def draw_starfield(stars: list[tuple[int, int]]) -> None:
    """Render a single frame of the starfield to stdout."""
    for y in range(len(stars)):
        line = ''
        for x in range(SCREEN_WIDTH):
            if 0 <= y < len(stars) and stars[y][0] == x:
                line += rnd.choice(STAR_SHAPES)
            else:
                line += ' '
        print(line, end='')
    print()

def clear_terminal() -> None:
    """Clear the screen using ANSI escape codes (no os.system!)."""
    # 2J clears all lines; H moves to top-left
    print('\033[2J\033[H', end='')

def run_inspection(name: str, func) -> None:
    """Run a self-inspecting function and print the result."""
    stdout.write(f'\033[1m┌─ {name} ──\033[0m\n')
    result = func()
    stdout.write(f'{result}\n')
    stdout.write('\033[1m└───────────────\033[0m\n')
    return stdout  # so .flush() works

def count_functions_in_module() -> str:
    """Count how many top-level functions are defined here."""
    funcs = [f for f in dir() if callable(eval(f)) and not f.startswith('_')]
    return f'FUNCTIONS DEFINED: {len(funcs)}\n  (we just counted ourselves!)'

def verify_line_count_under_limit() -> str:
    """Check that our code is under the 400-line max."""
    lines = sum(1 for _ in open(CODE_FILE, 'r', errors='replace'))
    verdict = 'PASS ✓' if lines <= 400 else f'FAIL ✗ (got {lines})'
    return f'MAX LINE COUNT: 400\nACTUAL LINES: {lines}\nVERDICT: {verdict}'

def compute_elapsed_time() -> str:
    """Show how long the program has been running."""
    start = perf_counter()
    sleep(1.2)              # Let it breathe — non-blocking pause
    elapsed = round(perf_counter() - start, 3)
    return f'ELAPSED TIME: {elapsed} seconds\n  (with a deliberate nap)'

def starfield_stats() -> str:
    """Report on the starfield itself."""
    total_stars = sum(len(starfield) for starfield in all_starfields())
    avg_y = round(sum(s[1] for s in all_starfields()) / max(1, total_stars), 2)
    return f'STARS TOTAL: {total_stars}\n  (spread across y ≈ {avg_y})'

# =============================================================================
# SECTION 4: DATA GENERATION (self-created sample data)
# ==================================================