# Generated by Cognia | 2026-07-20T00:12:05.675629
# Category: gestor de tareas con SQLite en memoria, pila de deshacer y tests unitarios que se ejecutan solos
# Score: 6.7/10
# Origin: predefined category

import sqlite3
import unittest

class TaskManager:
    def __init__(self):
        self.conn = sqlite3.connect(':memory:')
        self.conn.execute('CREATE TABLE tasks (id INTEGER PRIMARY KEY, description TEXT)')
        self.undo_stack = []

    def add_task(self, description):
        self.conn.execute('INSERT INTO tasks (description) VALUES (?)', (description,))
        self.undo_stack.append(('add', description))
        self.conn.commit()

    def delete_task(self, task_id):
        task = self.conn.execute('SELECT description FROM tasks WHERE id = ?', (task_id,)).fetchone()
        if task:
            self.conn.execute('DELETE FROM tasks WHERE id = ?', (task_id,))
            self.undo_stack.append(('delete', task_id, task[0]))
            self.conn.commit()

    def undo(self):
        if self.undo_stack:
            action, *args = self.undo_stack.pop()
            if action == 'add':
                self.delete_task(args[0])
            elif action == 'delete':
                self.add_task(args[1])

    def get_tasks(self):
        return self.conn.execute('SELECT * FROM tasks').fetchall()

class TestTaskManager(unittest.TestCase):
    def setUp(self):
        self.tm = TaskManager()

    def test_add_task(self):
        self.tm.add_task('Task 1')
        tasks = self.tm.get_tasks()
        self.assertEqual(len(tasks), 1)
        self.assertEqual(tasks[0][1], 'Task 1')

    def test_delete_task(self):
        self.tm.add_task('Task 1')
        task_id = self.tm.get_tasks()[0][0]
        self.tm.delete_task(task_id)
        tasks = self.tm.get_tasks()
        self.assertEqual(len(tasks), 0)

    def test_undo_add(self):
        self.tm.add_task('Task 1')
        self.tm.undo()
        tasks = self.tm.get_tasks()
        self.assertEqual(len(tasks), 0)

    def test_undo_delete(self):
        self.tm.add_task('Task 1')
        task_id = self.tm.get_tasks()[0][0]
        self.tm.delete_task(task_id)
        self.tm.undo()
        tasks = self.tm.get_tasks()
        self.assertEqual(len(tasks), 1)
        self.assertEqual(tasks[0][1], 'Task 1')

if __name__ == '__main__':
    print('\033[2J\033[H', end='')  # Clear terminal

    # Run demo
    tm = TaskManager()
    tm.add_task('Task 1')
    tm.add_task('Task 2')
    print("Tasks after adding 2 tasks:")
    for task in tm.get_tasks():
        print(task)

    tm.delete_task(1)
    print("\nTasks after deleting task 1:")
    for task in tm.get_tasks():
        print(task)

    tm.undo()
    print("\nTasks after undoing last action:")
    for task in tm.get_tasks():
        print(task)

    # Run tests
    print("\nRunning tests...")
    unittest.main(argv=[''], exit=False)