# Generated by Cognia | 2026-08-26T15:27:09.376756
# Category: text similarity analyzer with sample texts
# Score: auto-asignado 9.0/10 (SIN VERIFICAR)
# Origin: predefined category

import re
import math
from collections import Counter

BOLD = "1"
DIM = "2"
CYAN = "96"
GREEN = "92"
RED = "91"
YELLOW = "93"
BLUE = "94"
MAGENTA = "95"


def color(code, text):
    return f"\033[{code}m{text}\033[0m"


def banner():
    art = (
        "   /\   /\n"
        "  ( o) ( o)\n"
        "   \\_ \\_ \n"
        "  /|\\  |\\ \n"
        "   |      |\n"
        "   |______|\n"
    )
    print(color(CYAN, art))
    print(color(BOLD, "   " + "ANIMAL PYTHON TEXT SIMILARITY ZOO"))
    print(color(DIM, "   " + "knowledge_python + animal themes + automatic analysis"))


STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "been", "but", "by",
    "do", "for", "from", "has", "have", "in", "is", "it", "its", "of",
    "on", "or", "our", "that", "the", "their", "they", "this", "to",
    "was", "we", "were", "with"
}


def tokenize(text):
    words = re.findall(r"[a-z]+", text.lower())
    return [word for word in words if word not in STOPWORDS and len(word) > 1]


def make_features(tokens):
    bigrams = []
    for i in range(max(0, len(tokens) - 1)):
        bigrams.append(tokens[i] + " " + tokens[i + 1])
    return Counter(tokens + bigrams)


def jaccard(counter_a, counter_b):
    if not counter_a or not counter_b:
        return 0.0
    intersection = sum((counter_a & counter_b).values())
    union = sum((counter_a | counter_b).values())
    return intersection / union if union else 0.0


def cosine(counter_a, counter_b):
    if not counter_a or not counter_b:
        return 0.0
    dot = sum(counter_a[key] * counter_b[key] for key in counter_a if key in counter_b)
    norm_a = math.sqrt(sum(value * value for value in counter_a.values()))
    norm_b = math.sqrt(sum(value * value for value in counter_b.values()))
    return dot / (norm_a * norm_b) if norm_a and norm_b else 0.0


SAMPLE_TEXTS = {
    "PY-ALPHA": "Python language uses clear syntax for simple code.",
    "PY-BETA": "Python syntax is clear and simple for readable code.",
    "CAT-ALPHA": "Cats are curious animals with soft fur, whiskers, and gentle meows.",
    "DOG-BETA": "Dogs are loyal animals that wag tails and love playing outside.",
    "ML-GAMMA": "Text similarity measures shared words and phrases between documents."
}


def main():
    banner()
    print(color(BOLD, "Sample texts (built-in):"))
    print(color(DIM, " " + "-" * 72))
    for doc, text in SAMPLE_TEXTS.items():
        label = f"{doc:9}"
        print(f" {color(YELLOW, label)}  {text}")
    print(color(DIM, " " + "-" * 72))

    tokens_by_doc = {doc: tokenize(text) for doc, text in SAMPLE_TEXTS.items()}
    features_by_doc = {doc: make_features(tokens_by_doc[doc]) for doc in SAMPLE_TEXTS}

    print(color(BOLD, "Counts:"))
    total_tokens = 0
    for doc in SAMPLE_TEXTS:
        tokens = tokens_by_doc[doc]
        total_tokens += len(tokens)
        print(
            f" {doc:9} tokens={len(tokens):3} "
            f"unique={len(set(tokens)):3} feature_occ={sum(features_by_doc[doc].values()):3}"
        )

    all_tokens = set()
    all_features = set()
    for tokens in tokens_by_doc.values():
        all_tokens.update(tokens)
    for counter in features_by_doc.values():
        all_features.update(counter.keys())

    print(
        f" {'TOTAL':9} tokens={total_tokens:3} "
        f"unique_tokens={len(all_tokens):3} unique_features={len(all_features):3}"
    )
    print(color(DIM, " " + "-" * 72))

    print(color(BOLD, "Pair similarity results (unigram + bigram features):"))
    ids = list(SAMPLE_TEXTS)
    pair_results = []
    for i in range(len(ids)):
        for j in range(i + 1, len(ids)):
            doc_a, doc_b = ids[i], ids[j]
            j_score = jaccard(features_by_doc[doc_a], features_by_doc[doc_b])
            c_score = cosine(features_by_doc[doc_a], features_by_doc[doc_b])
            pair_results.append((doc_a, doc_b, j_score, c_score))

    pair_results.sort(key=lambda item: item[3], reverse=True)

    for rank, (doc_a, doc_b, j_score, c_score) in enumerate(pair_results, 1):
        if c_score >= 0.5:
            line_color = GREEN
        elif c_score >= 0.1:
            line_color = YELLOW
        else:
            line_color = DIM
        line = f" {rank:2}. {doc_a:9} vs {doc_b:9} J={j_score:.3f} C={c_score:.3f}"
        print(color(line_color, line))
    print(color(DIM, " " + "-" * 72))

    print(color(BOLD, "Verification checks:"))
    checks = []

    def verify(name, condition, detail):
        status = color(GREEN, "PASS") if condition else color(RED, "FAIL")
        print(f" [{status}] {name}: {detail}")
        checks.append(bool(condition))

    verify("Sample texts loaded", len(SAMPLE_TEXTS) == 5, f"count={len(SAMPLE_TEXTS)}")
    verify(
        "Every document has tokens",
        all(len(tokens_by_doc[doc]) > 0 for doc in SAMPLE_TEXTS),
        f"min_tokens={min(len(tokens_by_doc[doc]) for doc in SAMPLE_TEXTS)}"
    )
    verify(
        "Stopwords removed",
        all(not (set(tokens_by_doc[doc]) & STOPWORDS) for doc in SAMPLE_TEXTS),
        "no stopword tokens remain"
    )

    expected_feature_occ = {
        doc: len(tokens_by_doc[doc]) + max(0, len(tokens_by_doc[doc]) - 1)
        for doc in SAMPLE_TEXTS
    }

    verify(
        "Feature counts = tokens + bigrams",
        all(sum(features_by_doc[doc].values()) == expected_feature_occ[doc] for doc in SAMPLE_TEXTS),
        f"total_feature_occ={sum(sum(counter.values()) for counter in features_by_doc.values())}"
    )

    self_j_ok = all(
        abs(jaccard(features_by_doc[doc], features_by_doc[doc]) - 1.0) < 1e-12
        for doc in SAMPLE_TEXTS
    )
    self_c_ok = all(
        abs(cosine(features_by_doc[doc], features_by_doc[doc]) - 1.0) < 1e-12
        for doc in SAMPLE_TEXTS
    )
    verify("Self Jaccard = 1.0", self_j_ok, "checked all 5 documents")
    verify("Self cosine = 1.0", self_c_ok, "checked all 5 documents")

    all_sims = [x[2] for x in pair_results] + [x[3] for x in pair_results]
    verify(
        "Similarities within [0,1]",
        all(0.0 <= sim <= 1.0 for sim in all_sims),
        f"min={min(all_sims):.3f} max={max(all_sims):.3f}"
    )

    pair_map = {(a, b): (j, c) for a, b, j, c in pair_results}
    py_cos = pair_map[("PY-ALPHA", "PY-BETA")][1]
    animal_cos = pair_map[("CAT-ALPHA", "DOG-BETA")][1]

    verify(
        "Python pair more similar than animal pair",
        py_cos > animal_cos,
        f"PY={py_cos:.3f} CAT-DOG={animal_cos:.3f}"
    )

    verify(
        "Top pair is Python pair",
        pair_results[0][0] == "PY-ALPHA" and pair_results[0][1] == "PY-BETA",
        f"top={pair_results[0][0]} vs {pair_results[0][1]}"
    )

    sorted_ok = all(
        pair_results[i][3] >= pair_results[i + 1][3]
        for i in range(len(pair_results) - 1)
    )
    verify("Pair list sorted by cosine", sorted_ok, f"pairs={len(pair_results)}")

    passed = sum(checks)
    total = len(checks)
    print(color(DIM, " " + "-" * 72))
    if passed == total:
        verdict = color(GREEN, "ALL VERIFICATIONS PASSED")
    else:
        verdict = color(RED, f"{total - passed} CHECKS FAILED")

    print(color(BOLD, f"VERDICT: {passed}/{total} passed - {verdict}"))
    print(color(BLUE, "Analysis complete. Program ran automatically with no input."))


if __name__ == "__main__":
    main()