# Generated by Cognia | 2026-08-29T20:20:01.747627
# Category: text similarity analyzer with sample texts
# Score: auto-asignado 8.9/10 (SIN VERIFICAR)
# Origin: predefined category

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ZooLex — a text similarity analyzer with sample texts.

Analyzes five short texts (animals + Python theme) with three
algorithms: Jaccard set overlap, cosine word-vector similarity and
Levenshtein edit distance. Prints matrices, bars and PASS/FAIL
verifications. Standard library only, fully automatic.
"""

import math
import random
import re

# --------------------------------------------------------------- ANSI colors
C = {k: f'\033[{v}m' for k, v in {
    'B': 1, 'R': 0, 'G': 32, 'RD': 31, 'Y': 33,
    'CY': 36, 'M': 35, 'BL': 34, 'Gy': 90}.items()}

def paint(code, s):
    return C[code] + str(s) + C['R']

# ---------------------------------------------------------- sample corpus
TEXTS = {
    'reptA': 'The python snake is a scaly reptile. It slithers on the ground '
             'and hunts with a venomous bite.',
    'reptB': 'The cobra snake is a venomous reptile. It strikes its prey with '
             'a deadly bite and hides in the grass.',
    'petCt': 'The cat purrs softly on the sofa. It grooms its fur with a rough '
             'tongue and is a gentle indoor pet.',
    'codeP': 'In the Python programming language a loop repeats a block of code '
             'and a function defines reusable behavior.',
    'charM': 'The snake charmer plays a flute in the desert and the cobra '
             'slowly sways to the tune in the heat.',
}
NAMES = list(TEXTS)
QUERY = 'a venomous reptile strikes its prey with a deadly bite'

# ------------------------------------------------------------------ tokenizer
def tokenize(text):
    return re.findall(r'[a-z]+', text.lower())

def word_counts(text):
    counts = {}
    for w in tokenize(text):
        counts[w] = counts.get(w, 0) + 1
    return counts

# ------------------------------------------------------------------- metrics
def jaccard(a, b):
    sa, sb = set(tokenize(a)), set(tokenize(b))
    if not (sa and sb):
        return 0.0
    return len(sa & sb) / len(sa | sb)

def cosine(a, b):
    va, vb = word_counts(a), word_counts(b)
    dot = sum(va.get(k, 0) * vb.get(k, 0) for k in va)
    na = math.sqrt(sum(v * v for v in va.values()))
    nb = math.sqrt(sum(v * v for v in vb.values()))
    return dot / (na * nb) if na and nb else 0.0

def levenshtein(a, b):
    if not a:
        return len(b)
    if not b:
        return len(a)
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cost = 0 if ca == cb else 1
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + cost))
        prev = cur
    return prev[-1]

# ------------------------------------------------------------------- display
def bar(score, width=22):
    filled = max(0, min(width, int(round(score * width))))
    return paint('G', '#' * filled) + paint('Gy', '.' * (width - filled))

def heat(score):
    if score >= 0.70:
        return paint('G', f'{score:5.2f}')
    if score >= 0.40:
        return paint('Y', f'{score:5.2f}')
    return paint('Gy', f'{score:5.2f}')

def build_matrix(mode):
    return [[mode(TEXTS[n1], TEXTS[n2]) for n2 in NAMES] for n1 in NAMES]

def print_matrix(m, title):
    print()
    print(paint('CY', '  ' + title))
    print(paint('CY', '  ' + '─' * 44))
    print('  ' + ' ' * 8 + ' '.join(paint('B', n) for n in NAMES))
    for i, name in enumerate(NAMES):
        cells = [heat(m[i][j]) if j != i else paint('B', ' 1.00')
                 for j in range(len(NAMES))]
        print('  ' + paint('B', name.ljust(8)) + ' '.join(cells))

# ---------------------------------------------------------- random generator
THEME_WORDS = ['snake', 'cobra', 'reptile', 'venom', 'bite',
               'grass', 'desert', 'prey', 'hunts', 'scales']

def gen_sentence(rng):
    w = rng.sample(THEME_WORDS, 4)
    return (f'The {w[0]} near the {w[1]} shows {w[2]} '
            f'after the {w[3]} moves at dusk.')

# --------------------------------------------------------------------- main
def main():
    print('\033[2J\033[H', end='')
    checks = []

    def check(name, ok, extra=''):
        checks.append(bool(ok))
        mark = paint('G', 'PASS') if ok else paint('RD', 'FAIL')
        print(f'  [{mark}] {name}  {extra}')

    print(paint('BL', '+=' + '=' * 64 + '+'))
    print(paint('BL', '| ' +
        'Z O O L E X  ·  T E X T   S I M I L A R I T Y   A N A L Y Z E R'.center(64) +
        ' |'))
    print(paint('BL', '+=' + '=' * 64 + '+'))
    print('    ' + paint('BL', r' /\_/\   ( o.o )   > ^ <   ~ss~  #'))
    print(paint('Gy', '    animals + Python theme · 3 similarity algorithms · self-verifying'))

    # [1] corpus census
    print(paint('M', '\n[1] SAMPLE CORPUS — token census'))
    print(paint('M', '  ' + '─' * 64))
    total = 0
    for name in NAMES:
        toks = tokenize(TEXTS[name])
        total += len(toks)
        print(f'  {paint("B", name.ljust(7))} tokens={len(toks):>3} '
              f'unique={len(set(toks)):>3}  "{TEXTS[name]}"')
    npairs = len(NAMES) * (len(NAMES) - 1) // 2
    print(paint('Gy', f'  → {total} tokens across {len(NAMES)} texts · '
              f'{npairs} unique pairs to compare'))

    # [2] cosine matrix
    cos_m = build_matrix(cosine)
    print_matrix(cos_m, '[2] COSINE SIMILARITY MATRIX (bag-of-words vectors)')
    best, worst = (-1.0, None, None), (2.0, None, None)
    for i in range(len(NAMES)):
        for j in range(i + 1, len(NAMES)):
            v = cos_m[i][j]
            if v > best[0]:
                best = (v, NAMES[i], NAMES[j])
            if v < worst[0]:
                worst = (v, NAMES[i], NAMES[j])
    print(f'  {paint("G","most similar"):>15}: {best[1]} × {best[2]}'
          f'  {bar(best[0])}  {best[0]:.3f}')
    print(f'  {paint("RD","least similar"):>15}: {worst[1]} × {worst[2]}'
          f'  {bar(worst[0])}  {worst[0]:.3f}')

    # [3] jaccard matrix
    jac_m = build_matrix(jaccard)
    print_matrix(jac_m, '[3] JACCARD SET-OVERLAP MATRIX (unique words only)')

    # [4] levenshtein demo
    print(paint('M', '\n[4] LEVENSHTEIN EDIT DISTANCE — word-level demo'))
    for a, b in [('cobra', 'cobra'), ('cobra', 'cat'), ('kitten', 'sitting'),
                 ('python', 'serpent'), ('python', 'python')]:
        d = levenshtein(a, b)
        sim = 1.0 - d / max(len(a), len(b))
        print(f'  lev("{a}", "{b}") = {d:>2}   similarity = {sim:.2f}  {bar(sim)}')

    # [5] query detection
    print(paint('M', '\n[5] QUERY DETECTION — which sample text matches this snippet?'))
    print(f'  query: {paint("CY", QUERY)}')
    scores = sorted(((name, cosine(QUERY, TEXTS[name])) for name in NAMES),
                    key=lambda t: -t[1])
    for rank, (name, v) in enumerate(scores, 1):
        tag = paint('G', '◄ best match') if rank == 1 else ''
        print(f'  {rank}. {paint("B", name.ljust(7))} {bar(v)}  {v:.3f}  {tag}')

    # [6] verification suite
    print(paint('M', '\n[6] VERIFICATION SUITE — comparing computed values, not just printing them'))
    print(paint('M', '  ' + '─' * 64))
    n = len(NAMES)
    check('cosine diagonal == 1.00 (5 texts)',
          all(abs(cos_m[i][i] - 1.0) < 1e-9 for i in range(n)))
    check('cosine matrix symmetric (20 directed pairs)',
          all(abs(cos_m[i][j] - cos_m[j][i]) < 1e-9
              for i in range(n) for j in range(n)))
    va, vb = (cosine(TEXTS['reptA'], TEXTS['reptB']),
              cosine(TEXTS['reptA'], TEXTS['codeP']))
    check('theme affinity: two reptile texts > reptile vs code text',
          va > vb, f'(A-B={va:.3f}  A-code={vb:.3f})')
    check('jaccard self-similarity == 1.00',
          abs(jaccard(TEXTS['petCt'], TEXTS['petCt']) - 1.0) < 1e-9)
    check('jaccard symmetric  j(A,B) == j(B,A)',
          abs(jac_m[0][3] - jac_m[3][0]) < 1e-9,
          f'({jac_m[0][3]:.3f} vs {jac_m[3][0]:.3f})')
    check('lev("cobra","cobra") == 0', levenshtein('cobra', 'cobra') == 0)
    check('lev("kitten","sitting") == 3 (classic test case)',
          levenshtein('kitten', 'sitting') == 3)
    d_ab, d_bc, d_ac = (levenshtein('kitten', 'sitting'),
                        levenshtein('sitting', 'python'),
                        levenshtein('kitten', 'python'))
    check('triangle inequality  d(k,p) <= d(k,s)+d(s,p)',
          d_ac <= d_ab + d_bc, f'({d_ac} <= {d_ab}+{d_bc})')
    check('query ranks reptB #1', scores[0][0] == 'reptB',
          f'(score {scores[0][1]:.3f})')

    rng = random.Random(42)
    gen = [gen_sentence(rng) for _ in range(3)]
    print(paint('Gy', '\n  random generator (seed=42) — 3 fresh animal sentences:'))
    for s in gen:
        print('    · ' + paint('Gy', s))
    check('random animal sentences score higher vs reptB than vs codeP',
          all(cosine(s, TEXTS['reptB']) > cosine(s, TEXTS['codeP']) for s in gen))
    check('all 3 generated sentences are distinct', len(set(gen)) == 3)

    passed = sum(checks)
    print('\n' + paint('M', '  ' + '═' * 64))
    if passed == len(checks):
        print(paint('G', f'  ✔ VERDICT: {passed}/{len(checks)} checks passed — analyzer VERIFIED'))
    else:
        print(paint('RD', f'  ✘ VERDICT: {passed}/{len(checks)} checks passed — FAILURES DETECTED'))
    print(paint('Gy', f'  ZooLex session complete · {total} tokens · '
              f'{npairs} pairs · {len(checks)} checks'))

if __name__ == '__main__':
    main()