# Generated by Cognia | 2026-08-29T00:16:40.536056
# Category: text similarity analyzer with sample texts
# Score: auto-asignado 9.2/10 (SIN VERIFICAR)
# Origin: predefined category

# -*- coding: utf-8 -*-
"""
  TEXT SIMILARITY ANALYZER  --  owl edition
  Compares a small corpus of animal-themed texts (Python-learning flavor)
  with four dependency-free metrics, then verifies the math against
  known values (PASS/FAIL) and ranks a query's best match.
"""

import math
import re
from collections import Counter

RESET, BOLD, DIM = "\033[0m", "\033[1m", "\033[2m"
CYAN, MAGENTA = "\033[96m", "\033[95m"
GREEN, YELLOW, RED, WHITE = "\033[92m", "\033[93m", "\033[91m", "\033[97m"

CORPUS = {
    "BUHO1":     "El búho sabio aprende a programar en Python",
    "BUHO2":     "El búho estudia Python en el bosque nocturno",
    "BUHO3":     "En el bosque el búho nocturno analiza textos con Python",
    "GATO":      "El gato silvestre persigue mariposas en el jardín",
    "SERPIENTE": "La serpiente de cascabel no programa, pero Python lleva su nombre",
}
QUERY = "El búho lee libros de programación en Python"

OWL = (
    "   ,  ,\n"
    "  ( \\  / )\n"
    "  (  o  o )\n"
    "  (  -  - )\n"
    "   \\  ^  /\n"
    "    \\ __ /"
)

# ---------------------------------------------------------- NLP primitives ----

def normalize(text):
    return re.sub(r"[^a-záéíóúñ]+", " ", text.lower())

def tokens(text):
    return normalize(text).split()

def bag(text):
    return Counter(tokens(text))

def bigrams(text):
    t = tokens(text)
    return [f"{a} {b}" for a, b in zip(t, t[1:])]

# --------------------------------------------------------------- metrics ------

def jaccard(a, b):
    n = len(a | b)
    return 0.0 if n == 0 else len(a & b) / n

def cosine(a, b):
    dot = sum(a.get(k, 0) * b.get(k, 0) for k in a.keys() | b.keys())
    na = math.sqrt(sum(v * v for v in a.values()))
    nb = math.sqrt(sum(v * v for v in b.values()))
    return 0.0 if (na == 0 or nb == 0) else dot / (na * nb)

def levenshtein(a, b):
    if not a:
        return len(b)
    if not b:
        return len(a)
    row = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(row[j] + 1, cur[j - 1] + 1,
                            row[j - 1] + (ca != cb)))
        row = cur
    return row[-1]

def sim_edit(a, b):
    longest = max(len(a), len(b))
    return 1.0 if longest == 0 else 1.0 - levenshtein(a, b) / longest

def profile(a, b):
    return {
        "JAC": jaccard(set(tokens(a)), set(tokens(b))),
        "COS": cosine(bag(a), bag(b)),
        "SHG": jaccard(set(bigrams(a)), set(bigrams(b))),
        "EDI": sim_edit(normalize(a), normalize(b)),
    }

def composite(prof):
    return sum(prof.values()) / len(prof)

# ------------------------------------------------------------- display ---------

def bar(score, w=8):
    n = int(round(score * w))
    return "█" * n + "░" * (w - n)

def tint(score):
    return GREEN if score >= 0.6 else YELLOW if score >= 0.3 else RED

def cell(prof, key):
    v = prof[key]
    return f"{key} {v:4.2f} {tint(v)}{bar(v)}{RESET}"

def pair_rows():
    ids = list(CORPUS)
    rows = []
    for i in range(len(ids)):
        for j in range(i + 1, len(ids)):
            a, b = ids[i], ids[j]
            rows.append((a, b, profile(CORPUS[a], CORPUS[b])))
    return rows

def check_float(label, expected, got):
    ok = math.isclose(expected, got, abs_tol=1e-9)
    mark = f"{GREEN}PASS{RESET}" if ok else f"{RED}FAIL{RESET}"
    print(f"  {label:<46} {expected: .4f} {got: .4f}  {mark}")
    return ok

def check_bool(label, cond, detail):
    mark = f"{GREEN}PASS{RESET}" if cond else f"{RED}FAIL{RESET}"
    print(f"  {label:<46} {detail:<16}  {mark}")
    return bool(cond)

# ----------------------------------------------------------------- main --------

def main():
    print("\033[2J\033[H", end="")
    rows = pair_rows()
    all_scores = [v for _, _, p in rows for v in p.values()]

    print(f"{CYAN}{BOLD}{'=' * 74}{RESET}")
    print(f"{CYAN}{BOLD}   TEXT SIMILARITY ANALYZER  -  owl edition{RESET}")
    print(f"{CYAN}{BOLD}   {len(CORPUS)} sample texts · {len(rows)} pairs · 4 metrics{RESET}")
    print(f"{CYAN}{BOLD}{'=' * 74}{RESET}")
    print(f"  {MAGENTA}{OWL}{RESET}")

    # -- corpus with counts
    print(f"  {BOLD}SAMPLE CORPUS{RESET}  {DIM}(animal x Python-learning flavor){RESET}")
    print(f"  {DIM}{'-' * 70}{RESET}")
    tot_tok = tot_bg = 0
    for k, t in CORPUS.items():
        toks, bgs = tokens(t), bigrams(t)
        tot_tok += len(toks)
        tot_bg += len(bgs)
        print(f"  {YELLOW}[{k:<9}] {RESET}{t}   {DIM}({len(toks)} tok, {len(bgs)} bg){RESET}")
    print(f"  {DIM}counts: {tot_tok} tokens, {tot_bg} bigrams, "
          f"{sum(len(bag(t)) for t in CORPUS.values())} distinct words{RESET}")

    # -- pairwise table
    print(f"\n  {BOLD}PAIRWISE SIMILARITY{RESET}  "
          f"{DIM}JAC=Jaccard COS=cosine SHG=bigram-Jaccard EDI=edit-sim{RESET}")
    print(f"  {DIM}{'-' * 70}{RESET}")
    for a, b, prof in rows:
        print(f"  {WHITE}{a:<9} x {b:<9}{RESET}   "
              + "  ".join(cell(prof, k) for k in ("JAC", "COS")))
        print(" " * 26 + "  ".join(cell(prof, k) for k in ("SHG", "EDI")))

    best = max(rows, key=lambda r: composite(r[2]))
    worst = min(rows, key=lambda r: composite(r[2]))
    print(f"\n  MOST SIMILAR PAIR:  {WHITE}{best[0]} x {best[1]}{RESET}  "
          f"{GREEN}composite {composite(best[2]):.2f}{RESET}")
    print(f"  LEAST SIMILAR PAIR: {WHITE}{worst[0]} x {worst[1]}{RESET}  "
          f"{RED}composite {composite(worst[2]):.2f}{RESET}")

    # -- heatmap
    ids = list(CORPUS)
    grid = {a: {b: (1.0 if a == b else 0.0) for b in ids} for a in ids}
    for a, b, prof in rows:
        grid[a][b] = grid[b][a] = composite(prof)
    print(f"\n  {BOLD}COMPOSITE HEATMAP{RESET}  {DIM}(avg of 4 metrics, diagonal = self){RESET}")
    print(" " * 11 + "".join(f"{i:<9}" for i in ids))
    for a in ids:
        print(f"  {WHITE}{a:<9}{RESET}" + "".join(
            f"{tint(grid[a][b])}{grid[a][b]:9.2f}{RESET}" for b in ids))

    # -- best match
    print(f"\n  {BOLD}BEST MATCH{RESET}  {DIM}(query vs corpus, composite score){RESET}")
    print(f"  query: {WHITE}\"{QUERY}\"{RESET}  {DIM}({len(tokens(QUERY))} tokens){RESET}")
    ranked = sorted(((composite(profile(QUERY, t)), k) for k, t in CORPUS.items()),
                    reverse=True)
    medals = {1: YELLOW, 2: WHITE, 3: RED}
    for rank, (s, k) in enumerate(ranked, 1):
        print(f"  {medals.get(rank, DIM)}#{rank} {k:<9} {tint(s)}{s:.2f} "
              f"{bar(s, 10)}{RESET}  {DIM}{CORPUS[k]}{RESET}")

    # -- validation
    print(f"\n  {BOLD}VALIDATION SUITE{RESET}  {DIM}(known values + properties){RESET}")
    print(f"  {DIM}{'-' * 70}{RESET}")
    res = []
    t = CORPUS["BUHO1"]
    nt = normalize(t)
    res.append(check_float("jaccard(text, text) == 1.0", 1.0,
                           jaccard(set(tokens(t)), set(tokens(t)))))
    res.append(check_float("cosine(text, text) == 1.0", 1.0,
                           cosine(bag(t), bag(t))))
    res.append(check_float("levenshtein(text, text) == 0", 0.0,
                           float(levenshtein(nt, nt))))
    res.append(check_float("edit-sim(text, text) == 1.0", 1.0, sim_edit(nt, nt)))
    res.append(check_float("jaccard(disjoint sets) == 0.0", 0.0,
                           jaccard({"gato"}, {"bosque"})))
    res.append(check_float("cosine(disjoint bags) == 0.0", 0.0,
                           cosine({"gato": 1}, {"bosque": 1})))
    res.append(check_float("bigram-jaccard(disjoint) == 0.0", 0.0,
                           jaccard(set(bigrams("gato gato")),
                                   set(bigrams("bosque bosque")))))
    res.append(check_float('jaccard({"el","buho"},{"el","bosque"})', 1 / 3,
                           jaccard({"el", "buho"}, {"el", "bosque"})))
    res.append(check_float('levenshtein("kitten","sitting")', 3.0,
                           float(levenshtein("kitten", "sitting"))))
    res.append(check_float('levenshtein("","abc")', 3.0,
                           float(levenshtein("", "abc"))))
    res.append(check_float('levenshtein("flames","fire")', 3.0,
                           float(levenshtein("flames", "fire"))))
    max_diff = 0.0
    for a, b, _ in rows:
        pa, pb = profile(CORPUS[a], CORPUS[b]), profile(CORPUS[b], CORPUS[a])
        for key in pa:
            max_diff = max(max_diff, abs(pa[key] - pb[key]))
    res.append(check_float("symmetry |s(a,b)-s(b,a)|, 10 pairs", 0.0, max_diff))
    res.append(check_bool("all pairwise scores in [0,1]",
                          all(0.0 <= s <= 1.0 for s in all_scores),
                          f"min={min(all_scores):.3f} max={max(all_scores):.3f}"))
    passed = sum(res)
    verdict = GREEN if passed == len(res) else RED
    print(f"\n  {BOLD}VERDICT: {verdict}{passed}/{len(res)} CHECKS PASSED{RESET}")
    print(f"{CYAN}{BOLD}{'=' * 74}{RESET}")

if __name__ == "__main__":
    main()