# Generated by Cognia | 2026-08-13T00:42:51.712336
# Category: text similarity analyzer with sample texts
# Score: auto-asignado 7.2/10 (SIN VERIFICAR)
# Origin: predefined category

from itertools import combinations
from collections import Counter
import random

CLEAR = "\033[2J\033[H"
CYAN = "\033[36m"
MAGENTA = "\033[35m"
YELLOW = "\033[33m"
GREEN = "\033[32m"
RED = "\033[31m"
BOLD = "\033[1m"
RESET = "\033[0m"
COLORS = {"CYAN": CYAN, "MAGENTA": MAGENTA, "YELLOW": YELLOW, "GREEN": GREEN, "RED": RED, "BOLD": BOLD, "RESET": RESET}

ANIMALS = ["cat", "kitten", "purr", "feline", "tabby"]
WORDS = ["the", "quick", "brown", "fox", "jumps", "over", "lazy", "dog"]
SENTENCES = ["A feline purred loudly.", "The kitten jumps.", "Purr the cat.", "The fox runs.", "Dog cat."]
ALPHABET = "abcdefghijklmnopqrstuvwxyz"
random_words = ["".join(random.choices(ALPHABET, k=r)) for r in [5,7,8,6]]

def levenshtein(a, b):
    m, n = len(a), len(b)
    dp = [[0]*(n+1) for _ in range(m+1)]
    for i in range(m+1): dp[i][0] = i
    for j in range(n+1): dp[0][j] = j
    for i in range(1, m+1):
        for j in range(1, n+1):
            if a[i-1] == b[j-1]:
                dp[i][j] = min(dp[i-1][j] + 1, dp[i][j-1] + 1, dp[i-1][j-1])
            else:
                dp[i][j] = min(dp[i-1][j] + 1, dp[i][j-1] + 1, dp[i-1][j-1] + 1)
    return dp[m][n]

def charbag(s1, s2):
    c1, c2 = Counter(s1), Counter(s2)
    intersect = sum(min(c1[k], c2[k]) for k in c1)
    union = sum(c1[k] + c2[k] for k in c1 | c2) - intersect
    return intersect, union, intersect / union if union else 1.0

def wordbag(s1, s2):
    w1, w2 = Counter(s1.lower().split()), Counter(s2.lower().split())
    intersect = sum(min(w1[k], w2[k]) for k in w1)
    union = sum(w1[k] + w2[k] for k in w1 | w2) - intersect
    return intersect, union, intersect / union if union else 1.0

def similarity(s1, s2):
    d = levenshtein(s1, s2)
    max_len = max(len(s1), len(s2))
    dr = 1.0 - d / max_len if max_len else 1.0
    i, u, cr = charbag(s1, s2)
    iw, uw, wr = wordbag(s1, s2)
    return d, dr, i, cr, iw, wr

def run():
    # Border
    print(f"{COLORS['CYAN']}{'='*60}{COLORS['RESET']}")
    # Title
    print(f"{COLORS['CYAN']}{' TEXT SIMILARITY ANALYZER'.center(60)}")
    # Description
    print(f"{COLORS['BOLD']}{COLORS['CYAN']}Analyzing sample texts with Levenshtein & Char Bags")
    print(f"{COLORS['CYAN']}{'-'*60}{COLORS['RESET']}")
    # ASCII cat
    CAT = """
      /\_/\
     ( o.o )\
      > ^ <
"""
    print(f"{COLORS['CYAN']}{CAT}{COLORS['RESET']}")
    # Sample groups
    groups = [("ANIMALS", ANIMALS), ("WORDS", WORDS), ("SENTENCES", SENTENCES),
              ("RANDOM", random_words)]
    for name, data in groups:
        print(f"{COLORS['MAGENTA']}{name}{COLORS['RESET']}:")
        for s in data:
            print(f"  {COLORS['CYAN']}{s}{COLORS['RESET']}")
    # Pairwise results
    all_samples = ANIMALS + WORDS + SENTENCES + random_words
    print(f"{COLORS['CYAN']}{'Pairwise Comparisons (d = Levenshtein, c = char bag, w = word bag)'}{COLORS['RESET']}")
    results = []
    for s1, s2 in combinations(all_samples, 2):
        d, dr, ic, cr, iw, wr = similarity(s1, s2)
        ratio = dr
        if ratio >= 0.75: label = "PASS"
        elif ratio >= 0.55: label = "OK"
        else: label = "FAIL"
        results.append((s1, s2, d, dr, ic, cr, iw, wr, label))
    # Print each result
    for idx, (s1, s2, d, dr, ic, cr, iw, wr, label) in enumerate(results, 1):
        print(f"{COLORS['CYAN']}{idx}{COLORS['RESET']}: {COLORS['BOLD']}{s1}{COLORS['RESET']}")
        print(f"{COLORS['CYAN']}{'>'}{COLORS['RESET']}{COLORS['BOLD']}{s2}{COLORS['RESET']}")
        print(f"{COLORS['CYAN']}  d={COLORS['YELLOW']}{d}{COLORS['RESET']}  dr={COLORS['GREEN']}{dr:.3f}{COLORS['RESET']}")
        print(f"{COLORS['CYAN']}  c={COLORS['RED']}{cr:.3f}{COLORS['RESET']}  w={COLORS['RED']}{wr:.3f}{COLORS['RESET']}")
        print(f"{COLORS['CYAN']}  {label}{COLORS['RESET']}")
        print(f"{COLORS['CYAN']}{'─'*60}{COLORS['RESET']}")
    # Summary
    avg = sum(dr for _, _, _, dr, _, _, _, _, _ in results) / len(results)
    max_d = max(d for _, _, d, _, _, _, _, _, _ in results)
    max_dr = max(dr for _, _, _, dr, _, _, _, _, _ in results)