# Generated by Cognia | 2026-04-05T20:34:45.299769
# Category: cipher and encryption toy
# Score: 6.5/10

import string

def stem_encrypt(message, shift):
    stems = string.ascii_lowercase
    shifted_message = ""
    for char in message:
        if char.isalpha():
            index = (stems.index(char.lower()) + shift) % len(stems)
            if char.isupper():
                shifted_message += stems[index].upper()
            else:
                shifted_message += stems[index]
        else:
            shifted_message += char
    return shifted_message

def score(message, encrypted_message):
    correct_letters = sum(1 for i in range(len(message)) if message[i] == encrypted_message[i])
    return (correct_letters / len(message)) * 100

print('\033[2J\033[H', end='')
while True:
    print("Enter a message to encrypt:")
    user_message = input()
    shift = int(input("Enter the encryption shift: "))
    encrypted_message = stem_encrypt(user_message, shift)
    score_value = score(user_message, encrypted_message)
    print(f"Encrypted message: {encrypted_message}")
    print(f"Score: {score_value:.2f}%")
    response = input("Enter 'q' to quit: ")
    if response.lower() == 'q':
        break