# Generated by Cognia | 2026-08-02T00:14:56.786377
# Category: Automated pet feeder scheduler based on animal needs and feeding habits
# Score: auto-asignado 5.9/10 (SIN VERIFICAR)
# Origin: self-proposed idea

import datetime
import random
import time

# Constants
FEEDING_INTERVAL_HOURS = 8  # Hours between feedings
FEEDING_DURATION_MINUTES = 5  # Minutes the feeder runs
NUM_FEEDINGS = 3  # Number of feedings per day
PET_NAMES = ["Buddy", "Charlie", "Daisy"]
RANDOM_SEED = 42  # For reproducibility

# Sample data
class Pet:
    def __init__(self, name, feeding_time):
        self.name = name
        self.feeding_time = feeding_time

    def __repr__(self):
        return f"Pet(name={self.name}, feeding_time={self.feeding_time})"

# Generate sample pets with random feeding times
random.seed(RANDOM_SEED)
pets = [Pet(name, random.randint(0, 24)) for name in PET_NAMES]

# Function to check if it's time to feed a pet
def is_time_to_feed(current_hour, feeding_time):
    return current_hour == feeding_time

# Function to simulate feeding
def feed_pet(pet):
    print(f"Feeding {pet.name} at {datetime.datetime.now().strftime('%H:%M')}")
    time.sleep(FEEDING_DURATION_MINUTES * 60)  # Simulate feeding duration
    print(f"Finished feeding {pet.name}")

# Main scheduler
def run_scheduler():
    for _ in range(NUM_FEEDINGS):
        current_hour = datetime.datetime.now().hour
        for pet in pets:
            if is_time_to_feed(current_hour, pet.feeding_time):
                feed_pet(pet)
        time.sleep(FEEDING_INTERVAL_HOURS * 3600)  # Wait for the next feeding interval

# Print initial state
print("Pet Feeder Scheduler started.")
print(f"Pets: {pets}")
print(f"Feeding Interval: {FEEDING_INTERVAL_HOURS} hours")
print(f"Feeding Duration: {FEEDING_DURATION_MINUTES} minutes")
print(f"Number of Feedings per Day: {NUM_FEEDINGS}")

# Run the scheduler
run_scheduler()