# Generated by Cognia | 2026-07-25T11:31:48.978618
# Category: juego Minecraft
# Score: 7.0/10
# Origin: predefined category

print('\033[2J\033[H', end='')  # Clear terminal

# Constants
PLAYER_NAME = "Minecraft Player"
PLAYER_X, PLAYER_Y = 0, 0
WORLD_SIZE = 10
GRASS = 'G'
STONE = 'S'
AIR = 'A'
PLAYER_SYMBOL = 'P'

# World generation
world = [[GRASS if i % 2 == 0 else STONE for i in range(WORLD_SIZE)] for j in range(WORLD_SIZE)]

# Function to print the world
def print_world():
    for row in world:
        print(' '.join(row))

# Initial player position
world[PLAYER_Y][PLAYER_X] = PLAYER_SYMBOL

# Game loop
print(f"Bienvenido, {PLAYER_NAME}!")
print_world()

for _ in range(5):  # Simulate 5 actions
    # Simulate player movement
    PLAYER_X += 1 if PLAYER_X < WORLD_SIZE - 1 else 0
    PLAYER_Y += 1 if PLAYER_Y < WORLD_SIZE - 1 else 0
    PLAYER_X -= 1 if PLAYER_X > 0 else 0
    PLAYER_Y -= 1 if PLAYER_Y > 0 else 0

    # Update world
    world[PLAYER_Y][PLAYER_X] = PLAYER_SYMBOL

    # Print world
    print_world()

print("Juego terminado!")
print_world()
print('\033[2J\033[H', end='')  # Clear terminal

# Constants
PLAYER_NAME = "Minecraft Player"
PLAYER_X, PLAYER_Y = 0, 0
WORLD_SIZE = 10
GRASS = 'G'
STONE = 'S'
AIR = 'A'
PLAYER_SYMBOL = 'P'

# World generation
world = [[GRASS if i % 2 == 0 else STONE for i in range(WORLD_SIZE)] for j in range(WORLD_SIZE)]

# Function to print the world
def print_world():
    for row in world:
        print(' '.join(row))

# Initial player position
world[PLAYER_Y][PLAYER_X] = PLAYER_SYMBOL

# Game loop
print(f"Bienvenido, {PLAYER_NAME}!")
print_world()

for _ in range(5):  # Simulate 5 actions
    # Simulate player movement
    PLAYER_X += 1 if PLAYER_X < WORLD_SIZE - 1 else 0
    PLAYER_Y += 1 if PLAYER_Y < WORLD_SIZE - 1 else 0
    PLAYER_X -= 1 if PLAYER_X > 0 else 0
    PLAYER_Y -= 1 if PLAYER_Y > 0 else 0

    # Update world
    world[PLAYER_Y][PLAYER_X] = PLAYER_SYMBOL

    # Print world
    print_world()

print("Juego terminado!")
print_world()