# Generated by Cognia | 2026-07-21T19:53:08.743567
# Category: dashboard de inversiones con gráficos pastel y nombres de empresas|RUTA: AGENTE
# Score: 7.6/10
# Origin: predefined category

import random
from datetime import datetime

# Datos de ejemplo
empresas = ['Apple', 'Google', 'Microsoft', 'Tesla', 'Amazon']
invertido = [random.randint(1000, 5000) for _ in range(len(empresas))]
colores = ['red', 'green', 'blue', 'purple', 'orange']

print('\033[2J\033[H', end='')  # Limpiar terminal

# Imprimir encabezado
print(f"{'Dashboard de Inversiones':^80}")
print(f"{'Fecha: ' + datetime.now().strftime('%Y-%m-%d %H:%M'):^80}")
print('-' * 80)

# Imprimir valores invertidos
print(f"{'Empresa':<20} {'Invertido ($)'}")
for empresa, valor in zip(empresas, invertido):
    print(f"{empresa:<20} {valor:>20}")

print('-' * 80)

# Crear gráfico pastel
print("Gráfico Pastel de Inversiones:")
for i, (empresa, valor, color) in enumerate(zip(empresas, invertido, colores), 1):
    print(f"{i}. {empresa:<20} {'█' * int(valor / 100):<20} ${valor}")

print('-' * 80)
import random
from datetime import datetime

# Datos de ejemplo
empresas = ['Apple', 'Google', 'Microsoft', 'Tesla', 'Amazon']
invertido = [random.randint(1000, 5000) for _ in range(len(empresas))]
colores = ['red', 'green', 'blue', 'purple', 'orange']

print('\033[2J\033[H', end='')  # Limpiar terminal

# Imprimir encabezado
print(f"{'Dashboard de Inversiones':^80}")
print(f"{'Fecha: ' + datetime.now().strftime('%Y-%m-%d %H:%M'):^80}")
print('-' * 80)

# Imprimir valores invertidos
print(f"{'Empresa':<20} {'Invertido ($)'}")
for empresa, valor in zip(empresas, invertido):
    print(f"{empresa:<20} {valor:>20}")

print('-' * 80)

# Crear gráfico pastel
print("Gráfico Pastel de Inversiones:")
for i, (empresa, valor, color) in enumerate(zip(empresas, invertido, colores), 1):
    print(f"{i}. {empresa:<20} {'█' * int(valor / 100):<20} ${valor}")

print('-' * 80)