# Generated by Cognia | 2026-08-17T23:52:35.025683
# Category: di hola en 3 palabras
# Score: auto-asignado 7.1/10 (SIN VERIFICAR)
# Origin: predefined category

import random
import string

# Constants
NUM_WORDS = 3
GREETING = "hello"

# Generate three random words
random_words = [''.join(random.choices(string.ascii_lowercase, k=random.randint(3, 8))) for _ in range(NUM_WORDS)]

# Print the greeting in three words
print('\033[2J\033[H', end='')  # Clear terminal
print(f"{random_words[0]} {random_words[1]} {random_words[2]}")

# Verification
if GREETING in random_words[0] or GREETING in random_words[1] or GREETING in random_words[2]:
    print("Verification: PASS - 'hello' found in at least one of the words.")
else:
    print("Verification: FAIL - 'hello' not found in any of the words.")

# Output evidence
print(f"Generated words: {random_words}")
print(f"Number of words generated: {len(random_words)}")
print(f"Constants used: NUM_WORDS={NUM_WORDS}, GREETING='{GREETING}'")