# Generated by Cognia | 2026-07-20T00:43:40.084978
# Category: mapa de proyecto Python con ast: funcion mapear(directorio) que recorre los .py y devuelve para cada fichero la lista de clases y funciones con su linea, y funcion resumen(mapa) que lo formatea compacto; probar sobre un directorio temporal creado en el propio test con tempfile, con unittest y unittest.main(exit=False)
# Score: 6.5/10
# Origin: predefined category

import ast
import unittest
import tempfile
import os
import glob

class CodeParser(ast.NodeVisitor):
    def __init__(self):
        self.classes = []
        self.functions = []

    def visit_ClassDef(self, node):
        self.classes.append((node.name, node.lineno))
        self.generic_visit(node)

    def visit_FunctionDef(self, node):
        self.functions.append((node.name, node.lineno))
        self.generic_visit(node)

def mapear(directorio):
    mapa = {}
    for py_file in glob.glob(os.path.join(directorio, '*.py')):
        with open(py_file, 'r', encoding='utf-8') as file:
            tree = ast.parse(file.read())
        parser = CodeParser()
        parser.visit(tree)
        mapa[os.path.basename(py_file)] = {
            'classes': parser.classes,
            'functions': parser.functions
        }
    return mapa

def resumen(mapa):
    res = []
    for file, content in mapa.items():
        classes = ', '.join(f'{cls} (line {line})' for cls, line in content['classes'])
        functions = ', '.join(f'{func} (line {line})' for func, line in content['functions'])
        res.append(f"{file}: Classes: {classes if classes else 'None'}, Functions: {functions if functions else 'None'}")
    return '\n'.join(res)

class TestCodeMapping(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.mkdtemp()
        with open(os.path.join(self.temp_dir, 'test1.py'), 'w', encoding='utf-8') as f:
            f.write('class A: pass\ndef foo(): pass')
        with open(os.path.join(self.temp_dir, 'test2.py'), 'w', encoding='utf-8') as f:
            f.write('class B: pass\n\ndef bar(): pass\ndef baz(): pass')

    def tearDown(self):
        for file in glob.glob(os.path.join(self.temp_dir, '*.py')):
            os.remove(file)
        os.rmdir(self.temp_dir)

    def test_mapear(self):
        mapa = mapear(self.temp_dir)
        self.assertIn('test1.py', mapa)
        self.assertIn('test2.py', mapa)
        self.assertEqual(mapa['test1.py']['classes'], [('A', 1)])
        self.assertEqual(mapa['test1.py']['functions'], [('foo', 2)])
        self.assertEqual(mapa['test2.py']['classes'], [('B', 1)])
        self.assertEqual(mapa['test2.py']['functions'], [('bar', 3), ('baz', 4)])

    def test_resumen(self):
        mapa = {
            'test1.py': {'classes': [('A', 1)], 'functions': [('foo', 2)]},
            'test2.py': {'classes': [('B', 1)], 'functions': [('bar', 3), ('baz', 4)]}
        }
        res = resumen(mapa)
        expected = [
            "test1.py: Classes: A (line 1), Functions: foo (line 2)",
            "test2.py: Classes: B (line 1), Functions: bar (line 3), baz (line 4)"
        ]
        self.assertEqual(res.split('\n'), expected)

if __name__ == '__main__':
    print('\033[2J\033[H', end='')  # Clear terminal
    unittest.main(exit=False)
    print("Running demo...")
    temp_dir = tempfile.mkdtemp()
    with open(os.path.join(temp_dir, 'demo.py'), 'w', encoding='utf-8') as f:
        f.write('class C: pass\ndef qux(): pass\ndef quux(): pass')
    mapa = mapear(temp_dir)
    print(resumen(mapa))
    for file in glob.glob(os.path.join(temp_dir, '*.py')):
        os.remove(file)
    os.rmdir(temp_dir)