# Generated by Cognia | 2026-07-19T21:14:42.429894
# Category: pagina web que simule un dashboard de inversiones con movimiento: cotizaciones que cambian solas, grafico animado y variaciones en verde y rojo
# Score: 7.8/10
# Origin: predefined category

import random
import time

# Constants
NUM_STOCKS = 5
MAX_PRICE = 100.0
MIN_PRICE = 50.0
PRICE_CHANGE = 0.5
UPDATE_INTERVAL = 0.5
GRAPH_WIDTH = 20

# Sample stock data
stocks = [
    {"name": "AAPL", "price": random.uniform(MIN_PRICE, MAX_PRICE)},
    {"name": "GOOGL", "price": random.uniform(MIN_PRICE, MAX_PRICE)},
    {"name": "AMZN", "price": random.uniform(MIN_PRICE, MAX_PRICE)},
    {"name": "MSFT", "price": random.uniform(MIN_PRICE, MAX_PRICE)},
    {"name": "FB", "price": random.uniform(MIN_PRICE, MAX_PRICE)},
]

def clear_screen():
    print('\033[2J\033[H', end='')

def print_graph(price, width):
    filled = int(price * width / MAX_PRICE)
    return '[' + '=' * filled + ' ' * (width - filled) + ']'

def update_stock_prices():
    for stock in stocks:
        change = random.uniform(-PRICE_CHANGE, PRICE_CHANGE)
        stock["price"] += change
        stock["price"] = max(MIN_PRICE, min(MAX_PRICE, stock["price"]))

def display_dashboard():
    clear_screen()
    print("Investment Dashboard")
    print("-" * 30)
    for stock in stocks:
        price_str = f"${stock['price']:.2f}"
        graph = print_graph(stock["price"], GRAPH_WIDTH)
        color = "\033[92m" if stock["price"] >= stock["price"] - PRICE_CHANGE else "\033[91m"
        reset_color = "\033[0m"
        print(f"{stock['name']}: {color}{price_str}{reset_color} {graph}")

def main():
    try:
        while True:
            update_stock_prices()
            display_dashboard()
            time.sleep(UPDATE_INTERVAL)
    except KeyboardInterrupt:
        clear_screen()
        print("Exiting...")

if __name__ == "__main__":
    main()