# Generated by Cognia | 2026-07-20T00:14:37.409563
# Category: gestor de tareas con SQLite en memoria, pila de deshacer y tests unitarios que se ejecutan solos
# Score: 6.7/10
# Origin: predefined category

import sqlite3
import unittest

class TaskManager:
    def __init__(self):
        self.conn = sqlite3.connect(':memory:')
        self.cursor = self.conn.cursor()
        self.cursor.execute('CREATE TABLE tasks (id INTEGER PRIMARY KEY, description TEXT)')
        self.undo_stack = []

    def add_task(self, description):
        self.cursor.execute('INSERT INTO tasks (description) VALUES (?)', (description,))
        self.conn.commit()
        self.undo_stack.append(('add', description))

    def remove_task(self, task_id):
        self.cursor.execute('SELECT description FROM tasks WHERE id = ?', (task_id,))
        description = self.cursor.fetchone()
        if description:
            self.cursor.execute('DELETE FROM tasks WHERE id = ?', (task_id,))
            self.conn.commit()
            self.undo_stack.append(('remove', task_id, description[0]))

    def undo(self):
        if self.undo_stack:
            action, *args = self.undo_stack.pop()
            if action == 'add':
                self.cursor.execute('DELETE FROM tasks WHERE description = ?', (args[0],))
            elif action == 'remove':
                self.cursor.execute('INSERT INTO tasks (description) VALUES (?)', (args[1],))
            self.conn.commit()

    def list_tasks(self):
        self.cursor.execute('SELECT * FROM tasks')
        return self.cursor.fetchall()

class TestTaskManager(unittest.TestCase):
    def setUp(self):
        self.tm = TaskManager()

    def test_add_task(self):
        self.tm.add_task('Task 1')
        tasks = self.tm.list_tasks()
        self.assertEqual(len(tasks), 1)
        self.assertEqual(tasks[0][1], 'Task 1')

    def test_remove_task(self):
        self.tm.add_task('Task 1')
        task_id = self.tm.list_tasks()[0][0]
        self.tm.remove_task(task_id)
        tasks = self.tm.list_tasks()
        self.assertEqual(len(tasks), 0)

    def test_undo_add(self):
        self.tm.add_task('Task 1')
        self.tm.undo()
        tasks = self.tm.list_tasks()
        self.assertEqual(len(tasks), 0)

    def test_undo_remove(self):
        self.tm.add_task('Task 1')
        task_id = self.tm.list_tasks()[0][0]
        self.tm.remove_task(task_id)
        self.tm.undo()
        tasks = self.tm.list_tasks()
        self.assertEqual(len(tasks), 1)
        self.assertEqual(tasks[0][1], 'Task 1')

if __name__ == '__main__':
    # Clear terminal
    print('\033[2J\033[H', end='')
    
    # Demonstrate Task Manager
    tm = TaskManager()
    tm.add_task('Task 1')
    tm.add_task('Task 2')
    print("Tasks after adding two tasks:")
    print(tm.list_tasks())
    
    tm.remove_task(1)
    print("Tasks after removing task with id 1:")
    print(tm.list_tasks())
    
    tm.undo()
    print("Tasks after undoing last action:")
    print(tm.list_tasks())
    
    # Run tests
    unittest.main(argv=[''], exit=False)